### ISSUE TITLE
Support for context

### ISSUE THREAD

**Issue by BlackEdder** [kdheepak/taskwarrior-tui#1]
Would it be possible to support contexts? Or are they already supported and did I just miss them ;)

**Comment by kdheepak** [comment]
You didn't miss them! I just haven't figured out the best way to support them yet. Ideas welcome :) 

It seems like the best thing would be to add a new tab for all context related actions. I think we would want to be able to easily 1) create new contexts, 2) switch between contexts, 3) delete contexts, at the very least.

I haven't used contexts a lot though. I'm typically in "work" context all the time, and occasionally switch to a "personal" context. Can you describe how you use contexts? Just looking for ideas / inspiration.

**Comment by BlackEdder** [comment]
It sounds like I use them pretty much the same way as you do, so I think a simple hotkey to change context would be enough initially. Later it might be good to have a context editting mode where you can add context etc.

I know vit just uses the context that task is currently in, so to switch you switch context outside of vit and vit will then respect that change. I assume it does this by relying on the task command line to load tasks and the task command already respects the context setting.

**Comment by kdheepak** [comment]
I thought it would work that way as well here, but it turns out that `task export` doesn't respect the current `context`, i.e. always returns the full list of tasks. I'll have to see how `vit` does this and think more about how it can be implemented here.

**Comment by kdheepak** [comment]
I've added support for using the current context from taskwarrior. So if you switch contexts using `task context work` from the command line, `taskwarrior-tui` will show only `work` related tasks. I'll have to write some tests and then make a new release.

**Comment by StephanMeijer** [comment]
I would love to see this functionality

**Comment by kdheepak** [comment]
Can you clarify which functionality specifically? Currently `taskwarrior-tui` uses the context set by `task`. If you get the latest release this will "just work". 

Currently there's no way to switch contexts from within taskwarrior. But that's the next "task" I have for `taskwarrior-tui` :)

**Comment by kdheepak** [comment]
You can currently switch task contexts in `taskwarrior-tui` by hitting the `!` key, and then typing `task context work` and hitting `Enter`. The `!` key lets you run arbitrary shell commands. 

I think there's still room for a nice context switcher menu though, and will post here when I have updates on that.

**Comment by kdheepak** [comment]
I've added support for a context switcher!

![context-switcher mov](https://user-images.githubusercontent.com/1813121/97959948-a746ae00-1d6d-11eb-9ffe-8f76f2a2b32d.gif)

You can add new contexts either by editing your `~/.taskrc` or by running the context define from the command line or from inside `taskwarrior-tui` using the `!` shortcut. See https://taskwarrior.org/docs/context.html for more information.
