### ISSUE TITLE
Add readline

### ISSUE THREAD

**Issue by typebrook** [kdheepak/taskwarrior-tui#11]
Hi @kdheepak 
Is it possible to apply **readline** feature for filter input? (like https://github.com/kkawakam/rustyline)
It would make a tui better.

**Comment by kdheepak** [comment]
Thanks for opening the issue! This has been on my list of things to do. And thanks for linking that package. I think that could be a great addition here.

**Comment by kdheepak** [comment]
Thanks for the suggestion and opening this issue. I've added readline support in [v0.6.11](https://github.com/kdheepak/taskwarrior-tui/releases/tag/v0.6.11).

**Comment by kdheepak** [comment]
@typebrook if you find it doesn't work as readline should let me know! I have mainly used just `C-a` and `C-e` in the past.

**Comment by typebrook** [comment]
@kdheepak 
Well done! readline now works. 
But `C-h` (delete letter before caret) is not implemented. Would you like to add it later?

**Comment by kdheepak** [comment]
Sure! I'll be able to add it!

**Comment by kdheepak** [comment]
`C-h` should work now in https://github.com/kdheepak/taskwarrior-tui/releases/tag/v0.6.13.

**Comment by typebrook** [comment]
@kdheepak 
Many thanks! Now it is as useful as `tasksh` for me
