### ISSUE TITLE
Contexts Regression

### ISSUE THREAD

**Issue by nickwynja** [kdheepak/taskwarrior-tui#118]
I'm on 0.10.3 and contexts no longer seem to work. The list of contexts populate properly but when selecting one doesn't change the list.

**To Reproduce**

1. open up context list with `c`
2. select context by hitting enter
3. list remains unfiltered by the context

**Environment (please complete the following information):**

- Operating System:  Mac
- Installation:  Github release
- taskwarrior-tui version: 0.10.3

```bash
taskwarrior-tui --version
```
- task version: 2.5.1

```bash
task --version
```

**Additional context and information**

Possibly related to changes with the filters in #93?

**Comment by kdheepak** [comment]
You are right! I'm surprised it even worked in the past, it seems like it was always buggy. Anyway, I have a fix for it now. I'll also plan on adding more tests so that I can catch these regressions earlier.

**Comment by nickwynja** [comment]
@kdheepak Great, thanks! Tested on master and it's working nicely for me now.

**Comment by kdheepak** [comment]
Thanks for reporting the issue!

**Comment by kdheepak** [comment]
I've made a new release that has the fix for this issue: https://github.com/kdheepak/taskwarrior-tui/releases/tag/v0.11.0.
