### ISSUE TITLE
Context switcher not working

### ISSUE THREAD

**Issue by cyrinux** [kdheepak/taskwarrior-tui#127]
**Context switching broken**

Hi,
Thanks for this great tool.

On the last master and on the 10.4.1 version, i'm unable to make the context switcher working.
I press `c` then choose on of my context then when pressing `enter` the context doesn't become active.
On the 10.4.1, this become active but the task list is no filtered.

Any idea?

**Comment by kdheepak** [comment]
Thanks for reporting the issue! I believe this is the same issue as reported in https://github.com/kdheepak/taskwarrior-tui/issues/118. It should be fixed in the latest `master` branch though? Are you still experiencing the same issue. It seems to be working as expected for me.

**Comment by iordanisg** [comment]
Can confirm, switched to `taskwarrior-tui-git` on Arch and the context switching works as expected.

**Comment by kdheepak** [comment]
Thanks! I'll make a new release with this fix this week.

**Comment by cyrinux** [comment]
I just tested master too, works nicely, thanks you, i close this issue.

**Comment by kdheepak** [comment]
I made a new release that has a fix for this issue: https://github.com/kdheepak/taskwarrior-tui/releases/tag/v0.11.0
