### ISSUE TITLE
Pressing `d` on a task deletes it instead of completing it

### ISSUE THREAD

**Issue by C-Fergus** [kdheepak/taskwarrior-tui#129]
**Describe the bug**

Pressing `d` on a task deletes it instead of completing it, which is the action that should be performed when pressing `x`.

**To Reproduce**

1.  Add a task
2.  Open `taskwarrior-tui` and press the `d` key while the task is highlighted
3.  Exit `taskwarrior-tui`
4.  Execute `task limit:1 status:deleted rc.report.all.sort:end- all` and see that the task was deleted instead of completed.

**Environment (please complete the following information):**

- Operating System:  Linux
- Installation: arch
- taskwarrior-tui version: 0.11.0

```bash
taskwarrior-tui --version
```
- task version:

```bash
task --version
```

**Additional context and information**

Using `task ID done` from the command line completed the task as normal.

**Comment by kdheepak** [comment]
Oh my, I pushed a quick fix and a new release with this change. I swapped it in my configuration and that accidentally leaked into the wild. My bad. I'll write some tests for this so that something like this doesn't happen again. Sorry about the confusion.

**Comment by kdheepak** [comment]
You can try out this release for the fix: https://github.com/kdheepak/taskwarrior-tui/releases/tag/v0.11.1

**Comment by C-Fergus** [comment]
Haha, I'm not sure what it was that you were testing but the fix works perfectly. Thanks a million.

**Comment by kdheepak** [comment]
`v0.11.x` introduces keybinding configuration and I swap `x` and `d`.

**Comment by C-Fergus** [comment]
Ah right, I have only just started using it and didn't know it was a new feature. Thanks again for the quick fix.

**Comment by kdheepak** [comment]
Thanks for reporting the issue!
