### ISSUE TITLE
Bad handling of single quotes surrounded by quotes

### ISSUE THREAD

**Issue by b1two** [kdheepak/taskwarrior-tui#134]
**Describe the bug**

I like to surround the task description between quotes such as:
`proj:myproject "my task description" prio:H`
It works well when the description does not include single quotes, however trying to add a task with the following payload leads to errors:
`"a '"` (note that the quotes are included in the payload)
After trying to add this task, the files `backlog.data` and `undo.data` get corrupted and therefore taskwarrior is not usable anymore.

**To Reproduce**

* Try to add the following task:
`"a '"`

**Environment (please complete the following information):**

- Operating System: Linux debian sid
- Installation: Github master branch
- taskwarrior-tui version:

```bash
$ taskwarrior-tui --version
taskwarrior-tui 0.11.1
```
- task version:

```bash
$ task --version
2.5.3
```

**Additional context and information**

Content of the `backlog.data` after the bug:
```
{"description":"a \\
```
Content of the `undo.data` after the bug:
```
time 1615634410
new [description:"a \\---
```

**Comment by kdheepak** [comment]
Ouch that's bad. I wanted it such that we could add tasks like `finish bob's task` but once the fix is merged, now we'll just have to use `"finish bob's task" as we would in the terminal (i.e. `task add "finish bob's task").

**Comment by kdheepak** [comment]
Maybe in the future I can explore all the corner cases, and write solutions for tackling them all. It could be as simple as "if there's a single quote in a double quotes section of a string, don't escape it, otherwise do" but I'm not sure about it. So for now this will be a feature loss.

**Comment by kdheepak** [comment]
This fix is in this release: https://github.com/kdheepak/taskwarrior-tui/releases/tag/v0.12.0
