### ISSUE TITLE
Autocomplete when using the prompt

### ISSUE THREAD

**Issue by bergercookie** [kdheepak/taskwarrior-tui#136]
**Description**

Hi there, thanks for this plugin!

It would be very convenient to get autocompletion when adding new tasks.

This autocompletion could at first be rather basic and just autocomplete when pressing the up and down arrows, just like when using bash, but it could also be extended further to autocomplete project, tag names on <TAB>

**Comment by kdheepak** [comment]
Great idea! There’s some initial work on this in the `history` branch. The plan is to use bash / zsh history and add the commands that are run into there using a bash / zsh function. Once that is done, we’ll be able to add the Up and Down arrow functionality easily.

**Comment by kdheepak** [comment]
Related to https://github.com/kdheepak/taskwarrior-tui/issues/84

**Comment by kdheepak** [comment]
There's now support for history using the up and down arrow keys and tab completion based on the current task report. Let me know what you think if you get a chance to try it out!

**Comment by kdheepak** [comment]
Here's a gif of tab completion and history using the up arrow key in action:

![](https://user-images.githubusercontent.com/1813121/113711977-cfcb2f00-96a2-11eb-8b06-9fd17903561d.gif)
