### ISSUE TITLE
Support for user-defined commands

### ISSUE THREAD

**Issue by arozans** [kdheepak/taskwarrior-tui#14]
I have identified a few operations that I perform frequently in taskwarrior so I wrote small bash functions to save some time.
One of them is for a quick removing tasks from my "inbox" context and adding a project, it looks like that:
```
tp(){
        first_arg=$1
        second_arg=$2
        shift
        shift
        rest_args="$@"
        task mod $first_arg -in -inthe -hass -personal pro:$second_arg $rest_args 
}
```

Do you think it's possible to implement something similar in your TUI?

Thanks!

**Comment by kdheepak** [comment]
Awesome idea! Thanks for the suggestion! This will be in the next release :)

**Comment by kdheepak** [comment]
You should be able to use `!` now to enter a custom shell prompt, where you can type `tp 1 proj` and hit enter. `taskwarrior-tui` will run whatever you type in the `!` shell prompt as a subprocess.
