### ISSUE TITLE
Add shortcut for next tag

### ISSUE THREAD

**Issue by jdorel** [kdheepak/taskwarrior-tui#140]
**Description**

I often mark tasks as next, it would be super useful to have a dedicated shortcut for this (ex: n).

Maybe there should be a way to allow people to configure adding tags by shortcut. Either directly (ex: press n to add/remove next tag), or through some kind of tag menu (ex: press t, then n).

**Comment by kdheepak** [comment]
Great idea! I’m thinking by default 0-9 will be user configurable shortcuts. Of course, one would be able to remap it to a key of their choosing. I think 10 user definable shortcuts ought to be plenty?

**Comment by kdheepak** [comment]
I've added user defined shortcuts. As an example on how to use this, add the following to your `~/.taskrc`:

```
uda.taskwarrior-tui.shortcuts.0=~/local/bin/fn
```

Then create a file `~/local/bin/fn` with the contents you are interested in running when you hit the `0` key.

```bash
# contents of ~/local/bin/fn
source .env
task $1 mod +next
```

When you hit `0`, the following subprocess is run

```bash
~/local/bin/fn selected_task_uuid
```

which runs the script 

```
task $task_uuid mod +next
```

Obviously, you can rename the script and make it do something more complicated. This example was for illustration purposes.

Hope that helps!

**Comment by kdheepak** [comment]
This feature is available in this release: https://github.com/kdheepak/taskwarrior-tui/releases/tag/v0.12.0

Let me know if anything doesn't work as expected!

**Comment by nickwynja** [comment]
@kdheepak I can imagine that people will eventually want to do a lot of custom shortcuts and will run out of 10 defined shortcuts. I already have 5. This is a really satisfying start though and very clever to use the numbers as a fixed set of key combinations!

**Comment by kdheepak** [comment]
Maybe I’ll remove support for `0` for the shortcut as it is implemented right now, and use it as a prefix instead. Meaning you’ll still be able to press `8` to run the 8th shortcut but also `08` to run the 8th shortcut. And you’ll be able to press `088` to run the 88th shortcut defined. `88` will obviously run the 8th shortcut twice. That would allow a large number of shortcuts with configurable keys for just 9 shortcuts. 

Thoughts?

**Comment by kdheepak** [comment]
Also, I’m curious what 5 shortcuts you already have defined? Maybe it’ll give me ideas for my workflow too :) and potentially ideas for some features in the TUI.

**Comment by kdheepak** [comment]
I've decided to go ahead and reserve the `0` key for later. If we can think of a more elegant solution, I'll be able to allow `0` to be used as a shortcut again. For now, I'll make another release to reserve `0`, and this release will have just 9 shortcuts (`1`-`9`).

**Comment by kdheepak** [comment]
I made a new release with just 9 shortcuts: https://github.com/kdheepak/taskwarrior-tui/releases/tag/v0.12.1

**Comment by nickwynja** [comment]
Tried running a custom shortcut on `9` running the latest `0.12.1` and got this crash:

```
The application panicked (crashed).
  index out of bounds: the len is 9 but the index is 9
in src/app.rs, line 1093
thread: main
```

I use tmux extensively so I have scripts that open or navigate to custom UDAs. I have:

- `1`: Script to open custom URL uda on task
- `2`: Script to open a wiki page based on a wiki UDA on the task
- `3`: Navigate to mutt and search for msg-id stored in UDA. (I have an accompanying script that I run from mutt to create a task and add the current msg-id to the UDA.)
- `4`: On some tasks, I store a phone number as a UDA can this script dials the number using [Telephone](https://www.64characters.com/telephone/)
- `5`: one-liner script for `task mod $1 pro:work`
- `9`: `task sync`

The ability to run the custom shortcuts makes taskwarrior-tui _the most_ powerful and extensible productivity system I've ever seen.

**Comment by kdheepak** [comment]
> Tried running a custom shortcut on 9

Grr, I'm so dumb. Fixed in https://github.com/kdheepak/taskwarrior-tui/releases/tag/v0.12.2.

> The ability to run the custom shortcuts makes taskwarrior-tui _the_ most powerful and extensible productivity system I've ever seen.

:) I'm glad people are finding it so useful!

**Comment by kdheepak** [comment]
Also, I think running `task sync` maybe should be a built in feature. 

It is good to see your list btw! Super cool!

**Comment by jdorel** [comment]
Super nice work ! (And super reactive :heart: )

Maybe you could use something like this :
```
uda.taskwarrior-tui.functions.default-user-location=<folder(s)>
uda.taskwarrior-tui.functions.<function_name>.keyconfig=<key>
uda.taskwarrior-tui.functions.<function_name>.location=<location>
```
This would allow any shortcut, and any feature like a `task sync` shortcut could be implemented using this simple framework ?

**Comment by kdheepak** [comment]
> ```
> uda.taskwarrior-tui.functions.default-user-location=<folder(s)>
> uda.taskwarrior-tui.functions.<function_name>.keyconfig=<key>
> uda.taskwarrior-tui.functions.<function_name>.location=<location>
> ```

Maybe I'm just slow today but I'm not following how this would work? Can you elaborate?

**Comment by jdorel** [comment]
For exemple, one could have the following in his `taskrc` file : 
```
uda.taskwarrior-tui.functions.default-user-location=~/.config/taskwarrior-tui/functions/
uda.taskwarrior-tui.functions.set-next-tag.keyconfig=n
uda.taskwarrior-tui.functions.set-next-tag.location=set-next-tag.sh
```
And the file `~/.config/taskwarrior-tui/functions/set-next-tag.sh` would contain :
```
task $1 mod +next
```
We could even do without the `uda.taskwarrior-tui.functions.set-next-tag.location` if by default we are looking for `.sh` files. We would use the `<function_name>` (`set-next-tag` in the example) as a filename.

Default functions location could be :
```
/usr/lib/taskwarrior-tui/functions  - For functions installed globally by package manager
/usr/local/lib/taskwarrior-tui/functions  - For functions installed manually for the whole system (maybe it is not necessary ?)
~/.config/taskwarrior-tui/functions  - For functions specific to a user, that could override functions defined in /usr/lib
```

**Comment by kdheepak** [comment]
Ah, I get it now. That would be a powerful feature if implemented. I’ll have to think a little bit about how to go about doing it. I imagine there’ll be a little bit of refactoring required. Though I’d really like to improve test coverage before any refactoring. I’ll have more confidence that I’m not causing a regression. 

Maybe we should create a new issue to track that feature request?

**Comment by vizcay** [comment]
@kdheepak it is possible to use the shortcuts to have custom filter strings? I usually have around a handful of filters that I would love being able to swith around fast..

**Comment by kdheepak** [comment]
That’s a good idea. Can you open a new issue for it? I won’t be able to get to it for a couple of weeks but it should be fairly straight forward to implement.

**Comment by vizcay** [comment]
@kdheepak sure: https://github.com/kdheepak/taskwarrior-tui/issues/241.

**Comment by kdheepak** [comment]
It looks like there's a need for folks to open nvim as part of the shortcuts. See https://github.com/kdheepak/taskwarrior-tui/issues/244.

This means, when the shortcut is run, `taskwarrior-tui` has to necessarily get out of tui mode, run the shortcut and then enter the tui mode again. Maybe I should have done this from the start. It does make for a nicer experience if you are printing stuff to stdout from the shortcut.

If I merge this PR (https://github.com/kdheepak/taskwarrior-tui/pull/245), then when someone runs a shortcuts, the screen will "blink" (exit TUI and enter TUI again). Would people in this thread be able to test this out and provide feedback? 

Here's a screen recording of what it looks like when I have a shortcut that just echoes the task uuid:

https://user-images.githubusercontent.com/1813121/126064077-4e79c52a-e20e-430c-8244-10bd5e4aeb4e.mov

If no serious objection is raised, I'm inclined to merge this PR. It's a simple and straightforward implementation and my guess is that the screen blinking will be a minor inconvenience. 

Once a rewrite happens, I'll be able to enable background shortcuts and this annoyance will go away.

**Comment by nickwynja** [comment]
I'm seeing an issue where shortcut scripts seem to execute twice. I have a custom shortcut:

```
uda.taskwarrior-tui.shortcuts.1=~/.dotfiles/taskwarrior/nav-url.sh
```

which is the following script:

```
#!/bin/bash

URL=$(task _get $1.url)

if [[ "$URL" != "" ]]; then
     /usr/local/bin/brave $URL
fi
```

This assumes you have the following UDA and a task with that UDA defined.

```
uda.url.type=string
uda.url.label=URL
```

What I'm seeing in this case is that _two_ tabs are opened. Other scripts I have that open something in a tmux pane end up with two panes but this is the simplest way to reproduce.

**Comment by kdheepak** [comment]
That is so strange. Would you be able to try a shortcut that just echoes the task uuid (i.e. `echo $1`)?

**Comment by kdheepak** [comment]
Omg, it does open 2 URLs for me. So strange! I'll look into this. Thanks for reporting!

**Comment by kdheepak** [comment]
@nickwynja thanks for testing it out. I was forking the process twice but only printing to stdout once and that made me think I was calling it just once. The PR was in fact calling the shortcut twice every time. Oof. I've fixed it now in the most recent commit. 

Thoughts on the exiting and entering TUI for calling shortcuts? It doesn't feel like a disruption to me but I wanted to get the perspective of a power user.

**Comment by nickwynja** [comment]
> Thoughts on the exiting and entering TUI for calling shortcuts? It doesn't feel like a disruption to me but I wanted to get the perspective of a power user.

Because there was previously no visual feedback for long running scripts, exiting and re-entering is actually a UX improvement to me. My shortcut for `task sync` would often run long and error but I wouldn't know. I think this works well that I can write shortcut script that provide feedback through stdout and behaves in similar ways as `<shell-escape>` in mutt.

**Comment by kdheepak** [comment]
Awesome! I’ll merge and make a new release! Thanks for the feedback!
