### ISSUE TITLE
Crash referencing report.next.filter config

### ISSUE THREAD

**Issue by nickwynja** [kdheepak/taskwarrior-tui#157]
**Describe the bug**

The current build of master crashes for me. I believe it's related to this commit: https://github.com/kdheepak/taskwarrior-tui/commit/55c04b702eac48aacd8c9f6820b8e2cc1962f58d

**To Reproduce**

I'm using a custom `report.next.filter` to remove `limit:page` but it crashes for me whether I have this configuration or not:

```
# add custom attributes to 'next' report
report.next.filter=status:pending
report.next.columns=id,depends,priority,project,tags,recur,due.relative,until.remaining,description,entry.age,urgency
report.next.labels=ID,Dep,P,Project,Tag,Recur,Due,Until,Description,Age,Urg
```

**Additional context and information**

```
The application panicked (crashed).
  called `Option::unwrap()` on a `None` value
in src/config.rs, line 312
thread: main
```

**Comment by kdheepak** [comment]
Ugh. Sorry about that. I’ll look into it right away.

**Comment by kdheepak** [comment]
Hmm, I tried your configuration and it works for me. I tried removing `report.next.filter` and it still works for me. What version of `taskwarrior` are you using?

**Comment by kdheepak** [comment]
```
$ task --version
2.5.3
```

**Comment by kdheepak** [comment]
Also, can you run `task show report.next.filter` and share the output with me?

**Comment by nickwynja** [comment]
I just realized the error is coming from something else. I use a symlink to switch themes when I do a system-wide theme change so in my config I have:

```
include ~/.dotfiles/taskwarrior/solr.theme
```

For some reason the symlink was deleted. 

In that state, `task` gives this output:

```
$ task
Could not read include file '/Users/nickwynja/.dotfiles/taskwarrior/solr.theme'.
```

So it looks like this is more of an issue handling `include` errors or general `task` config problems?

**Comment by nickwynja** [comment]
Sorry for the false alarm!

**Comment by kdheepak** [comment]
Ah, but this worked before? Or was this a recent change in your configuration?

**Comment by kdheepak** [comment]
I've improved the error message ever so slightly in a commit directly to the `master` branch. 

<img width="945" alt="Screen Shot 2021-03-28 at 8 50 31 AM" src="https://user-images.githubusercontent.com/1813121/112756494-a9bad600-8fa2-11eb-8847-2d30d62e0170.png">

I think better error messages is something else that needs to be worked on.

**Comment by nickwynja** [comment]
I had run into issues before with this symlink missing and I think `taskwarrior-tui` would start but with no tasks. So there is a change in taskwarrior-tui's behavior after the above commit. Maybe running `task diag` on start and checking for a non-zero output could help. If it's non-zero, echoing `task`'s output might be most clear.

**Comment by kdheepak** [comment]
That's a good idea! For now, I've updated the latest commit to show `task diagnostics` along with the error.

```
Backtrace omitted. Run with RUST_BACKTRACE=1 to display it.
Run with RUST_BACKTRACE=full to include source snippets.

The application panicked (crashed).
  Unable to run `task show report.next.filter`.

  TASKRC override: /Users/$USER/gitrepos/taskwarrior-tui/tests/data/.taskrc
  Could not read include file '/Users/$USER/.dotfiles/taskwarrior/solr.theme'.

  Please check your configuration or open a issue on github.
in src/config.rs, line 292
thread: main
``` 

Still, your suggestion is better. I'll incorporate it in a future PR. Ideally, the user should never see a panic. But currently I have a few cases where that might happen (if `task` is not installed, if `task` is misconfigured etc), and I'll have to propagate the errors more cleanly. I'm hoping this is a good enough patch for now.
