### ISSUE TITLE
Input display is cut off when adding or modifying long tasks

### ISSUE THREAD

**Issue by nickwynja** [kdheepak/taskwarrior-tui#159]
**Describe the bug**

When a really long task, filter, etc is inputted the input does not scroll to display additional text.

**To Reproduce**

Hit `a` to add a new task and then type enough text to fill up the entire input. When you get to the edge of the input, the input will continue to accept characters but the input will not scroll to keep showing you what you are typing.

This happens with any of the input scenarios, like adding, modifying or filtering.

**Environment (please complete the following information):**

- Operating System:  Mac
- Installation:  git pull
- taskwarrior-tui version: master

```bash
taskwarrior-tui --version
```
- task version:

```bash
task --version
```

**Additional context and information**

**Comment by kdheepak** [comment]
I thought I had addressed this! Thanks for reporting. I’ll look into it today!

**Comment by kdheepak** [comment]
It looks like this never worked, but I could have sworn I tested this! Anyway, this is addressed in an upcoming PR.

**Comment by nickwynja** [comment]
Fix works nicely for me! Thanks again for all your work on this.

**Comment by kdheepak** [comment]
Thanks for testing and reporting the issue! Once the tests pass, I'll merge the PR.

**Comment by kdheepak** [comment]
This fix is available in https://github.com/kdheepak/taskwarrior-tui/releases/tag/v0.13.0.
