### ISSUE TITLE
Tab completion

### ISSUE THREAD

**Issue by Petemir** [kdheepak/taskwarrior-tui#163]
**Description**

It gets a bit cumbersome to type the same things over and over, and tab completion would make that a little less annoying.

**Solution**

Tab completion for the input (add task, modify task, filter task) section. Do you think it is feasible? To suggest/complete tags, projects, etc.

**Comment by kdheepak** [comment]
This is a great idea and it is definitely one of the current pain points of `taskwarrior-tui`. This is related to #84  and #136. 

In the most recent release though multiple selection has landed (#139), which should alleviate the pain a little if you are willing to adapt your workflow some. You’ll have to select multiple tasks and then modify then all. There’s also some additional changes in the latest release that prefills more information when you use modify (#162), which I think is a nice quality of live improvement. 

But this still doesn’t solve autocomplete / tab suggestions when using `add` and `filter`. That will likely be the next feature I work on for this project. I’ll leave this issue open till then. 

One thing that it is not clear for me is what the best use interface is going to be for showing suggestions. I’ll have to experiment with a couple of options before picking one that feels right. I’m open to ideas and suggestions here.

**Comment by kdheepak** [comment]
The latest release adds history and prefilling of information for task modification: https://github.com/kdheepak/taskwarrior-tui/releases/tag/v0.13.3

You'll have to set `uda.taskwarrior-tui.task-report.pre-fill-task-meta-data=true` to your `.taskrc` for the prefilling to work.

**Comment by Petemir** [comment]
Amazing, thank you :) .

**Comment by kdheepak** [comment]
You are too quick to reply! I wanted to say that this is the first iteration of tab completion. I think there's more improvements possible to make it a smoother experience. At the moment, when a tab completion item is selected using `Enter`, it just blindly appends it to the command prompt string. Ideally, it would append the completion only or something smarter. This is a good first step though. I'll make a new release shortly.

**Comment by kdheepak** [comment]
You can try it out in this release: https://github.com/kdheepak/taskwarrior-tui/releases/tag/v0.13.7.

**Comment by kdheepak** [comment]
Here's a gif of it in action:

![](https://user-images.githubusercontent.com/1813121/113711977-cfcb2f00-96a2-11eb-8b06-9fd17903561d.gif)

**Comment by kdheepak** [comment]
I think tab complete is a lot better now. It is context specific (i.e. `due:<TAB>` shows only `due:...` completion candidates). The full list is available when you tab on an empty space. Also, after typing `project:<TAB>` and selecting a completion candidate, if you hit enter, it picks completes the prompt correctly (i.e. the prompt is updated to `project:current` instead of `project:project:current`).

Hopefully, with that tab completion will be a lot nicer to use.

**Comment by Petemir** [comment]
Yeah, it is! Thank you very much, that was quick :smile:
