### ISSUE TITLE
Metadata shows inline on modify command

### ISSUE THREAD

**Issue by nickwynja** [kdheepak/taskwarrior-tui#164]
**Describe the bug**

New in `v0.13.0` there's a change in behavior to modifying a task. Prior to `0.13`, when you modify a task by hitting `m`, the input would just show the description of the task, like `Pay parking invoice for April`. In `0.13`, modify sets the input to `Pay parking invoice for April due:'2021-03-31T23:59:59'`. To update the due date I can change the date that shows up in the input or remove by appending `due:`. If there's a tag I want to modify, the tag will show up in the input now but removing the text of the tag doesn't work, you have to use `-tag`.

**To Reproduce**

Select a task with metadata like a due date, project, or tag and hit `m`. The metadata will show up in the input along with the description.

**Environment (please complete the following information):**

- Operating System:  Mac
- Installation:  git
- taskwarrior-tui version: 0.13.0
- task version: 2.5.1

**Additional context and information**

I preferred the original behavior where metadata didn't show but you could modify the description inline. I'm not sure whether the new behavior is intended but I find it less intuitive. If it is intended, certain things like removing the text of a tag should remove the tag.

**Comment by nickwynja** [comment]
Oh seeing #162 now. Will read more into the background of this.

**Comment by kdheepak** [comment]
It is intended behavior. I thought it would be easier to modify tasks if more information was pre-populated. Like, right now it is easier to increase the due date by 1. I also think now it is easier to remove tags. Previously, you had to subtract all the tag names (`-TAG1 -TAG2 ...`) but now you just have to change a few `+` to `-` and don't have to type the actual tag names. Once history works better I think it'll be even more useful in my opinion.

Can you clarify what you find less intuitive? I can very easily add this as optional behavior.

**Comment by kdheepak** [comment]
Alternatively, I can add a keyboard shortcut while editing that let's you pre-fill content.

**Comment by kdheepak** [comment]
Also, there's read line like support using emacs keybindings, so navigating around in prompt can also be efficient.

https://github.com/kdheepak/taskwarrior-tui/blob/be12852bb79e59c67bc3a7ac33a566047c9453f6/src/app.rs#L2303-L2314 

Anyway, that was my thinking at least when adding this. I'm open to feedback!

**Comment by nickwynja** [comment]
I'll play around with it and see if I get used to it. I can understand how being able to see and edit the data could be easier to change. For that objective, I like using `e` though. I think what was unintuitive at first was that it now behaves differently than `task mod` in the CLI where you just write the update rather than 'edit' what exists. Modifying one task now also behaves a bit differently than a single task. These all might be minor things but worth bringing them up at least.

**Comment by kdheepak** [comment]
I’ll have to experiment with using it more. In my testing I found it a useful. 

Also there’s a bug with  how `due:date` is displayed  because of how / when it is stored in taskwarrior exports. I’ll have to look into the source of `taskwarrior` to figure out what additional logic they have to handle local time zones. I’m mentioning it here even though it’s not directly related to the issue you posted.

**Comment by kdheepak** [comment]
I made it configurable and set to `false` by default so that I can test it more before pushing it on all users. I'll make a new release with the change. I think once history works well it'll be worth the change.

**Comment by kdheepak** [comment]
For reference, this feature was partly inspired by issue #163.
