### ISSUE TITLE
taskwarrior-tui crashes when adding recurring or waiting tasks

### ISSUE THREAD

**Issue by gbstan** [kdheepak/taskwarrior-tui#183]
It seems that adding a recurring/waiting task causes a crash of taskwarrior-tui. The task is correctly added to taskwarrior but the TUI interfaces crashes.

**To Reproduce**

1. Launch taskwarrior-tui
2. Add a task (press "a")
3. Test due:1week recur:yearly wait:due-2days

This leads to:

```bash
Backtrace omitted. Run with RUST_BACKTRACE=1 to display it.
Run with RUST_BACKTRACE=full to include source snippets.

The application panicked (crashed).
  called `Option::unwrap()` on a `None` value
in src/app.rs, line 1629
thread: main
```

**Environment (please complete the following information):**

- Operating System: MacOS 10.15.7
- Installation: home-brew
- taskwarrior-tui version: 0.13.11

```bash
taskwarrior-tui --version
```
- task version: 2.5.3

```bash
task --version
```

**Additional context and information**

**Comment by kdheepak** [comment]
Thanks for reporting! Ugh, it seems my recent change to jump to the task added introduced this bug. This is fixed in https://github.com/kdheepak/taskwarrior-tui/releases/tag/v0.13.12.

**Comment by gbstan** [comment]
Amazing! Thank you for being so responsive and thorough.
