### ISSUE TITLE
Add Ctrl+Arrow for move to next/previous word

### ISSUE THREAD

**Issue by Petemir** [kdheepak/taskwarrior-tui#186]
**Description**

One usual navigation method on text input fields is to use `Ctrl+{Right|Left}` arrows for jumping to the next/previous word. Although taskwarrior-tui supports this type of navigation with emacs-style (I think, I don't use emacs :D) bindings, it doesn't work with the `Ctlr+arrow` approach.

**Solution**

Support `Ctrl+{Right|Left}` shortcuts for moving between words. Apparently, different systems handle `Ctrl+arrow` shortcuts differently, but one of the already used libraries (crossterm) supports [key events with KeyModifiers](https://docs.rs/crossterm/0.19.0/crossterm/event/index.html), so perhaps that cross-platform problem would be solved. _I think_ (I tried and failed, but I don't know rust, so that's one possible reason :) ) it should be possible without much overhead, but as always, if it is too big of a request, I'll just learn the emacs bindings!

**Edit**: ctrl+delete / ctrl+backspace for deleting whole words would also be cool :) .

**Comment by kdheepak** [comment]
I think this is a neat idea. However, `Ctrl+Left` and `Ctrl+Right` are already keyboard shortcuts for moving between desktops on a Mac. So I could use `Alt+Left` and `Alt+Right` for doing this. Thoughts? 

I think the `Ctrl+delete` and `Ctrl+backspace` would be neat too! Thanks for the suggestion!

Usually adding a new keybinding would be super straightforward, so I'd have walked you through how to make a PR for this :) But in this case I haven't set it up for handling `Ctrl` + `non character` key bindings so I have to modify the code a little for this to work. I'll make a PR with this change shortly :)

**Comment by kdheepak** [comment]
Hmm, this might not be possible as I initially thought. I think `Ctrl/Alt+Left/Right` cannot be captured by the terminal. Similarly for `Ctrl+delete` and `Ctrl+backspace`. I'm using an example from crossterm-rs to check: https://github.com/crossterm-rs/crossterm/blob/92f62ba86f762e16c70e53b45b76d529a8f1ee13/examples/event-read.rs

However, depending on the terminal emulator you are using, you can configure it to send the corresponding keystrokes. If you do that, you can use `Ctrl+Left` to send `Alt+Char('b')` and that will allow you to go back a word in any shell prompt, including the prompt in `taskwarrior-tui`.

It does look like this cannot be resolved in `taskwarrior-tui` unfortunately.

**Comment by Petemir** [comment]
Thanks for trying!
