### ISSUE TITLE
Filtering with `Marc` doesn't filter

### ISSUE THREAD

**Issue by Petemir** [kdheepak/taskwarrior-tui#187]
I have a curious problem, and I am not sure if it is on my side or not. 

My supervisor is called Marc, and I wanted to search for a task that had his name on the description. Yet, when I write on the "Filter Tasks" field the text "Marc", there are absolutely no changes in the list of tasks. Only with the first "M", I see tasks whose description start with "M", but as soon as I add the following "a", all the tasks appear. If I add any other letter at the end (e.g., making the word "Marc**o**" instead), then the task list shows empty (as expected).

I think this also happens with other words. When I start writing "urgency" (also with "description") the task list is modified (getting empty), but when I put the last "y" it shows everything again. Probably it has to do with taskwarrior(-tui) not knowing if what I am writing will be a field-based filter, or just a plain text (i.e., in description field) filter.

If the last hypothesis is true, perhaps writing the ":" in the current word could be used as an indicator that the current word is a field-based filter? (i.e., show the full task list when I write ":" after "urgency"/"description"/etc. ; although I still wouldn't know which field matches with "Marc" :) ).

**To Reproduce**

- [ x ] Reproducible using the test data located here: <https://github.com/kdheepak/taskwarrior-testdata/>

(fyi I first pressed 'm' instead of '/', so disregard that part)

![Peek 2021-04-13 14-31](https://user-images.githubusercontent.com/287105/114552630-17365a00-9c65-11eb-8b03-0794f824ac5f.gif)

**Environment (please complete the following information):**

- Operating System: Linux
- Installation: github releases
- taskwarrior-tui version: v0.13.12

**Comment by kdheepak** [comment]
Thanks for opening such a detailed issue, and with the gif as well! So, as you mentioned, `taskwarrior-tui` just forwards the typed `filter` into `task export`. Meaning, if you run `task description` in the command line, it shows all tasks that have a description, OR if you type `task urgency` it shows all tasks that have an urgency. These are usually all the tasks though. For example, try `task due` or in `taskwarrior-tui` try opening the filter prompt and typing `due`. It should show you only tasks that have a `due` date associated with it. When you typing `due:` though, it shows all tasks that it knows _don't_ have a due date associated with it.

>  perhaps writing the ":" in the current word could be used as an indicator that the current word is a field-based filter?

So, while I can see why you are asking for a change in behavior here, I'm not sure it'll work well if someone _wants_ to see tasks without `due` dates or tasks with and without a `project`. Does that make sense?

> Only with the first "M", I see tasks whose description start with "M", but as soon as I add the following "a", all the tasks appear.

This is perplexing to me! I would have said that this is a bug, however I'm also not able to replicate it.

<img width="560" alt="Screen Shot 2021-04-13 at 8 15 46 AM" src="https://user-images.githubusercontent.com/1813121/114567532-8e9dc680-9c30-11eb-893f-3132a111ab73.png">
<img width="560" alt="Screen Shot 2021-04-13 at 8 16 05 AM" src="https://user-images.githubusercontent.com/1813121/114567545-92314d80-9c30-11eb-9f7f-2171d4c445be.png">
<img width="560" alt="Screen Shot 2021-04-13 at 8 16 20 AM" src="https://user-images.githubusercontent.com/1813121/114567550-93627a80-9c30-11eb-80bf-6d64efe99efd.png">

Can you try running `task Mar` and `task Marc` from the command line and share what the output is?

**Comment by kdheepak** [comment]
Also, can you share what version of `taskwarrior` you are using?

**Comment by Petemir** [comment]
> So, while I can see why you are asking for a change in behavior here, I'm not sure it'll work well if someone _wants_ to see tasks without `due` dates or tasks with and without a `project`. Does that make sense?

OK, I totally get the "urgency"/"urgency:", so don't worry :). I added that part more as context because perhaps there was some hidden field with "Marc" that I couldn't easily see. 
 
> Can you try running `task Mar` and `task Marc` from the command line and share what the output is? 

The problem still happens with just calling taskwarrior 

`task M` (OK)
<img width="543" alt="image" src="https://user-images.githubusercontent.com/287105/114570488-27a30080-9c76-11eb-98a4-253f9e2f2bc0.png">

`task Mar` (not OK, idem `task Ma`)
<img width="578" alt="image" src="https://user-images.githubusercontent.com/287105/114570660-4f926400-9c76-11eb-977d-a3010e05d0a2.png">

`task Marc` (not OK, same output as `task Ma` and `task Mar`)
<img width="578" alt="image" src="https://user-images.githubusercontent.com/287105/114570775-6638bb00-9c76-11eb-95ca-98735436fff5.png">

`task Marco` (OK again)
<img width="566" alt="image" src="https://user-images.githubusercontent.com/287105/114570855-781a5e00-9c76-11eb-8526-03e1dabb8be7.png">

> Also, can you share what version of taskwarrior you are using?

I have version 2.5.1, from Ubuntu's repository.

**Comment by kdheepak** [comment]
Thanks for adding as much context in the original issue post as possible :) 

Can you try a more recent version of `Taskwarrior`? 2.5.3 preferably?

**Comment by Petemir** [comment]
As evidenced by my previous post, this is obviously a taskwarrior issue. 

With taskwarrior v2.5.3 I do not have this exact problem anymore, although it still happens with `marc` (i.e., no capital M), and from `mar` (`task mar` and `task marc`). Perhaps you can reproduce it that way, but it isn't a taskwarrior-tui problem :).

**Comment by kdheepak** [comment]
This is because `task march` results in the entire task list being shown lol. And `task mar` and `task marc` probably expand to `task march` internally in `taskwarrior`. The same thing happens for `jan`, `feb`, etc. 

As of right now I don't know how to make it filter just tasks with `marc` in them. Maybe we should open an issue on the `taskwarrior` repository. I would have expected `task "marc"` to not behave the same way as `task march`.
