### ISSUE TITLE
Help is not fully shown

### ISSUE THREAD

**Issue by amatosg** [kdheepak/taskwarrior-tui#188]
**Describe the bug**
When pressing the "?" key, the help window will be cropped to fill the screen, not showing all availables commands

**To Reproduce**

- [ ] Reproducible using the test data located here: <https://github.com/kdheepak/taskwarrior-testdata/>

Steps to reproduce the behavior: Press "?"

**Environment (please complete the following information):**

- Operating System: Linux
- Installation: Arch Linux
- taskwarrior-tui version:  0.13.12
- task version: 2.5.3

**Additional context and information**
![tt-001](https://user-images.githubusercontent.com/42916953/114586548-6753f300-9c4a-11eb-82e8-d912ba802826.png)
![tt-002](https://user-images.githubusercontent.com/42916953/114586559-6b801080-9c4a-11eb-878a-3f7cde839604.png)

**Comment by kdheepak** [comment]
You can use `j` and `k` to scroll the help window.

**Comment by kdheepak** [comment]
I'm closing the issue! Feel free to re-open if you still need help or open a new issue if you have other questions!
