### ISSUE TITLE
Project autocompletion when annotating a task

### ISSUE THREAD

**Issue by jdorel** [kdheepak/taskwarrior-tui#191]
**Description**

Currently, project autcompletion only works when creating a new task. I often add tasks without specifying any metadata as a way of quick capture (a sort of inbox).

**Solution**

Implement the same project completion as when creating a task.

**Additional context**

**Comment by kdheepak** [comment]
Thanks for opening an issue! I didn't realize that `task annotate 1 +test` worked the same way `task modify 1 +test` works. You learn something new every day.

I made a PR for this feature. Once I merge it, I'll make a new release.

**Comment by kdheepak** [comment]
This feature is available in https://github.com/kdheepak/taskwarrior-tui/releases/tag/v0.13.14.
