### ISSUE TITLE
Access different report

### ISSUE THREAD

**Issue by jdorel** [kdheepak/taskwarrior-tui#193]
**Description**

From what I understand, currently only the `next` report is accessed. The idea would be to access other filters.

My use case would be to access the `inbox` filter, which search for pending task without project or priority.

**Solution**

It would be nice to access this directly from the CLI, because it would permit aliasing : 
```
alias tinbox='taskwarrior-tui --report=inbox
```

But access from the interface itself could also be interesting.

**Additional context**

I know context exists, but combining reports and context is useful, for exemple : I am in the `work` context, and I want the `inbox` report. Also it could be interesting to access context directly from the CLI also.

**Comment by kdheepak** [comment]
Thanks for opening the issue! I think this is a good idea. Ideally, users will be able to switch reports from within the TUI but that'll involve some refactoring. For now, I've added a command line argument `--report`. I'll make a new PR in the future that adds support for picking from existing reports within the TUI and adding a context command line argument as well.
