### ISSUE TITLE
When using `v` in selection mode for multiple selection, the current position indicator is not visable

### ISSUE THREAD

**Issue by xarthurx** [kdheepak/taskwarrior-tui#197]
**Describe the bug**

Normal mode:
![image](https://user-images.githubusercontent.com/1921878/116707750-5091f800-a9cf-11eb-8408-e0d38f4bedea.png)

`v` in selection mode:
![image](https://user-images.githubusercontent.com/1921878/116707893-75866b00-a9cf-11eb-8df9-0e4b417dab37.png)

You can see the tasks that are selected, but don't know which line the current cursor is located in unless by referencing the bottom panel.

Would be good to keep the `dot` indicator to show the current line.

**Comment by xarthurx** [comment]
BTW, coming from the `VIT` for taskwarrior, and I like this TUI much better.

**Comment by kdheepak** [comment]
Thanks for the compliment and I'm glad you are finding it useful.

> You can see the tasks that are selected, but don't know which line the current cursor is located in unless by referencing the bottom panel.
> 
> Would be good to keep the dot indicator to show the current line.

I see what you are saying. It would be nice to have the dot indicator shown somehow as well. I'll look into this feature request. I don't want to add a new column and shift the columns though. I think I can use a distinct symbol for when it is selected and highlighted and when it unselected and highlighted. I'll give it some thought and experiment with a few symbols and post here when I make progress on that.

Although, I will say that there may be a misconfiguration in either your terminal or your taskwarrior-tui setup. Can you check with "bold" works in your terminal setup?

This is what it looks like for me. The current "selection" is always highlighted using the bold style.

<img width="200" alt="Screen Shot 2021-04-30 at 8 24 28 AM" src="https://user-images.githubusercontent.com/1813121/116708996-7dbdb680-a98d-11eb-919a-145548e05f52.png">
<img width="200" alt="Screen Shot 2021-04-30 at 8 24 17 AM" src="https://user-images.githubusercontent.com/1813121/116709031-857d5b00-a98d-11eb-89fe-83c411c6cdba.png">

This is why this hasn't been an issue for me. I'm not sure why it doesn't do that for you though.

**Comment by xarthurx** [comment]
I see...

I'm using Windows Terminal and the `WSL` for accessing TaskWarrior.
Based on the issue here: https://github.com/microsoft/terminal/issues/109

No, `bold` is not currently supported...

**Comment by xarthurx** [comment]
> I see what you are saying. It would be nice to have the dot indicator shown somehow as well. I'll look into this feature request. I don't want to add a new column and shift the columns though. I think I can use a distinct symbol for when it is selected and highlighted and when it unselected and highlighted. I'll give it some thought and experiment with a few symbols and post here when I make progress on that.

I think there is no need for an additional column.
What I would suggest is:
1. when the current line is selected, using the `check` symbol.
2. when the current line is not selected, using the `dot` symbol.
3. All the rest lines will have no symbol.

Thus, it should be simply a change of the marking symbols when switching between "selected" and "not selected".

Hope it helps.

**Comment by xarthurx** [comment]
Ah, the above comment will also introduce confusion when multiple items are selected and we don't know where the cursor is...

Yes, then a different symbol of "selected AND current line" would be good, or a reverse of the foreground/background color, probably.

**Comment by kdheepak** [comment]
This should be resolved in https://github.com/kdheepak/taskwarrior-tui/releases/tag/v0.13.16
