### ISSUE TITLE
Cannot taskwarrior-tui cannot add first task

### ISSUE THREAD

**Issue by chrxn** [kdheepak/taskwarrior-tui#2]
`taskwarrior-tui` cannot add the first task if the task list is empty.

Demonstrated here:
[![asciicast](https://asciinema.org/a/n5R2kGVEW0jS4HByYLm7f2dfh.svg)](https://asciinema.org/a/n5R2kGVEW0jS4HByYLm7f2dfh)

**Comment by kdheepak** [comment]
Thanks for the detailed demonstration! Clearly I've never actually completed all my pending tasks :)

This should be fixed in https://github.com/kdheepak/taskwarrior-tui/releases/tag/v0.5.3.

**Comment by kdheepak** [comment]
I'm closing this issue. Let me know if you still have issues or if anything else comes up!
