### ISSUE TITLE
Columns keep changing

### ISSUE THREAD

**Issue by typebrook** [kdheepak/taskwarrior-tui#20]
@kdheepak 
![output2](https://user-images.githubusercontent.com/19887090/95667918-28f85100-0b9f-11eb-8189-98fa35a92fde.gif)

It happens after 6d4ba2d (use `git bisect`)

Machine I build on:
- Manjaro Linux (5.4.62)

**Comment by kdheepak** [comment]
Oof. That is annoying. I'm currently working on rewriting the column width calculator, so that'll resolve this issue. Until then, you can remove `tags` from `~/.taskrc` in the `report.next.columns=...` and `report.next.labels` attributes.

**Comment by kdheepak** [comment]
Can you try https://github.com/kdheepak/taskwarrior-tui/releases/tag/v0.7.0? I think it should resolve this issue.

**Comment by typebrook** [comment]
@kdheepak 
Yap! It is fixed now. Thanks! You are so productive man! :rocket:
