### ISSUE TITLE
Cannot shlex split ${input string} when the text contains " ' ".

### ISSUE THREAD

**Issue by xarthurx** [kdheepak/taskwarrior-tui#208]
**Describe the bug**

When adding annotations, if the text contains the symbol `'` (for instance, the "belonging mark" after the word "one" in "one's name"), an error will be produced as

```
Cannot shlex split ${input string}.
```

Guess this is due to the handling of string element when it contains special symbols?
https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html

**Comment by kdheepak** [comment]
You can use `one\'s`. I initially was trying to auto escape the single quotes but that became more messy and bug prone. For example, someone might type `hello 'John'` as the task and that works fine. Basically currently whatever works in the command line works in the TUI. If you have a single quote you’ll need to escape it in the command line prompt too. Like, if some one tries to run the equivalent of`task add 'John\'s mother said she wants 'perfect' scores' due:'2021-02-01'`, they’ll have to escape some single quotes but not others. 

Hope that makes sense?

I’m open to suggestions on how to fix this. This is definitely an annoyance but there’s too many corner cases to handle correctly.

**Comment by xarthurx** [comment]
OK, escaping make sense. And I agree many corner cases exist if you want to include all of them...

**Comment by kdheepak** [comment]
Closing as `wontfix` but I'm open to suggestions / a PR to handle this currently.
