### ISSUE TITLE
auto-completion for "depends" in the modify mode

### ISSUE THREAD

**Issue by xarthurx** [kdheepak/taskwarrior-tui#213]
**Description**

Pressing `m` for editing the current task has provided great ease for editing tasks.
However, the auto-completion system at the moment doesn't provide `tab` completion for the keyword `depends` (say, type `d` and press `tab`)

Similarly, `wait` also seems missing.

It would be great if these can be added.

**Comment by kdheepak** [comment]
Thanks for the suggestion! This is available in this release: https://github.com/kdheepak/taskwarrior-tui/releases/tag/v0.13.19

**Comment by Petemir** [comment]
@kdheepak One minor comment. Is there a reason why when you modify one task with one of the aforementioned fields (e.g., `wait`, `depends`), it doesn't appear on the modify input field?

**Comment by xarthurx** [comment]
@Petemir  I actually like the current way better. It help to only modify the things you want and keep the rest untouched.

Say, you have `task description. priority:H +TAG` and I want to modify the `priority`, if all things are shown, then I have to move my cursor to the `priority` position and change it. Using the current methods, I only need to type (also with the help of auto-completion) new priority setting.

**Comment by Petemir** [comment]
Cool, when I read `Similarly, wait also seems missing.` I was dubious if you meant that it was missing from the edit field (which was a particular concern of mine, but I understand the use case, the text to modify can get long really quickly :) ).

**Comment by kdheepak** [comment]
Also, pre-populating the modify pane with all the information is available as a configuration option, though it might be undocumented :) I go back and forth on it’s usefulness. With emacs style navigation it can be easy to move the cursor around quickly. But it’s also a lot of noise. And with auto complete all the information is readily available anyway. 

I’m open to suggestions or ideas here.

**Comment by Petemir** [comment]
@kdheepak hi! Coming back to this topic (sorry, didn't feel like opening a new issue, because I don't know if it's an issue or it is expected behaviour), is there a way to remove dependencies? Because if I put "depends:" in order to blank a task's dependencies on the "modify" field, the same dependencies remain. I only seem able to remove them by entering the "edit" mode.
