### ISSUE TITLE
default filter has unwanted limit:page

### ISSUE THREAD

**Issue by rockydd** [kdheepak/taskwarrior-tui#214]
**Describe the bug**
Suddenly, the tui set the default filter to 'status:pending limit:page', so that I have to remove `limit:page` every time. 

![image](https://user-images.githubusercontent.com/64197/117043698-6d297b00-acc2-11eb-81db-da318a19ca13.png)

Seems that this happens after I upgrade taskwarrior to 2.5.3.

**To Reproduce**

- [ ] Reproducible using the test data located here: <https://github.com/kdheepak/taskwarrior-testdata/>

**Environment (please complete the following information):**

- Operating System:  Mac
- Installation: homebrew 
- taskwarrior-tui version: 0.13.18

```bash
taskwarrior-tui --version
```
- task version: 2.5.3

```bash
task --version
```

**Additional context and information**

**Comment by kdheepak** [comment]
Can you run `task show report.next.filter` and share the output? The tui should be using that value.

**Comment by gbstan** [comment]
I have the same issue. Here is the output of ``task show report.next.filter``:

Config Variable    Value
report.next.filter status:pending limit:page

**Comment by kdheepak** [comment]
Can you add the following to your `.taskrc` and try again?

```
report.next.filter status:pending 
```

**Comment by gbstan** [comment]
Yes, it works by adding this to ``.taskrc``: report.next.filter=status:pending

**Comment by kdheepak** [comment]
I think with the newest version of `taskwarrior` this change is required. I will add a way to use a separate filter for `taskwarrior` and `taskwarrior-tui`, because I can imagine someone might want to use `task` in the command line occasionally and would like `limit:page` in those instances.

**Comment by kdheepak** [comment]
I made a PR. You can now add `uda.taskwarrior-tui.task-report.next.filter=status:pending` and `taskwarrior-tui` will use that, leaving `report.next.filter` for the `task` command line tool. If `uda.taskwarrior-tui.task-report.next.filter` is not defined, the configuration will use `report.next.filter` though.

**Comment by kdheepak** [comment]
You can try out the new configuration in this release.

**Comment by rockydd** [comment]
> You can try out the new configuration in this release: https://github.com/kdheepak/taskwarrior-tui/releases/tag/v0.13.19

It works great! Thanks!
