### ISSUE TITLE
Cursor jumping less distance than expected

### ISSUE THREAD

**Issue by vursc** [kdheepak/taskwarrior-tui#217]
**On entering characters that occupy multiple character widths in line-inputs, like when entering a task title, the cursor has some spacing issues**

**To Reproduce**

- Start taskwarrior-tui
- Press `a` to enter add mode
- Enter a title containing characters that occupy multiple character widths such as 写作业 (Chinese for "do homework") etc
- With each entered character, the cursor jumps only one space further ahead, while each character occupies two spaces' width
- When deleting the characters via backspace, the behavior is hard to determine (because of poor display effects)

**Environment (please complete the following information):**

- Operating System: Windows 10, 20H2 (19042.928)
- Terminal: both PowerShell and double-clicking the executable
  - I tried to determine Powershell version, and `powershell.exe -Version 3`, `powershell.exe -Version 4`, `powershell.exe -Version 5`, `powershell.exe -Version 5.0`, `powershell.exe -Version 5.1` are successful, while version 1, 2 crashes on startup, and version 5.3 or higher and 6 not found
- System locale: Displayed as "中文(简体, 中国)", probably zh-CN, without UTF-8 enabled
- Installation: github releases, and `cargo build` (both `dev` and `release`)
- taskwarrior-tui version: `0.13.19` / latest `master`
- task version: `2.5.3` / latest `msys2`

**Additional context and information**

![taskwarrior-tui-issue](https://user-images.githubusercontent.com/80833781/117246317-01384580-ae6f-11eb-865e-f9d32788ec5a.gif)

Refer to #49. This may be because the number of graphenes is used to determine the cursor position.

Maybe calculate width of each character? use something like <https://crates.io/crates/unicode-width> should be a good option.

**Comment by kdheepak** [comment]
Thanks for reporting! This is an annoying bug. 

> NOTE: The computed width values may not match the actual rendered column width. For example, the woman scientist emoji comprises of a woman emoji, a zero-width joiner and a microscope emoji.

I believe even the `unicode-width` crate is not sufficient for this. I'll look into how best to solve this problem.

**Comment by kdheepak** [comment]
Can you build a binary from the referenced PR and try it? I think it still doesn't do exactly the right thing because it doesn't know the width of the graphemes in whatever font is being used but I think at least it behaves more reasonably.

**Comment by kdheepak** [comment]
This should be fixed in this release: https://github.com/kdheepak/taskwarrior-tui/releases/tag/v0.13.20
