### ISSUE TITLE
auto-completion with keywords that exist in the completed tasks

### ISSUE THREAD

**Issue by xarthurx** [kdheepak/taskwarrior-tui#218]
**Description**

Currently, the auto-completion popup list only shows options that exist in the unfinished tasks.
I think the circumstance that I finish all tasks in one project/with one tag, and then I need to add another task of the same project some time later.

The selection of the possible options should include the ones from completed tasks. So is the tags)

(Or even better, user can set a time range, so that the options only show possible options of tasks finished within the time range. This can reduce the number of auto-completion options once the # of projects gets bigger)

**Comment by kdheepak** [comment]
Good idea! Currently, it shows completion only from the task list imported (which is based on the filter). If you want to have it show completion right now from any task, you'll have to change the filter. And this is obviously not desired.

**Comment by xarthurx** [comment]
Is there any update on this?
Or an alternative method for dealing with this issue is to allow the user to add a list of "frequently used project/tags".

A case that I'm often encountering:
I get tasks of one project done once they are added (high priority), and new tasks are coming/added frequently. But whenever the task list doesn't contain tasks of this project, I get no auto-completion of it and have to type it by hand.

It would be great if this issue can be nicely managed if possible.

**Comment by kdheepak** [comment]
Sorry, work has just been busy and I haven’t had the time to implement this. I’ll try to work on this over the weekend.

**Comment by xarthurx** [comment]
I would still vote for this feature if possible... The issue I described is the most painful thing at the moment for `taskwarrior-tui`.

**Comment by kdheepak** [comment]
I've implemented this behind a configuration option:

```
uda.taskwarrior-tui.task-report.use-all-tasks-for-completion=true
```

By default this is set to `false`, since this makes an extra call to `task export all` every update tick, and I'm not sure if that benefit is worth it yet.

**Comment by kdheepak** [comment]
You can try this feature in https://github.com/kdheepak/taskwarrior-tui/releases/tag/v0.19.4

**Comment by xarthurx** [comment]
Thanks for the quick response.
However, I encounter this after activating the option in `.taskrc`:
![image](https://user-images.githubusercontent.com/1921878/154356537-bf093d3a-fcba-40ae-8c5e-7bfa754a7f18.png)

I think in my use case, it is best to set a time range to get the auto-completion. For instance, auto-fill the project/tags I have written within 3 months. Otherwise, it might be from a new project.

Not sure if this is easy to do, though. 

Isn't taskwarrior have a project or tag pool somewhere? Like when I write post in a forum, filling tags will auto-complete related tags...

**Comment by kdheepak** [comment]
Are you using taskserver or intheam? This seems to be related to #393.

**Comment by bradyt** [comment]
> Isn't taskwarrior have a project or tag pool somewhere? Like when I write post in a forum, filling tags will auto-complete related tags...

This sounded familiar, so first I tried grepping `task show`, then searching `man taskrc`. Naively searched for "tags", then that led to searching for "`\.all\.`". This part might be relevant, but I'm very much not sure if it will be useful here:

```
list.all.projects=0
       May be "1" or "0", and determines whether the 'projects' command lists
       all the project names you have used, or just the ones used in active
       tasks. The default value is "0".
summary.all.projects=0
       If set to "1", shows all projects in the summary report, even if there
       are no pending tasks. The default value is "0".
complete.all.tags=1
       May be "1" or "0", and determines whether the tab completion scripts
       consider all the tag names you have used, or just the ones used in active
       tasks. The default value is "0".
list.all.tags=1
       May be "1" or "0", and determines whether the 'tags' command lists all
       the tag names you have used, or just the ones used in active tasks. The
       default value is "0".
```

The discrepancy in the last two, between "default" and what is set, might be an unrelated issue at Taskwarrior project.

**Comment by kdheepak** [comment]
@xarthurx can you share the output of `task export all`.

**Comment by kdheepak** [comment]
```
{"id":0,"description":"nd":"20190518T081754Z","entry":"20190517T231210Z","modified":"20190518T081754Z","status":"deleted","uuid":"4a9d9a18-7e1c-4d4b-9f7d-fd65eeb4b124","urgency":2},
```

This line doesn't appear to be valid JSON? That could be one cause of the problem.

**Comment by kdheepak** [comment]
I also deleted your comment just to be safe because I wasn't sure if you anonymized it or not :)

**Comment by xarthurx** [comment]
@kdheepak  Thank you for deleting that and for the quick response.
Yes, that's the problem, though I don't know exactly why that happened. Everything is working now, thanks!!!!

**Comment by xarthurx** [comment]
@kdheepak  BTW, do you have any "buy me a coffee" donating port?
I really appreciate your help and would like to make some contribution to the project.

**Comment by kdheepak** [comment]
Thanks! I appreciate the offer. If you'd like to donate, I'd recommend you donate to https://github.com/sponsors/GothenburgBitFactory or a charity of your choice :)

**Comment by kdheepak** [comment]
I can make the completion candidates case insensitive, but currently the actual completion just fills in the rest of the characters at the moment.

For example, if you typed `PRoJ<TAB>`, it'll show you `project:` as a candidate:

<img width="380" alt="Screen Shot 2022-02-17 at 10 31 18 AM" src="https://user-images.githubusercontent.com/1813121/154537867-e733f677-2b88-42f1-9561-b428e7c56bd0.png">

But if you hit enter, it'll just complete `ect:`, leaving `PRoJ` unchanged:

<img width="320" alt="Screen Shot 2022-02-17 at 10 31 42 AM" src="https://user-images.githubusercontent.com/1813121/154537880-c2deb981-d8cf-472a-818e-7695323ccbb0.png">

This is obviously not what users would expect. 

To make this work properly, I'll have to erase the matching characters and re-enter them from the candidate selection, and that's a pain to do at the moment. I experimented with this a while ago and left it as something I'd get to later. If you'd like to, you can open a new issue to track this feature request.

**Comment by yongli-abc** [comment]
Just FYI, the documentation is missing this option `use-all-tasks-for-completion`. I encountered the same need and had to dig through the code to find this option.

**Comment by yongli-abc** [comment]
Another request is that make the option more flexible so user can specify a default filter (not necessarily the same default report filter) to load project completion candidates.

More specifically, I would love to only use projects from "pending tasks" rather than "all tasks", because some old projects are no longer relevant. But if we support a default project completion filter, that could also be used to do "load the projects in the past X time period".

**Comment by kdheepak** [comment]
> Another request is that make the option more flexible so user can specify a default filter (not necessarily the same default report filter) to load project completion candidates.

That's a good idea! Can you open a new issue to track that feature request?

**Comment by yongli-abc** [comment]
> > Another request is that make the option more flexible so user can specify a default filter (not necessarily the same default report filter) to load project completion candidates.
> 
> That's a good idea! Can you open a new issue to track that feature request?

Sure, I created #613 and #612 .
