### ISSUE TITLE
`--report` is misbehaving

### ISSUE THREAD

**Issue by k4y4k** [kdheepak/taskwarrior-tui#221]
# Description

Hey again 😄

It's me, kayak "Ridiculous-Amount-Of-Pending-Tasks" kayak. Issue title is self-explanatory. Running `taskwarrior-tui`, hitting `/` and typing in something like `+READY project.not:Reading\ list project.not:fanfiction project.not:work.social\ media -optional` gets really old after a while. 

# Solution

## What I have:

A series of shell aliases that call `task +READY [exclude some projects]` or `task +READY /search` or something.

## What I'm looking for:

A way to slot in or otherwise integrate `tui` into that.

Why? `tui` updates as soon as `bugwarrior` opens / closes issues, whereas regular task prints and exits (as intended - but it's annoying to call task start `799` and realise that in the 2s between when I got the ID and called `start`, an earlier task had been closed, so the task I want is now 798. and I started ~~800~~ 799).

To be clear, I'd like to populate the original run, not make the field immutable.

Cheers!
  kayak

**Comment by k4y4k** [comment]
I'm open to (learning Rust and) opening a PR, but thought I'd open something up first in case there's an unclear way of doing such a thing (or I missed it).

**Comment by kdheepak** [comment]
Of course I remember you @k4y4k, you have the most memorable issues lol. 

Right now, you _can_ use different reports for different filters:

```
report.reading-list.filter=+READY project.not:Reading\ list project.not:fanfiction project.not:work.social\ media -optional
report.next.filter=status:pending
```

And then run `taskwarrior-tui --report reading-list` or `taskwarrior-tui` to use the filter for the `reading-list` report or the default `next` report.

This obviously changes the output of `task reading-list` too. If you want, you can use the following:

```
uda.taskwarrior-tui.task-report.reading-list.filter=+READY project.not:Reading\ list project.not:fanfiction project.not:work.social\ media -optional
uda.taskwarrior-tui.task-report.next.filter=status:pending
```

This will not affect the output of `task reading-list` but will change the filter in `taskwarrior-tui`. This also allows you to use different labels / columns for different reports. 

Thoughts? Does this help resolve your issue? I could add in a `--filter` flag too but it seems a little repetitive. If this does not resolve your issue, I'd be willing to do that.

**Comment by k4y4k** [comment]
# OHO!
## REPORTS!!!

Absolutely what I was looking for and what I meant when I mentioned
> A series of shell aliases that call ...

Consider me satisfied then :relieved: :ok_hand: 

---

PS
> Of course I remember you @k4y4k

aw :heart:

**Comment by k4y4k** [comment]
wait, I'm re-back.

(after compilation of `main`)

```
kayak@mint-tim-tam ~/g/t/t/release (main) [101]> ./taskwarrior-tui --report what

Backtrace omitted. Run with RUST_BACKTRACE=1 to display it.
Run with RUST_BACKTRACE=full to include source snippets.

The application panicked (crashed).
  index out of bounds: the len is 0 but the index is 0
in src/app.rs, line 857
thread: main
```

`task reports`

```
Report           Description
_reviewed        Tasksh review report.  Adjust the filter to your needs.
active           Active tasks
all              All tasks
blocked          Blocked tasks
blocking         Blocking tasks
burndown.daily   Shows a graphical burndown chart, by day
burndown.monthly Shows a graphical burndown chart, by month
burndown.weekly  Shows a graphical burndown chart, by week
completed        Completed tasks
ghistory.annual  Shows a graphical report of task history, by year
ghistory.monthly Shows a graphical report of task history, by month
history.annual   Shows a report of task history, by year
history.monthly  Shows a report of task history, by month
information      Shows all data and metadata
list             Most details of tasks
long             All details of tasks
ls               Few details of tasks
minimal          Minimal details of tasks
newest           Newest tasks
next             Most urgent tasks
oldest           Oldest tasks
overdue          Overdue tasks
projects         Shows all project names used
ready            Most urgent actionable tasks
recurring        Recurring Tasks
seq              What now?
summary          Shows a report of task status by project
tags             Shows a list of all tags used
unblocked        Unblocked tasks
waiting          Waiting (hidden) tasks
what             What now?

31 reports
```

`what` is defined [here](https://github.com/k4y4k/k4y4k/blob/3bae559dd92fe9ec09c93d404031453cf84136de/home/.taskrc#L63). It works in `task`:

<details>
<summary>output of `task what` (truncated, you get the idea)</summary>

```
kayak@mint-tim-tam ~> task what

ID  Project           Description                                  Urgency
  8 freak-ode-camp    #116: Roman Numeral Converter                     16
  4 freak-ode-camp    #356: Build a Survey Form                       14.9
 25 unforgettable-web #57: Purple                                     14.7
537 cs50x             Lecture: Scratch                                13.1
538 cs50x             Problem Set 0                                   13.1
539 cs50x             Lecture: C                                      13.1

```

</details>

Also crashes on another custom report, [`seq`](https://github.com/k4y4k/k4y4k/blob/e3b636407dece7ef42280cff8645724f515806d0/home/.taskrc#L76).

<details><summary>`task seq`</summary>

```
kayak@mint-tim-tam ~> task seq

ID  Project        Description                                     Urgency
1   freak-ode-camp #359: Build a Personal Portfolio Webpage        1.91
2   freak-ode-camp #358: Build a Technical Documentation Page      9.91
3   freak-ode-camp #357: Build a Product Landing Page              9.91
4   freak-ode-camp #356: Build a Survey Form                       14.9
5   freak-ode-camp #119: Cash Register                             3.04
6   freak-ode-camp #118: Telephone Number Validator                11
```
</details>

However, `tui` doesn't mind the built-in reports (`minimal`, `list`). Is there something you're checking for / assuming that mad `task` scientists wouldn't do?

**Comment by kdheepak** [comment]
Fixed in https://github.com/kdheepak/taskwarrior-tui/releases/tag/v0.13.21. Looking forward to what else you find, you mad `task` scientist 😁.

**Comment by k4y4k** [comment]
:joy: I'll be back with my `task` powered DNA sequencer in a week or so :eyes:
