### ISSUE TITLE
auto-completion for priority should allow all options (L, M, H)

### ISSUE THREAD

**Issue by xarthurx** [kdheepak/taskwarrior-tui#226]
**Description**

auto-completion for `priority` should allow all options (L, M, H).
Currently, it has the same issue described in https://github.com/kdheepak/taskwarrior-tui/issues/218 --- Only options exist in the current task list will appear when pressing `TAB`.

**Comment by kdheepak** [comment]
Thanks for opening the issue! This should be fixed when the referenced PR is merged. I'll make a new release once I do that.

**Comment by kdheepak** [comment]
You can check out the feature in this release: https://github.com/kdheepak/taskwarrior-tui/releases/tag/v0.13.24

**Comment by astr0gator** [comment]
Great. Can I set a priority as a string? E.g. in TW I can `task add Task0 priority:L`, however it doesn't work for me in TUI. Thx

**Comment by RedEtherbloom** [comment]
> Great. Can I set a priority as a string? E.g. in TW I can `task add Task0 priority:L`, however it doesn't work for me in TUI. Thx

Weird, you should be able to set it both via modify or on task add(e.g. via prio:L or priority:L).
In what way does it not work, does it ignore the prio or simply add it onto the end of the string? If the latter, did you enter priority:L in or behind the quotation marks? (e.g."Task0 priority:L" vs  "Task0" priority:L)

**Comment by astr0gator** [comment]
The latter, but it makes perfect sense for me now, thank you. A quotes-ignoring habit from taskwarrior CLI 😄
