### ISSUE TITLE
[Discussion] modify tags in the modify mode.

### ISSUE THREAD

**Issue by xarthurx** [kdheepak/taskwarrior-tui#228]
**Description**

With the most recent version, when pressing `m` to modify the task, it seems I can only add a `TAG`, instead of modifying it (say, delete some of the tags, and add new one)

I guess it is similar for entries like "project", etc.

I'm not sure if showing everything of the current task and ask the user to move the cursor and edit it is the best approach.
Alternatively, an "overwritten" approach could also be employed.

For me, providing all the info would be better, since there might be multiple tags exist and I don't want to overwrite all of them with the new tag.

**Comment by kdheepak** [comment]
Can you try adding `uda.taskwarrior-tui.task-report.pre-fill-task-meta-data=true` to your `.taskrc` to see if that helps?

**Comment by kdheepak** [comment]
See this issue for reference: https://github.com/kdheepak/taskwarrior-tui/issues/164

**Comment by xarthurx** [comment]
Great, that works.

> Can you try adding `uda.taskwarrior-tui.task-report.pre-fill-task-meta-data=true` to your `.taskrc` to see if that helps?
