### ISSUE TITLE
Inputting # (hashtag) doens't produce the expected result

### ISSUE THREAD

**Issue by Petemir** [kdheepak/taskwarrior-tui#231]
Hello once again :) .

There are some issues I find when trying to use "#" on the different input fields; I know it is a special character and there have been already some issues talking about single quotes, but perhaps this one could be solved.

Basically, if I add a task with a "#", everything after it gets omitted (obviously, as "#" works as a comment in the terminal). Furthermore, when I modify a task with a "#" (if I entered it as "\#", or with quotes), it appears as # (i.e., without quotes), so everything after it gets omitted.

Although I believe that at input time (adding a task) the burden of escaping the # could be on the user, I believe that when modifying a task this should/could be handled from taskwarruir-tui.

Let me know if there's something more needed. Thanks!

**To Reproduce**

* Add a task (press `a`) with a hashtag (#) somewhere in the middle.

**Environment (please complete the following information):**

- Operating System: Linux Ubuntu 21.04
- Installation: github releases
- taskwarrior-tui version: 0.13.24
- task version: 2.5.3

**Comment by kdheepak** [comment]
Thanks for opening the issue. This is certainly very annoying. What do you think about adding double quotes to the modify string when presented to the user? 

<img width="1037" alt="Screen Shot 2021-05-27 at 11 06 49 AM" src="https://user-images.githubusercontent.com/1813121/119867922-a4630480-bedb-11eb-9812-c286948ed71d.png">

**Comment by Petemir** [comment]
That way it should work, yes. From my tests either surrounding the whole string or just the special character "#" worked. Just to double-check, when adding a task from 0 the burden would be on the user to add the escape sequence?

**Comment by kdheepak** [comment]
When you say "task from 0", you mean `task add "..."` or using the number shortcut? Also, were you able to try the referenced PR?

**Comment by kdheepak** [comment]
I merged the PR. I think it works well. When trying to add a task like `John said "hello"` i.e. `task add "John said \"hello\""`, I think it is on the user to escape the double quotes appropriately.

**Comment by kdheepak** [comment]
I'm open to suggestions though!

**Comment by Petemir** [comment]
By "task from 0" I meant doing it with the 'a' shortcut and then adding it (opposed to modifying a task, which was the only case covered in your commit/PR).

e.g., 
<img width="435" alt="image" src="https://user-images.githubusercontent.com/287105/120328428-16c45200-c2eb-11eb-9b29-b82f452f402c.png">
Would only cover "this task".  I thought that perhaps # (no quotes for simplicity) could be replaced by "#" in the string, but perhaps it generated unexpected issues like in #208 .

I didn't get to test the PR but will do soon. I'll let you know about variations/possible improvements, thanks!

**Comment by kdheepak** [comment]
I _could_ prefill the add prompt with double quotes. I need to look into all the corner cases and figure out if I’d be able to handle all of it.

**Comment by kdheepak** [comment]
I've made a new release with this fix: https://github.com/kdheepak/taskwarrior-tui/releases/tag/v0.13.25
