### ISSUE TITLE
Disable Info View on startup

### ISSUE THREAD

**Issue by piotryordanov** [kdheepak/taskwarrior-tui#238]
Is it possible to disable the info view window on startup instead of having to press 'z' after starting the tui?

**Comment by kdheepak** [comment]
Yeah I believe there’s already a flag for it. I’m on my mobile now but I can look for it later and share here if you don’t find it by then.

**Comment by kdheepak** [comment]
`uda_task_report_show_info=false`

**Comment by piotryordanov** [comment]
Thx for the swift response!!

Is that something that I set inside of `.taskrc`? (I tried and it didn't do anything)

Also, where can I find where other flags are? Is this a `task` specific config, or a `taskwarrior-tui` config?

**Comment by kdheepak** [comment]
Oops, sorry I posted prematurely. Add this to your `.taskrc`

```
uda.taskwarrior-tui.task-report.show-info=false
```

you can find other configuration options here: https://kdheepak.com/taskwarrior-tui/configuration/advanced/

**Comment by piotryordanov** [comment]
Oh, I apologize. The show-info key was indeed on that page and I had glanced fast above it.

That does it.
Thx!

**Comment by kdheepak** [comment]
I should explain the options more clearly too :) I’lol add that as a todo for myself.

**Comment by piotryordanov** [comment]
No worries mate. Thx a lot for the hard work!
