### ISSUE TITLE
Custom file not being red

### ISSUE THREAD

**Issue by piotryordanov** [kdheepak/taskwarrior-tui#239]
Hello again

I am trying to run `taskwarrior-tui -c $HOME/.config/.taskrc` to setup a custom config, but it is failing.
As you can see in the screenshot, the .taskrc file exists, but wont be read!

![image](https://user-images.githubusercontent.com/48773775/122693661-6390ae00-d243-11eb-8e8b-47288af468c8.png)

**Comment by kdheepak** [comment]
I added that config for future uses, so that `taskwarrior-tui` could have its own config. But I haven’t gotten around to implementing that yet. You can use the taskwarrior environment variables to use a custom `.taskrc` though.

**Comment by kdheepak** [comment]
I'll close this issue, since I don't think it is a bug. Feel free to reopen if you have any additional questions.
