### ISSUE TITLE
Overdue date always shown in seconds, regardless of how large it is.

### ISSUE THREAD

**Issue by mk23w-vmware** [kdheepak/taskwarrior-tui#24]
**Describe the bug**

After a task is overdue, the Due column always shown it in seconds.

A nicer format (month:weeks:days:hours:seconds) would be more user friendly.

┌Task|Calendar────────────────────
│ID    Age   Project   Due     Description                             Urg
│• 1   13h   security  -14066s XXXX   9.87                             
│  2   16min            -77376s XXXX   9.21                              
│  3   6min                    istio                                   0.00         

Due dates are -14066s and -77376s.

I'd prefer to see -3h54m.

**To Reproduce**

- create task
- set due
- wait for due date to pass. Do not mark as done.

**Comment by kdheepak** [comment]
That bugged me too! Showing the time in a more sensible format is a great idea.

**Comment by kdheepak** [comment]
Fixed! 

<img width="780" alt="Screen Shot 2020-10-24 at 12 05 23 AM" src="https://user-images.githubusercontent.com/1813121/97069305-a010ea80-158c-11eb-87f5-77947f9f55fc.png">

And I made a new release with this change: https://github.com/kdheepak/taskwarrior-tui/releases/tag/v0.8.5.

**Comment by mk23w-vmware** [comment]
New image works great. Thanks so much!
