### ISSUE TITLE
Use shortcuts to switch predefined filter strings

### ISSUE THREAD

**Issue by vizcay** [kdheepak/taskwarrior-tui#241]
I usually have around a handful of filters that I would love being able to swith around fast.

**Comment by kdheepak** [comment]
Can you not use just multiple `context`s for managing predefined filter strings? Implementing switchable filter strings I think is a little more messy than I anticipated.

**Comment by vizcay** [comment]
@kdheepak I've finally done what was requested here with the help of tmux and tmuxinator. Basically I have multiple reports opened all the time that autoupdate every 5 secs and taskwarrior-tui in the first window to manage everything.

Will close this then.
