### ISSUE TITLE
Control the amount of tasks to show

### ISSUE THREAD

**Issue by mantzas** [kdheepak/taskwarrior-tui#242]
**Description**

Is there a way to increase the amount of task shown in the top `panel`?
If the list is too big some of the tasks are hidden.
Amazing work BTW.

**Solution**

Ideally we should be able to configure the amount of issues shows or be able to scroll through all of them.

**Additional context**

**Comment by kdheepak** [comment]
What do you mean be able to scroll through them? Using `j` or `k` let’s you scroll through all the issues, right?

**Comment by mantzas** [comment]
Correct, but the list shown does not contain all existing tasks in order to scroll.

**Comment by kdheepak** [comment]
Can you give an example of an issue that isn’t in the list that’d you’d like it to be? The filter controls which issues are in the list. If you change the filter the list will change accordingly. 

Or maybe I’m still not understanding the request? Please feel free to elaborate, I’m slow :)

**Comment by mantzas** [comment]
I am even slower no worries. ;)
When I open the app it show at the top pane a list of issues.
Right now it is showing 23 items. But there are actually more but they are `hidden`.
When I mark  an item as done `d` the list show is still 23 because one of the `hidden` tasks will be shown.
Does that help?

**Comment by kdheepak** [comment]
Can you share your filter string with me? If you can provide a screenshot using the test data that’ll be ideal. I’m not following why when you hit `d` the list doesn’t change? It should decrease in size, right?

**Comment by mantzas** [comment]
![image](https://user-images.githubusercontent.com/605434/124260182-0d234980-db38-11eb-9145-0f339eb1a6a1.png)

If i hit the d the item will be marked as done and the list will stay the same but with another item that pops from the list that was initially not shown.

Let me explain it in another way. Assume that i am adding 50 items on an empty taskwariror-tui application.
Only 23 are show, but the rest of the 27 are hidden.
If i delete/done one of the 23 visible ones then 23 will be still visible and 26 hidden (overall 49).
Does that help?

**Comment by kdheepak** [comment]
Can you try removing `limit:page` from the filter?

**Comment by mantzas** [comment]
Behaves exactly the same.

**Comment by kdheepak** [comment]
Can you share a reproducible example using this repository? https://github.com/kdheepak/taskwarrior-testdata

**Comment by mantzas** [comment]
@kdheepak hey, i created a PR int he mentioned testdata repo (did actually anonymize it). https://github.com/kdheepak/taskwarrior-testdata/pull/2

How to reproduce the issue:
- If I open the app the ui shows 24 items in my setup.
- Added 3-4 items which doe not show up
- When I complete/delete one one of the new shows up

**Comment by kdheepak** [comment]
Thanks for providing test data. I used the test data with an empty `.taskrc` and I do get only 24 items in the UI. However, when I change the filter to remove `limit:page`, then all items appear.

https://user-images.githubusercontent.com/1813121/126185720-c5d15796-9590-4b09-a080-07b059e6f719.mov

If you add the following to your `.taskrc` you can change the default `taskwarrior-tui` filter:

```
report.next.filter=status:pending
```

**Comment by kdheepak** [comment]
To clarify, I'm still not able to reproduce your issue. You might have to add your `.taskrc` to the PR in the test data repository as well.

**Comment by mantzas** [comment]
@kdheepak Finally it was my mistake. You asked me at some point to remove `limit:page` which i though i did. Finally i counted the items with and without limit and everything is ok. I am very sorry for the mess I made. Thank you very much for your time and effort.

**Comment by kdheepak** [comment]
Happens to the best of us my friend! No worries!
