### ISSUE TITLE
run taskopen from shortcut

### ISSUE THREAD

**Issue by kiil** [kdheepak/taskwarrior-tui#244]
I  am using  [taskopen](https://github.com/jschlatow/taskopen) to edit Notes with neovim.

The notes are attached to taskwarrior tasks as annotations.

But I cannot do this from taskwarrior-tui it seems.

Whether I run

`! task execute taskopen [taskid]` from taskwarrior-tui

or use

`task execute taskopen $1` in a shortcut

nothing happens. Neovim does not open at all.

If I use the edit command in taskwarrior-tui, neovim will in fact open for editing of the task itself, but  I cannot seem to get taskopen to open an attached note.

Any way to do it?

**Comment by kdheepak** [comment]
Thanks for opening an issue. 

How do I use `taskopen`? I'm using the `staging` branch: https://github.com/jschlatow/taskopen/tree/staging

```
$ taskopen 1
No actions applicable.
Attaching to task 1 'Move between tasks using 'j' and 'k''.
Type a file extension (or none): md
Annotating task 1 'Move between tasks using 'j' and 'k''.
Annotated 1 task.


$ task 1
Name          Value
ID            1
Description   Move between tasks using 'j' and 'k'
                2021-07-16 11:48:40 Notes.md
Status        Pending
Entered       2020-10-21 00:52:09 (8mo)
Last modified 2021-07-16 11:48:40 (4s)
Virtual tags  ANNOTATED PENDING PRIORITY READY UDA UNBLOCKED
UUID          0b11967d-9dae-4333-a137-c3b1e8a641d3
Urgency          6
Est           30
Priority      H

    UDA priority.H      1 *    6 =      6
                                   ------
                                        6

Date                Modification
2021-07-16 11:48:40 Annotation of 'Notes.md' added.
```

This doesn't open `nvim`  from the command line, even without using `taskwarrior-tui`. Do you have something specific in your `~/.taskrc` file?

**Comment by kdheepak** [comment]
`taskopen 1` only works for me when I use `task 1 annotate -- /full/path/to/file.md`. This runs `open $FILE`. I set up a shortcut in `taskwarrior-tui` to run `taskopen $1`. This seems to be working for me to open the file.


https://user-images.githubusercontent.com/1813121/125990071-78365f39-38f5-4a3e-b75a-b01364ec9b4c.mov

But this doesn't work if I replace `taskopen $1` with `nvim notes.md`. I think I do have to make a few other changes for this to work. Let me look into it.

**Comment by kiil** [comment]
If I set taskopen to use macvim (mvim) as editor it does indeed work, because then it opens in another window — just like in your example video.

But for nvim to open in the same terminal window and  temporarily "overtake" taskwarrior-tui  does not seem to work. Even though `task edit $1` works fine this way :)

**Comment by kiil** [comment]
I can  open  from the command line with nvim like this

`taskopen [taskid]`

without problems.

In  taskrc I have

`~/.taskrc`

in ~/.taskopenrc I have

`EDITOR='nvim'`

**Comment by kdheepak** [comment]
Thanks for the additional information. I'm not sure exactly what is going on here but even a simple rust program like this isn't working

```rust
fn main() {
    let mut c = std::process::Command::new("vim");
    dbg!(c.output());
}
```

This is output of my test:

```
[src/main.rs:58] c.output() = Ok(
    Output {
        status: ExitStatus(
            ExitStatus(
                256,
            ),
        ),
        stdout: "...",
        stderr: "Vim: Error reading input, exiting...\n\nVim: Finished.\r\n",
    },
)
```

Clearly I'm missing something here. I'll have to dig into this further. If I'm able to open `nvim` from a `std::process::Command` this feature is straightforward to make working.

**Comment by kiil** [comment]
Yes, but interestingly if I just press

`e`

inside taskwarrior-tui, it will open up the task for editing in neovim  (nvim) just fine, and neovim "overtakes" the terminal until i quit it. So it seems rust is able to do it somehow, but it just does not work from a simple shortcut.

**Comment by kdheepak** [comment]
I have a PR that solves this. I'm still not able to get `taskopen` to open nvim for me but using a explicit `nvim` instance works for me. If you would like to compile from source or [use the precompiled binary for your platform from the artifacts zip file](https://github.com/kdheepak/taskwarrior-tui/suites/3266778185/artifacts/76045541) from [the github action](https://github.com/kdheepak/taskwarrior-tui/actions/runs/1042223541), you can try out the PR. Any feedback is appreciated.

**Comment by kiil** [comment]
I tried out the PR - it works perfectly! Thanks for making it possible :)

**Comment by kdheepak** [comment]
I made a new release with this fix: https://github.com/kdheepak/taskwarrior-tui/releases/tag/v0.13.25

**Comment by kiil** [comment]
It works even better now. Thanks a lot!
