### ISSUE TITLE
Feature request:  Add hotkey for 'task sync' and option for autosync every x  minutes.

### ISSUE THREAD

**Issue by cocoonkid** [kdheepak/taskwarrior-tui#247]
**Description**
 Add hotkey for 'task sync' and option for autosync every x  minutes.

I have to leave the tui everytime I want to sync my todo which I do often as I work with multiple machines.

**Solution**
  Add hotkey for 'task sync' and option for autosync every x  minutes.

**Comment by kdheepak** [comment]
You can use a shortcut for `task sync`. See https://kdheepak.com/taskwarrior-tui/configuration/advanced/

As an example, if you add the following to your `.taskrc`:

```
uda.taskwarrior-tui.shortcuts.1=~/.config/taskwarrior-tui/shortcut-scripts/add-personal-tag.sh
uda.taskwarrior-tui.shortcuts.9=task sync
```

when you hit `1` it’ll run the `add-personal-tag.sh` script and when you hit `9` it’ll run `task sync`. 

As for running it every X minutes, I’ll look into that!

**Comment by cocoonkid** [comment]
Thank you so much.

**Comment by kdheepak** [comment]
This feature is available in https://github.com/kdheepak/taskwarrior-tui/releases/tag/v0.13.27
