### ISSUE TITLE
Persistently show current context in TUI

### ISSUE THREAD

**Issue by apkawel** [kdheepak/taskwarrior-tui#251]
**Description**

It would be nice to see the current context on the screen at all times.

Making my case: Users are presumed to be familiar with the contexts they create. Still, the current context is not apparent from the main state of the TUI, causing users to go back and forth between the main state and the context screen (c / esc / c / esc etc.).

**Solution**

Place name of current context at top of TUI (on same line as Task/Calendar).

This should be easy to do, and will provide users additional context that avoids additional keystrokes and user distraction.

**Comment by kdheepak** [comment]
This is a great idea! Thanks for opening an issue to suggest it! I've implemented it in a very straight forward manner. It shows the context in parentheses as part of the title (as you suggested) if the context is not `none`.

<img width="338" alt="Screen Shot 2021-07-27 at 1 05 19 PM" src="https://user-images.githubusercontent.com/1813121/127212979-dd5ca8b7-5274-427a-a0b4-3d2fd6b41718.png">

**Comment by apkawel** [comment]
This is awesome. Great job — thank you so much! :-)
