### ISSUE TITLE
Spurious jumps of highlighted line

### ISSUE THREAD

**Issue by apkawel** [kdheepak/taskwarrior-tui#253]
macOS 11.5
iTerm 2 3.4.9beta1 (using Toychest color theme)
taskwarrior 2.5.3
taskwarrior-tui 0.13.27

taskwarrior-tui ("TUI") appears to originally highlight the line that is selected. As I move up or down (selecting other lines) the highlighted line gets messed up: the highlight appears to jump around (often a second or two after the selection is changed) and after a few moves the highlight is on a different line from the selected line.

I presume this is a TUI issue and not an iTerm issue. If I am correct, (1) there should be a way to turn off the line highlighting altogether; and (2) the line highlighting should not lag at all; and (3) the line highlighting should always be on the same line as the selection.

I can provide an asciinema (but would have to anonymize data first).

Thank you for your work and consideration.

**Comment by kdheepak** [comment]
I’m using iTerm2 but I’m not experiencing any issue. Can you replicate the issue with the test data repository? Also, I believe the selection highlight colors are customizable. I’m on my mobile right now, I can expand when I get to a computer.

**Comment by apkawel** [comment]
Yes, I will. Please bear with me … have been slammed. Will respond soon.

**Comment by apkawel** [comment]
I think that I have figured out the problem (caused by iTerm 2).
iTerm 2 > Preferences > Profiles > Colors > deselect "Cursor Guide".

For some reason, iTerm 2's Cursor Guide jumps around the TUI. It will start off on the same line that is "selected" in the TUI, but then it will go to a line above, or below, or somewhere in the Task Details. Then it will jump to the correct line. Then it will go to an incorrect line again.

I am not sure if this is a bug in the TUI or in iTerm 2. Might be worth checking out.

**Comment by kdheepak** [comment]
Wow thanks for looking into that and figuring that out. I’ll look into it on my Mac too.

**Comment by kdheepak** [comment]
Hmm. I'm not seeing any spurious jumps of the highlighted line. I've tried with and without the setting enabled (I've always had that setting disabled btw). 

Can you send me a screen recording?

**Comment by kdheepak** [comment]
If this is still an issue can you reopen? I'm not able to replicate this so I'll close this for now.
