### ISSUE TITLE
Ask for confirmation before marking a task as done

### ISSUE THREAD

**Issue by vizcay** [kdheepak/taskwarrior-tui#257]
**Description**

The same arguments for #47 but for marking a task as done! I considering marking a task done a "destructive" operation in the sense that accidentally touching `d` can send a task into oblivion..

**Comment by vizcay** [comment]
@kdheepak 👏🏻 .. waiting for release!

**Comment by kdheepak** [comment]
I wanted to fix a few more bugs this weekend before making a release but it looks like I’ll not be able to get to that today. I’ll make a release with this feature now.

**Comment by kdheepak** [comment]
This feature is available in https://github.com/kdheepak/taskwarrior-tui/releases/tag/v0.13.30.
