### ISSUE TITLE
add more keybindings so that i can use ctrl+backspace to backward delete a word or ctrl+x to kill a line when adding new todo in tui

### ISSUE THREAD

**Issue by alexzanderr** [kdheepak/taskwarrior-tui#258]
when using terminals you have `ctrl+w` to `backward delete a word` and `ctrl+u` to `kill a line` (delete the entire line)

personally, i dont like using `ctrl+w` to backward delete word, i feel very comfortable with `ctrl+backspace`

is there a way to map the `ctrl+backspace` to that i can backward delete a word using taskwarrior-tui?

if not, i would request a feature for additional keybindings.

thanks.

**Comment by kdheepak** [comment]
Currently there’s no way to reconfigure it but I’m open to adding ctrl backspace as an additional way to remove the previous word. I can add that as a feature.

**Comment by alexzanderr** [comment]
thank you so much!

**Comment by kdheepak** [comment]
It looks like crossterm (the library that I'm using) doesn't support this: https://github.com/crossterm-rs/crossterm/issues/575. I'll keep an eye on the related issues, but for now this is not possible to implement.

**Comment by kdheepak** [comment]
I've added support for CtrlBackspace and AltBackspace for backspace word (as well as CtrlDelete and AltDelete for forward delete word). However, until crossterm supports CtrlBackspace, that code path will never be processed. Once they do add it (if it is even possible to add it), the next release of this tool will automatically support it.

AltBackspace works now for me though, so you can try that instead. I'll close this issue for now. Feel free to reopen if you think this is not resolved.

**Comment by kdheepak** [comment]
This feature is available in https://github.com/kdheepak/taskwarrior-tui/releases/tag/v0.13.31

**Comment by alexzanderr** [comment]
thanks a lot for support!

**Comment by alexzanderr** [comment]
so this release will be available when they update `crossterm`? i mean avaiable for me who i want to install taskwarrior-tui or update using pacman or pamac package manager for arch.

i know i can download the source and compile, or download alreay compiled.

but the question is: the release is not visible for pacman right now? right?

**Comment by kdheepak** [comment]
This release will be available now and you can use meta or option or alt + backspace. However, ctrl backspace won’t work until crossterm releases a new release, after which if I update the dependencies and make a new release that’ll work too. Hope that clarifies it.

**Comment by alexzanderr** [comment]
yes. thanks
