### ISSUE TITLE
Pressing the down arrow results in the current input being lost forever

### ISSUE THREAD

**Issue by jakec-dev** [kdheepak/taskwarrior-tui#260]
**Describe the bug**

When interacting with the bottom input bar (the box with `Filter Tasks` heading when opening taskwarrior-tui) in any way (e.g. filtering, adding tasks, modifying tasks, etc), if you press the down key on your keyboard you will lose whatever text you have already inputted with no way to retrieve it.

**To Reproduce**

1. Open taskwarrior-tui and press `a` to add a new task
2. Add any task, e.g. `"Wash car" +test` and press enter to save it
3. Press `a` to add another task
4. Start typing a new task in the `Add Task` box but don't press enter to save it, e.g. `"Buy groceries" +test`
5. Press the down arrow on your keyboard. 
 
The text you inputted in step 4 will be replaced with the text you inputted in step 3.

There is no way to get back to the text you had begun typing in step 4, so if you were writing a particularly long and detailed task and accidentally pressed the down arrow on your keyboard, you will have to start typing the task out all over again. 

This has happened to me a number of times already and it's quite frustrating when you lose a particularly detailed task you were entering and have to try to remember it all.

**Environment (please complete the following information):**

- Operating System:  Linux
- Installation: `yay -S taskwarrior-tu-git`
- taskwarrior-tui version: 0.13.29
- task version: 2.5.3

**Comment by kdheepak** [comment]
Yeah, that’s annoying. Sorry about that. I’ll work on this next immediately.

**Comment by kdheepak** [comment]
I'm pretty sure the open PR right now fixes this, but I have to do more testing. The whole history is a bit of a hack. I'm hoping I can clean it up as part of this fix. If you want to test it out, you can use the artifacts from the referenced PR or build from source from the PR.

**Comment by kdheepak** [comment]
I made some more changes and now it works satisfactorily. Feel free to reopen this issue or open a new issue if you are running into any more problems.

**Comment by kdheepak** [comment]
This is available in this release: https://github.com/kdheepak/taskwarrior-tui/releases/tag/v0.13.34
