### ISSUE TITLE
background_process fails after non-zero exit code

### ISSUE THREAD

**Issue by nickwynja** [kdheepak/taskwarrior-tui#265]
**Describe the bug**

`background_process` works properly until it runs into a non-zero exit code and then it doesn't ever run again. 

**To Reproduce**

Create a shell script with the following code and make it executable. I've called this `~/.dotfiles/taskwarrior/tui-task-sync.sh`:

```
echo "`date` run as background_process; exiting 0" > /tmp/tw-sync.log
exit 0
```

Taskrc has the following:

```
uda.taskwarrior-tui.background_process=~/.dotfiles/taskwarrior/tui-task-sync.sh
uda.taskwarrior-tui.background_process_period=10
```

Now open TUI and do `tail -f /tmp/tw-sync.log` and you should see something like this:

```
Mon Aug  2 08:08:05 EDT 2021 run as background_process; exitiing 0
Mon Aug  2 08:08:15 EDT 2021 run as background_process; exitiing 0
Mon Aug  2 08:08:25 EDT 2021 run as background_process; exitiing 0
Mon Aug  2 08:08:35 EDT 2021 run as background_process; exitiing 0
Mon Aug  2 08:08:45 EDT 2021 run as background_process; exitiing 0
```

If you update the script to this:

```
echo "`date` run as background_process; exiting 1" > /tmp/tw-sync.log
exit 1
```

and check the logs again (you don't need to close and re-open tui), you should see a final log line like this:

```
Mon Aug  2 08:09:35 EDT 2021 run as background_process; exitiing 1
```

The one time the script exited with 1 was the last time `background_process` ran and won't run again until I close tui and re-open.

**Environment (please complete the following information):**

- Operating System:  Mac
- Installation:  cargo build
- taskwarrior-tui version:  0.13.29

```bash
taskwarrior-tui --version
```
- task version: 2.5.3

```bash
task --version
```

**Additional context and information**

If you have `task sync` as a background process, `task sync` will return an exit code of 1 if it fails to sync, like if you're offline. I ran into this bug by noticing background sync would stop working after I went offline and came back online.

A workaround here is to always `exit 0` in a script.

**Comment by kdheepak** [comment]
This was by design since if a background process crashed I didn’t want to keep running it over and over again. Admittedly, the current solution is not ideal. I think I’d like to add some way to show the feedback of an error to the user before changing this behavior. 

I thought I documented this behavior but I’m not seeing anything now. I’ll add a comment in the documentation. The workaround you mentioned should be sufficient for people to use this feature right now.

**Comment by nickwynja** [comment]
Ah, I see. That makes sense. I'll close this since it's not a bug.
