### ISSUE TITLE
Use $XDG_STATE_HOME for history files

### ISSUE THREAD

**Issue by bharatvaj** [kdheepak/taskwarrior-tui#271]
State files such as history should not be placed under `$XDG_CONFIG_HOME` as they are not config files. Consider placing them in `$XDG_STATE_HOME`.

**Comment by kdheepak** [comment]
Ah, I didn’t know about that. Thanks for opening an issue!

**Comment by kdheepak** [comment]
I made a new release with this feature! https://github.com/kdheepak/taskwarrior-tui/releases/tag/v0.14.6
