### ISSUE TITLE
Set default filter action when starting taskwarrior-tui

### ISSUE THREAD

**Issue by simonhoffmann** [kdheepak/taskwarrior-tui#272]
**Description**

Currently, taskwarrior-tui always starts with the filter `status:pending limit:page`.
If i prefer a different filter, I have to change the filter manually every time.
It would be nice to have a `.taskrc` variable to specify the default filter at startup.

**Solution**

Add a new `.taskrc` variable that specifies the default filter at startup.

**Additional context**

none.

**Comment by kdheepak** [comment]
I believe `taskwarrior-tui` already supports what you are asking for. Can you check this comment:

https://github.com/kdheepak/taskwarrior-tui/issues/221#issuecomment-835734357

I think I’ll have to update the documentation to describe this better.

**Comment by kdheepak** [comment]
If you are planning to use the same, you can just not set `uda.taskwarrior-tui.task-report.next.filter` to anything. 

If you want them to be different, you can set `uda.taskwarrior-tui.task-report.ready.filter` to wherever you’d like, for example the value of `report.ready.filter`.
