### ISSUE TITLE
Autocomplete inserts at end of line, and not on current cursor position

### ISSUE THREAD

**Issue by Petemir** [kdheepak/taskwarrior-tui#275]
Hi again! I was just doing a batch addition of some similar tasks that perhaps where different on a word or two, so I used the history to go back to the previous "Add" command and edited it accordingly. When I did this and tried to use the autocomplete feature for editing the project field, when I selected an option it added the remaining text at the end of the line, and not at the cursor position.

* Start the "Add a task" functionality
* Write something
* Go back to the start of the line and add something with the autocomplete feature (e.g. the "project:" field)
* Press "Enter"
* The auto-completed text gets added at the end of the line

Let me know if I can do something to help with this! Thanks

![Autocomplete](https://user-images.githubusercontent.com/287105/135260517-cb7c4295-4a95-4ab5-8807-b5f5438d654f.gif)

**Environment (please complete the following information):**

- Operating System: Linux
- Installation: github releases
- taskwarrior-tui version: v0.13.33
- task version: 2.5.3

**Comment by kdheepak** [comment]
This should be resolved in https://github.com/kdheepak/taskwarrior-tui/releases/tag/v0.13.34.

**Comment by Petemir** [comment]
It is, thanks! :clap:
