### ISSUE TITLE
Tasks not displayed

### ISSUE THREAD

**Issue by lucaschamorrotuduri** [kdheepak/taskwarrior-tui#281]
Hi!
Recently, I've been having this issue where no tasks are displayed in the tui.
It's strange because the application recognizes the context and can change it, and new tasks can be created and appear in the task report (see the following screen capture):
![ttbug](https://user-images.githubusercontent.com/72558461/137289403-e61bc1b6-0785-4ce0-b08e-21ce91416a5f.png)

If I move the '*.data' files away from the data folder, then it starts working again:
![ttworks](https://user-images.githubusercontent.com/72558461/137289906-1b4f646b-22a8-472a-bbcb-df5b7d7d0d03.png)

This leads me to suspect that something is wrong with my data files, but I can't figure out what it is that trips only taskwarrior-tui but not task.
I've tried several filters and none at all, with no effect.
I'm using the prebuilt binary from Arch Linux's repo, but I've also compiled from source and the behavior is the same.

**Comment by Unix-Demonologist** [comment]
For me it was happened after update taskwarrior itself. Downgrade fixes it for me (Arch too).

**Comment by titosemi** [comment]
Confirmed. Downgrading taskwarrior solves the issue.

**Comment by kdheepak** [comment]
Wow. Thanks for the bad data and for identifying the problem. I was able to reproduce the problem, and I've made the fix and I no longer get a crash when I use the bad data that you shared. I've made a new release that has this fix: https://github.com/kdheepak/taskwarrior-tui/releases/tag/v0.14.4
