### ISSUE TITLE
cannot pass custom taskrc file and cannot tell custom data location

### ISSUE THREAD

**Issue by alexzanderr** [kdheepak/taskwarrior-tui#284]
i have this data `folder`:
`~/Alexzander__/manjaro-21-xfce/dotfiles/config_home/task-warrior/general-todo/data`
(dont ask about this path, this is how my system is configured)
you know how data tree representation looks. just dot data files

and i have this `taskrc` file
`~/Alexzander__/manjaro-21-xfce/dotfiles/config_home/task-warrior/general-todo/taskrc`
which contains:
```
data.location=~/Alexzander__/manjaro-21-xfce/dotfiles/config_home/task-warrior/general-todo/data
```
as you can see they are located in `general-todo` folder (based on category)

running `taskwarrior-tui` as:
```shell
taskwarrior-tui --config \
~/Alexzander__/manjaro-21-xfce/dotfiles/config_home/task-warrior/general-todo/taskrc

[taskwarrior-tui error]: Unable to run `task show`.
A configuration file could not be found in

Would you like a sample /home/alexzander/.config/task-warrior/taskrc created, so Taskwarrior can proceed? (yes/no)
TASKRC override: /home/alexzander/.config/task-warrior/taskrc
TASKDATA override: /home/alexzander/.config/task-warrior/data
Cannot proceed without rc file.

Please check your configuration or open a issue on github.

If you need additional help, please report as a github issue on https://github.com/kdheepak/taskwarrior-tui
```
`doesnt work`

why i cant just pass my custom config file and custom data folder

i see you hardcoded in your rust application these paths:
- `.config/task-warrior/taskrc`
- `.config/task-warrior/data`
if i dont symlink my custom paths with xdg_config_home/task-warrior or if dont have some default config in the xdg_config_home/task-warrior; taskwarrior-tuifolder will never ever accept my custom config

### why i want this?
to have multiple data folders based on different categories of todos, for example:
- general
- programming
- life
- bla bla
and i want to create these folders and open 4 instances of taskwarrior-tui based on these folders

**Comment by alexzanderr** [comment]
**EDIT**
you didnt hard coded the xdg config home task-warrior paths
i have set some export and didnt reloaded the shell

**BUT**
still doesnt work with my config
```shell
❱  taskwarrior-tui --config=/home/alexzander/Alexzander__/manjaro-21-xfce/dotfiles/config_home/task-warrior/taskrc
   [taskwarrior-tui error]: Unable to run `task show`.
A configuration file could not be found in

Would you like a sample /home/alexzander/.taskrc created, so Taskwarrior can proceed? (yes/no)
Cannot proceed without rc file.

Please check your configuration or open a issue on github.

If you need additional help, please report as a github issue on https://github.com/kdheepak/taskwarrior-tui
```

it just doesnt want to load my config:
```
data.location=~/Alexzander__/manjaro-21-xfce/dotfiles/config_home/task-warrior/data
```

**Comment by kdheepak** [comment]
Hi, thanks for making such a detailed issue! This is a known bug, but isn’t communicated clearly, sorry. The `—config` doesn’t actually do anything right now. You can use the `TASKRC` and `TASKDATA` environment variables and that should work.

**Comment by alexzanderr** [comment]
can u fix dash dash config please?

**Comment by alexzanderr** [comment]
> `--config` is for `taskwarrior-tui` config and not for `task` config. We need to figure out why setting the environment variable isn't working in `taskwarrior-tui`.

then what config should task tui have? because i didnt saw any docs for this and `i assumed that` it means task warrior's configuration, for example data location

**Comment by alexzanderr** [comment]
okey. i understand know. i suggest you add some docs about `--config` to tell people that is a useless argument.

sorry for replying to late.

> What I don't understand in your setup is how task is able to find the .taskrc file?

normally ( what i had before for a long time ), i have this:
these 2 exports:
```
export TASKRC="$XDG_CONFIG_HOME/task-warrior/taskrc"
export TASKDATA="$XDG_CONFIG_HOME/task-warrior/data"
```

taskrc:
```
data.location=~/.config/task-warrior/data
```

taskrc is located at `/home/alexzander/Alexzander__/manjaro-21-xfce/dotfiles/config_home/task-warrior/taskrc`

but the folder `task-warrior` from the above path is symlinked to `~/.config/task-warrior`

**Comment by alexzanderr** [comment]
now i see, if you are saying that --config is useless, then i cant pass custom taskrc file to taskwarrior-tui, then i cant realise what i want.

what i wanted:
### to have multiple `taskrc`s and multiple `data`s folders and to open multiple instances of taskwarrior-tui with every possible taskrc file

because i wanted to make categories.

**Comment by alexzanderr** [comment]
im already using tmux bro. with this, my env with become very complicated and very hard to maintain.

a lot of inceptions

**Comment by alexzanderr** [comment]
can you make a feature where i can pass a custom taskrc file and data folder to taskwarrior-tui?

**Comment by kdheepak** [comment]
Yeah, I plan to! I just haven't gotten around to it yet. I'll leave this issue open to track it.

**Comment by kdheepak** [comment]
I made a new release with this feature: https://github.com/kdheepak/taskwarrior-tui/releases/tag/v0.17.0

**Comment by alexzanderr** [comment]
i saw. thanks a lot man. it was worth waiting.

**Comment by alexzanderr** [comment]
thanks for the update man. but how am i supposed to tell taskwarrior-tui to operate in custom folder?

**Comment by alexzanderr** [comment]
for example i have a folder structure for `general` like this
```shell
 [.../task-warrior-tui/general]
❱  tree
 .
├──  taskdata
│  ├──  backlog.data
│  ├──  completed.data
│  ├──  pending.data
│  └──  undo.data
├──  taskrc
└──  tui-data
   ├──  filter.history
   └──  taskwarrior-tui.log
```
with `taskrc`:
```
data.location=~/Alexzander__/manjaro-21-xfce/data/task-warrior-tui/general/taskdata
```

and running taskwarrior-tui `at cwd` with these command line args:
```shell
taskwarrior-tui --taskrc taskrc --data tui-data
```

i do get an interface like this
![image](https://user-images.githubusercontent.com/54772464/148391781-293c052b-e23d-4d94-ace2-2ef2f600f65b.png)

but when having the same tree structure for `programming` folder
```shell
 [.../task-warrior-tui/programming]
❱  tree
 .
├──  taskdata
│  ├──  backlog.data
│  ├──  completed.data
│  ├──  pending.data
│  └──  undo.data
├──  taskrc
└──  tui-data
   └──  taskwarrior-tui.log
```
with `taskrc`:
```
data.location=~/Alexzander__/manjaro-21-xfce/data/task-warrior-tui/programming/taskdata
```

and running `the same` taskwarrior-tui command `at cwd` with these command line args:
```shell
taskwarrior-tui --taskrc taskrc --data tui-data
```

i do get an interface like this:
![image](https://user-images.githubusercontent.com/54772464/148392103-dcedd097-ba4f-4d37-ba2e-337a7f19c49d.png)


this is a really good update. im super glad.

**Comment by kdheepak** [comment]
Glad it is working out well for you!

**Comment by alexzanderr** [comment]
yes. indeed. you can put this example or something similar in readme, for people to know that you can do that and that is actually a good idea.

**Comment by alexzanderr** [comment]
btw. are you planning for making the project in python, in the future? just asking. if so, i can contribute.

**Comment by kdheepak** [comment]
Unless there’s a feature I need and it cannot be done in rust, I don’t think I’ll write it in python. But feel free to make feature requests. And if it is straightforward and if you want to learn rust, I can help guide you to making a contribution, if you are interested in doing so.

**Comment by alexzanderr** [comment]
hmm, very nice. i will think about that. thanks
