### ISSUE TITLE
Create snap of taskwarrior-tui

### ISSUE THREAD

**Issue by kwoot** [kdheepak/taskwarrior-tui#29]
**Description**
I think it would be nice of people could simply do a 'snap install taskwarrior-tui' to get the binary.

**Solution**

Yes, this means some work. If I had time, and if I knew how, I would do it myself.

**Additional context**

**Comment by kdheepak** [comment]
Great idea! I'll look into it.

**Comment by kdheepak** [comment]
Snap packages are now uploaded on very release: https://snapcraft.io/taskwarrior-tui. Let me know if you try it, I don't have a Ubuntu VM to test this out.

**Comment by kwoot** [comment]
I just ran a snap find but no result yet. I will retry soon.

**Comment by kdheepak** [comment]
It's only on the edge channel at the moment btw.
