### ISSUE TITLE
Multiline task context causes all context selection to shift

### ISSUE THREAD

**Issue by MNandor** [kdheepak/taskwarrior-tui#298]
**Describe the bug**

When a definition of a task context doesn't fit in a single line, context switching using `c` is shifted incorrect.
Example: if the 1st context spans 2 lines (1 extra line), selecting context 3 will switch to context 2 instead.

**To Reproduce**

- [x] Reproducible using the test data located here: <https://github.com/kdheepak/taskwarrior-testdata/>

1. Define multiple contexts
2. Give one of the contexts a long definition (see below) that spans multiple lines in `task context`
3. Open TUI, press `c`, and select one of the context __below__ the multiline context
4. Observe the shift

**Environment (please complete the following information):**

- Operating System: Linux
- Installation: arch
- taskwarrior-tui version: taskwarrior-tui 0.14.4
- task version: 2.6.1

Gif attached (note: in the context switcher menu, I repeat J-Enter). Note how my cursor is over "work" when I successfully switch to "pers3"
![task_bug](https://user-images.githubusercontent.com/59140312/139498563-9241c8d0-2ec6-4df5-bf48-70ebc6d6f90a.gif)

Screenshot: the contexts used
![image](https://user-images.githubusercontent.com/59140312/139498673-caa14ab8-86a8-4483-b615-277bf26ee177.png)

**Comment by MNandor** [comment]
I created this (excuse my paint skills) to illustrate what I think is happening. Note that the context filters are applied correctly, it's the index of the selection that shifts.
![image](https://user-images.githubusercontent.com/59140312/139500062-a5be4e4c-6ce6-469e-8776-b1a36b6e3013.png)

**Comment by kdheepak** [comment]
Thanks for reporting. I haven't tested it yet, but I can see how this would be broken the way I've currently implemented it. I'll fix it over the weekend.

**Comment by kdheepak** [comment]
This should be fixed in https://github.com/kdheepak/taskwarrior-tui/releases/tag/v0.14.5!
