### ISSUE TITLE
Crash ParseIntError

### ISSUE THREAD

**Issue by desbma** [kdheepak/taskwarrior-tui#299]
```
RUST_BACKTRACE=full taskwarrior-tui
Backtrace (most recent call first):
  File "<unknown>", line 0, in __libc_start_main

The application panicked (crashed).
  called `Result::unwrap()` on an `Err` value: ParseIntError { kind: InvalidDigit }
in src/pane/project.rs, line 153
thread: main
```
Arch Linux, taskwarrior-tui 0.14.4-1, task 2.6.1-1

The recent task 2.6 taskwarrior update brought many regressions for me, but I waited a bit to open issues. 
The last working combination is taskwarrior-tui 0.13.34-1 and task 2.5.3-1.

**Comment by desbma** [comment]
The combination of taskwarrior-tui 0.13.34-1 and task 2.6.1-1 does not crash but gives an empty task list.

**Comment by kdheepak** [comment]
The previous error you shared was because I think you have spaces in your context name or project name? I think I fixed that.

But it is surprising that it gives an empty list now. Can you try with the test data located here: https://github.com/kdheepak/taskwarrior-testdata? 

> The recent task 2.6 taskwarrior update brought many regressions for me, but I waited a bit to open issues.

Yeah, lots of issues, unfortunately. I'm super glad people are opening issues, because it is helping me find the problem. I don't use all the features of taskwarrior or even taskwarrior-tui, and I wouldn't have caught these until someone posted a bug report.

**Comment by desbma** [comment]
> But it is surprising that it gives an empty list now.

That is with taskwarrior-tui **0.13.34-1** (not the most recent) and task 2.6.1-1.

With latest versions for both, I get the crash above.

I don't use contexts, and don't have spaces in any of my projects (some have dashes though).

**Comment by kdheepak** [comment]
Can you share the output of `task summary`? Even an anonymized version is fine, but if you can maintain the same whitespace that'd be ideal.

```

Project   Remaining Avg age Complete 0%                        100%
(none)           24     9mo      20%
colortask         1    1.0y       0%
wth               1    1.0y       0%

3 projects
```

Mine contains `Avg age`. Does your not?

**Comment by kdheepak** [comment]
I think I know what the problem is, your output might contain something like this:

```
Project  Remaining  Avg Age  Complete  0%                  100%
A               12      13d       55%  XXXXXXXXXXXXX-----------
B              109   3d 12h       10%  XXX---------------------
```

The `3d 12h` breaks my current code. I'll look into this now.

**Comment by kdheepak** [comment]
This should be fixed in https://github.com/kdheepak/taskwarrior-tui/releases/tag/v0.14.5!

**Comment by desbma** [comment]
Thanks, the crash is fixed, but I am back with an empty task list.

It's probably due to my filter, I have `report.next.filter=(status:pending or status:waiting)` in my `~/.taskrc`, should I open a new issue ?

**Comment by kdheepak** [comment]
Yes please. Thanks!
