### ISSUE TITLE
X selection is disabled in taskwarrior-tui

### ISSUE THREAD

**Issue by wwalker** [kdheepak/taskwarrior-tui#3]
on linux, selecting text in the taskwarrior-tui is disabled.

I don't see any mouse interaction, so I don't believe that twtui needs to grab the mouse actions.

If it doesn't need to do it, my PR will fix it.  But if I am wrong and it does need to grab the mouse events, then just close this.

**Comment by kdheepak** [comment]
I had plans for adding some mouse functionality but haven't implemented anything yet. If selecting text doesn't work with mouse functionality is enabled it may be a good enough reason to never support mouse events. Thanks for making the PR! I've merged it, and I'll reconsider the possibility of supporting mouse events in the future if it doesn't interfere with selection.
