### ISSUE TITLE
Some usage feedback

### ISSUE THREAD

**Issue by kwoot** [kdheepak/taskwarrior-tui#30]
-The home, end, pgup and pgdn key do not seem to work on my end. Maybe not implemented yet?
-Maybe add a line somewhere in the gui that shows possible commands and/or possible key strokes?
 (like lazygit).

This is a very promising project!

**Comment by kdheepak** [comment]
Great ideas! 

> The home, end, pgup and pgdn key do not seem to work on my end. 

This is currently not implemented. What would you like this to do? Any suggestions?

> Maybe add a line somewhere in the gui that shows possible commands and/or possible key strokes?

If you hit `?` it should pull up the help menu. All the supported key bindings are also listed in [KEYBINDINGS.md](https://github.com/kdheepak/taskwarrior-tui/blob/f8d2d01791f052a70c3a38f99694e3cdcb79c5ca/KEYBINDINGS.md).

> This is a very promising project!

Thanks!

**Comment by kwoot** [comment]
> Great ideas!
> 
> > The home, end, pgup and pgdn key do not seem to work on my end.
> 
> This is currently not implemented. What would you like this to do? Any suggestions?

Home: move task pointer to top of task list.
End: move task pointer to bottom of task list
PgUp/PgDn: move task pointer one page down/up

> 
> > Maybe add a line somewhere in the gui that shows possible commands and/or possible key strokes?
> 
> If you hit `?` it should pull up the help menu. All the supported key bindings are also listed in [KEYBINDINGS.md](https://github.com/kdheepak/taskwarrior-tui/blob/f8d2d01791f052a70c3a38f99694e3cdcb79c5ca/KEYBINDINGS.md). Is this what you are asking for?

Well, I guess a tui hint to press the '?' to open the help menu would be enough.

> 
> > This is a very promising project!
> 
> Thanks!

I just bought a rust book. So maybe I can use this as a nice playground.

One feature that would be nice: 'switch' active task. it would stop the current active task and start the task where the pointer is. When number of active tasks > 1 do something else. Maybe present selection list. I don't know yet.

**Comment by kdheepak** [comment]
> One feature that would be nice: 'switch' active task. it would stop the current active task and start the task where the pointer is. 

This is already implemented. You can hit the `s` key to run `task start` on task. Hitting `s` again runs `task stop` on that task.

**Comment by kdheepak** [comment]
Thanks for offering usage feedback! `PageUp`, `PageDown` are implemented along with `J` and `K` in https://github.com/kdheepak/taskwarrior-tui/releases/tag/v0.8.11.

**Comment by kdheepak** [comment]
> Well, I guess a tui hint to press the '?' to open the help menu would be enough.

This is a good idea and thanks for suggesting it. However, at the moment, I'm going to not implement it since once a user knows about `?` it is information that doesn't serve any purpose and I would rather not have it on the screen at all times. I think it is important to consider discoverability of the `?` key for new users, but for now I'm going to punt on this. I will consider this in the future.
