### ISSUE TITLE
Empty task list

### ISSUE THREAD

**Issue by desbma** [kdheepak/taskwarrior-tui#305]
I get an empty task list with taskwarrior 0.14.5 (tested with `cargo run` in the repository).

I'm on Arch Linux. Since the recent taskwarrior & taskwarrior-tui updates broke different things, I don't know exactly which version caused the regression, but I know I don't have this issue with taskwarrior 2.5.3 and taskwarrior-tui 0.13.34.

It seem to be related to the default filter. I have `report.next.filter=(status:pending or status:waiting)` in my ~/.taskrc. 
If I remove the filter, the tasks show up. With taskwarrior 2.5.3, only one task shows up even if I remove the filter.

**Comment by gkssjovi** [comment]
I have the same problem

**Comment by kdheepak** [comment]
I'm able to reproduce this. I'll look into what is going on.

**Comment by desbma** [comment]
Thank you

**Comment by gkssjovi** [comment]
For me the problem is not solved.
I'm on mac os, using the taskwarrior version 2.5.3 and the list is still empty. 
Is there a way to debug this, to see an error log?

**Comment by kdheepak** [comment]
I have been adding logging but it isn’t in a public branch yet. If you can recompile from source, I can tell you how to debug this. 

Also, can you not update to the latest version of taskwarrior? I don’t think that that might be a cause of this issue but there are some changes between taskwarrior 2.5 and 2.6 that I’ve resolved in the most recent versions but I haven’t rested on 2.5.x. 

And going forward, my plan is to only maintain this for the latest version of taskwarrior, and this might mean partial support for some features in older version or dropping support for older versions of taskwarrior completely. It’ll depend on how much effort it is to maintain or add a feature, which is why I only want to guarantee support for the latest version.

**Comment by desbma** [comment]
It's also broken for me with taskwarrior 2.5.3, but since taskwarrior-tui now works well for my use cases with 2.6.1, I have updated both.

Given the lack of care from the taskwarrior authors for a stable interface, and the many regressions each release brings, even in minor versions, I understand and support @kdheepak's choice to only support the last taskwarrior version.

**Comment by kdheepak** [comment]
If you want to debug this and are willing to install rust and cargo, you can:

1) Uncomment this line:

https://github.com/kdheepak/taskwarrior-tui/blob/896999293058e25b1a64c685e8636859c4d82ae5/src/app.rs#L4407

2) Add `dbg!(&task);` to this line:

https://github.com/kdheepak/taskwarrior-tui/blob/896999293058e25b1a64c685e8636859c4d82ae5/src/app.rs#L1579

3) Run `cargo test -- --nocapture test_app` from the command line

`dbg!(&task);` will print out the command that is being run. You can run this to see what the output is. This json is what is read into `taskwarrior-tui`. This was where I found the bug for taskwarrior 2.6. I don't imagine this is where the issue is with 2.5, but this is a start. You can add more `dbg!(...)` elsewhere in the codebase to maybe figure out what is going on. Unfortunately, this is the way you have to do debugging at the moment. This is not ideal, and I'm hoping to improve it going forward.

**Comment by kdheepak** [comment]
I think going forward, maybe the plan is to not rely on the stdout printed by `taskwarrior`'s various commands, and only rely on `task export` and the values in `.taskrc`. This unfortunately means reimplementing a lot of features in `taskwarrior` in `taskwarrior-tui`. 

Currently, `taskwarrior-tui` depends on the output of `task show`, `task summary`, `task {N}`, `task context` (I might be missing others commands), and if that changes in any way, `taskwarrior-tui` might silently fail (which might be happening in this case) or might even crash. 

Hopefully, I've been you enough clues to debug this if you choose to do so. If I get the chance, I'll look into this, but no promises :)

**Comment by gkssjovi** [comment]
I'm not intended to stay on an older version of taskwarrior. I have just updated to the last version.
Last week the last version it was not working and 2.5.3 was working fine. Now it's inverted ;).

Now the tasks are displaying only if I put `status:pending`.
if I delete filters, it will not show all the task ( Completed, Delete ... ) as before. Probably I will try to debug this if there is not a quick tip you may know. 
This interface is perfect, I hope It will work.
I have also created a link between taskwarrior and timewarrior that will create a some new columns that will show the total time spent on each task and it will estimate the cost. ( https://github.com/gkssjovi/trackwarrior ).
Thank you for the suggestions, if you know a quick fix for the last problem it will be geat.

**Comment by gkssjovi** [comment]
I have ran the command and I got this error.

```
taskwarrior-tui (main) cargo test -- --nocapture test_app
   Compiling taskwarrior-tui v0.14.6 (/Users/gkssjovi/Desktop/taskwarrior-tui)
error: environment variable `TASKDATA` not defined
    --> src/app.rs:3382:42
     |
3382 |         let mut f = File::open(Path::new(env!("TASKDATA")).parent().unwrap().join("export.json")).unwrap();
     |                                          ^^^^^^^^^^^^^^^^
     |
     = note: this error originates in the macro `env` (in Nightly builds, run with -Z macro-backtrace for more info)

error: environment variable `TASKDATA` not defined
    --> src/app.rs:3393:28
     |
3393 |         let cd = Path::new(env!("TASKDATA"));
     |                            ^^^^^^^^^^^^^^^^
     |
     = note: this error originates in the macro `env` (in Nightly builds, run with -Z macro-backtrace for more info)

error: could not compile `taskwarrior-tui` due to 2 previous errors
```

**Comment by kdheepak** [comment]
You'll need to clone the tests, which is located over here: github.com/kdheepak/taskwarrior-testdata.

I think I figured out what the problem is though, but I don't know how to solve it yet. When `taskwarrior-tui` runs the following command, the data is empty:

```
[src/app.rs:1602] &task = "task" "rc.json.array=on" "rc.confirmation=off" "\'(status:pending or status:waiting)\'" "export"
[src/app.rs:1608] &data = "[\n]\n"
```

But when I type that in the command line it works as expected. I'm looking into it.

**Comment by desbma** [comment]
> I think going forward, maybe the plan is to not rely on the stdout printed by taskwarrior's various commands, and only rely on task export and the values in .taskrc. This unfortunately would mean reimplementing a lot of features in taskwarrior in taskwarrior-tui. I'll reach out to the taskwarrior devs to see what they think.

This would be a lot more robust, because the only reliable interface taskwarrior provides for other program is `task export` and `task _get`.
Reimplementing the rest would be a lot of work indeed, because that is 90% of the value of taskwarrior (the data model itself is very simple). That could be gradually implemented though.

**Comment by gkssjovi** [comment]
Yes, it will be much work, I hope they will create a more reliable interface.
Those problems are strange. I will try de debug this somehow ;) Thx

**Comment by kdheepak** [comment]
@gkssjovi what version of `taskwarrior-tui` was working with 2.5.x for you?

**Comment by gkssjovi** [comment]
I don't remember the version number. Last week I have installed taskwarrior-tui for the first time. I have installed it via brew package manager. The version only have the Tasks and Calendar tabs, without the Project tabs. As for the filter it came only with status:pending and page:limit.

**Comment by kdheepak** [comment]
I’m able to fix it. However, the json schema for tasks has changed between taskwarrior 2.5.3 and 2.6.1. This happens when using `depends`.

**Comment by gkssjovi** [comment]
I still not able to display all tasks.
How I can override the report by default?
I have tried `uda.taskwarrior-tui.task-report.next.filter=$(task show report.next.filter)` but as an output I get nothing.

![Screenshot 2021-11-02 at 08 31 58](https://user-images.githubusercontent.com/5613459/139797502-0cba0f48-97fe-415d-bd01-e6ed6a95a458.png)

I think is is the problem for me.
Thank you for investigating.

**Comment by kdheepak** [comment]
Can you try the latest commit on the `main` branch?

**Comment by gkssjovi** [comment]
Yes, I have tried, it the same think. 
What I want is to load the report all , with the filter status:pending. And then there is no filter there just to show the entire list including uuid.  Probably I missing something.

**Comment by kdheepak** [comment]
I merged a new PR to the `main` branch just when I made the previous comment. Did you try that?

**Comment by gkssjovi** [comment]
Yes, I have made a pull require on the main branch, and also checked on the new branch. It is the same.
I think the program it always take the task next even the filters are empty.

**Comment by gkssjovi** [comment]
I have found a working version for me, this commit `91938b56358b918afa83ca198ccb152702d0740c` it is working well. Where there is no filter it will show the entire list of tasks. A litter problem with the context, but that is fine.
Thank you

**Comment by kdheepak** [comment]
Hmm. There should be no difference between that commit and the latest commit on the `main` branch in terms of behavior.

**Comment by gkssjovi** [comment]
This one seems to work, I don't know what is happen with other ones.

![sample](https://user-images.githubusercontent.com/5613459/139879065-bdbb36de-7bd8-494c-86c5-a0dce4b4de3f.gif)

Sor some of the other commits I get this error message, when I write `cargo run`
`[taskwarrior-tui error]: invalid digit found in string

If you need additional help, please report as a github issue on https://github.com/kdheepak/taskwarrior-tui`

Anyway I'm glad one of the versions works.

**Comment by kdheepak** [comment]
It turns out trying to support this syntax : `report.next.filter=(status:pending or status:waiting)` caused lots of regressions. I'm unfortunately going to have to revert that change.

However, you can change your `taskrc` to `report.next.filter='(status:pending or status:waiting)'` and it'll work fine. Notice the single quotes to surround this filter.

**Comment by gkssjovi** [comment]
I have build the last release, and it is working fine if I wrote `status:pending` for the report.next.filter.
The problem is, when I clear the filter entirely I want to display the all tasks like `report all`. 
This behaviour Is working on the commit `91938b56358b918afa83ca198ccb152702d0740c` I have mentioned earlier.

**Comment by kdheepak** [comment]
Can you try the latest commit on the `main` branch with `taskwarrior` 2.6.1? It seems to be working for me as expected.

https://user-images.githubusercontent.com/1813121/140983172-873b90d7-ccdf-44dc-87cc-c215ff67e65e.mov

**Comment by kdheepak** [comment]
`report.next.filter=(status:pending or status:waiting)` should now work as expected too.

**Comment by gkssjovi** [comment]
Now it's perfect! ;) 
Everything is working as expected.
So the problem was just this line of code `highlight_style = style.patch(self.config.uda_report_style_selection);`
Thank you for fixing it.

**Comment by gkssjovi** [comment]
Now it's the perfect task and time tracking tool. ;)

**Comment by gkssjovi** [comment]
On the top there are "Tasks", "Projects" and "Calendar".
What the section projects is about?
Because I have associated some projects to the tasks, but that section in empty. Is that normal?

**Comment by kdheepak** [comment]
Can you share the output of `task summary`? Your issue might be related to this issue: https://github.com/kdheepak/taskwarrior-tui/issues/317

**Comment by gkssjovi** [comment]
Here it is:
![Screenshot 2021-11-09 at 21 08 03](https://user-images.githubusercontent.com/5613459/140988619-0a4d1d47-3930-4beb-be19-aaed59cd493b.png)

**Comment by kdheepak** [comment]
Hmm. That shouldn’t be empty then. I’m not sure what’s going on there.

**Comment by gkssjovi** [comment]
I don't know if the `taskrc` configuration file has something to do with this.

**Comment by kdheepak** [comment]
If you can share your configuration or reproduce the issue with the test data, I might be able to figure out what is going on. But otherwise, you’ll just have to wait till I resolve the linked issue.

**Comment by gkssjovi** [comment]
I can also run the test if you tell me what lines should I uncomment.

Here is the taskrc file.
[taskrc.txt](https://github.com/kdheepak/taskwarrior-tui/files/7507388/taskrc.txt)

**Comment by kdheepak** [comment]
You'll need to uncomment this line:

https://github.com/kdheepak/taskwarrior-tui/blob/c61288a017b3609a12fa8413d095c5f4d85d145e/src/pane/project.rs#L230

And the run the following:

```
cargo test -- --nocapture test_project_summary
```

Then there's this function that does the parsing. You'll have to add `dbg!(&contains_avg_age)` or dbg!(&line) in the function to figure out what is going on.

**Comment by gkssjovi** [comment]
But I did not know where to put the dbg!...
This is without that.

`
running 1 test
[src/pane/project.rs:236] &app.projects.rows = []
[src/pane/project.rs:237] &app.projects.list = []
test pane::project::tests::test_project_summary ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 9 filtered out; finished in 0.62s
`

**Comment by gkssjovi** [comment]
```
running 1 test
[src/pane/project.rs:157] &contains_avg_age = false
[src/pane/project.rs:157] &contains_avg_age = false
[src/pane/project.rs:237] &app.projects.rows = []
[src/pane/project.rs:238] &app.projects.list = []
test pane::project::tests::test_project_summary ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 9 filtered out; finished in 0.65s
```

**Comment by kdheepak** [comment]
Can you add `dbg!(&header)` to this line?

https://github.com/kdheepak/taskwarrior-tui/blob/c61288a017b3609a12fa8413d095c5f4d85d145e/src/pane/project.rs#L128

**Comment by gkssjovi** [comment]
```
running 1 test
[src/pane/project.rs:128] &header = "------- --------- ------- -------- ------------------------------"
[src/pane/project.rs:159] &contains_avg_age = false
[src/pane/project.rs:128] &header = "------- --------- ------- -------- ------------------------------"
[src/pane/project.rs:159] &contains_avg_age = false
[src/pane/project.rs:239] &app.projects.rows = []
[src/pane/project.rs:240] &app.projects.list = []
test pane::project::tests::test_project_summary ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 9 filtered out; finished in 0.95s
```

**Comment by kdheepak** [comment]
I think I understand what is happening. Last question, can you add `dbg!(&lines)` to the same line?

**Comment by gkssjovi** [comment]
```
running 1 test
[src/pane/project.rs:128] &header = "------- --------- ------- -------- ------------------------------"
[src/pane/project.rs:129] &lines = [
    "------- --------- ------- -------- ------------------------------",
    "Inbox           3      1d      57% =================",
    "Soncid          4      7d      20% ======",
    "2 projects",
    "",
]
[src/pane/project.rs:160] &contains_avg_age = false
[src/pane/project.rs:128] &header = "------- --------- ------- -------- ------------------------------"
[src/pane/project.rs:129] &lines = [
    "------- --------- ------- -------- ------------------------------",
    "Inbox           3      1d      57% =================",
    "Soncid          4      7d      20% ======",
    "2 projects",
    "",
]
[src/pane/project.rs:160] &contains_avg_age = false
[src/pane/project.rs:240] &app.projects.rows = []
[src/pane/project.rs:241] &app.projects.list = []
test pane::project::tests::test_project_summary ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 9 filtered out; finished in 0.80s
```

**Comment by gkssjovi** [comment]
It is showing something

**Comment by kdheepak** [comment]
Can you add `dbg!(&lines);` immediately after this line?

https://github.com/kdheepak/taskwarrior-tui/blob/c61288a017b3609a12fa8413d095c5f4d85d145e/src/pane/project.rs#L125

**Comment by gkssjovi** [comment]
![Uploading Screenshot 2021-11-09 at 21.46.31.png…]()
```
running 1 test
[src/pane/project.rs:126] &lines = [
    "------- --------- ------- -------- ------------------------------",
    "Inbox           3      1d      57% =================",
    "Soncid          4      7d      20% ======",
    "2 projects",
    "",
]
[src/pane/project.rs:129] &header = "------- --------- ------- -------- ------------------------------"
[src/pane/project.rs:160] &contains_avg_age = false
[src/pane/project.rs:126] &lines = [
    "------- --------- ------- -------- ------------------------------",
    "Inbox           3      1d      57% =================",
    "Soncid          4      7d      20% ======",
    "2 projects",
    "",
]
[src/pane/project.rs:129] &header = "------- --------- ------- -------- ------------------------------"
[src/pane/project.rs:160] &contains_avg_age = false
[src/pane/project.rs:240] &app.projects.rows = []
[src/pane/project.rs:241] &app.projects.list = []
test pane::project::tests::test_project_summary ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 9 filtered out; finished in 0.62s
```

**Comment by kdheepak** [comment]
Thanks for the detailed reports. Can you try the latest `main` branch again? I believe this should be fixed now.

**Comment by gkssjovi** [comment]
```
The application panicked (crashed).
  byte index 17 is out of bounds of `2 projects`
in src/pane/project.rs, line 145
thread: main
```

**Comment by gkssjovi** [comment]
```
running 1 test
[src/pane/project.rs:130] &lines = [
    "Project Remaining Avg age Complete 0%                        100%",
    "------- --------- ------- -------- ------------------------------",
    "Inbox           3      1d      57% =================",
    "Soncid          4      7d      20% ======",
    "2 projects",
]
[src/pane/project.rs:133] &header = "Project Remaining Avg age Complete 0%                        100%"
[src/pane/project.rs:136] &contains_avg_age = true
thread 'pane::project::tests::test_project_summary' panicked at 'byte index 17 is out of bounds of `2 projects`', src/pane/project.rs:150:33
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
test pane::project::tests::test_project_summary ... FAILED

failures:

failures:
    pane::project::tests::test_project_summary

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 9 filtered out; finished in 0.24s

error: test failed, to rerun pass '--bin taskwarrior-tui'
```

**Comment by kdheepak** [comment]
Can you try the most recent version of the `main` branch again? I think this should be fixed now.

**Comment by gkssjovi** [comment]
Yep, everything is working fine now. Thank you.
![Screenshot 2021-11-09 at 22 23 15](https://user-images.githubusercontent.com/5613459/140998946-c5db0e68-b6ea-436a-9f7b-f388ec971f41.png)

**Comment by kdheepak** [comment]
Thanks for patiently debugging.

**Comment by kdheepak** [comment]
I made a new release with this fix: https://github.com/kdheepak/taskwarrior-tui/releases/tag/v0.14.11

**Comment by gkssjovi** [comment]
I'm glad everything is working fine ;) 
Thank you
