### ISSUE TITLE
Filter Tasks by Tags Crashes `taskwarrior-tui`

### ISSUE THREAD

**Issue by Neurognostic** [kdheepak/taskwarrior-tui#31]
**Describe the bug**

After pressing <kbd>/</kbd> to edit the filter, if <kbd>+</kbd> (or a few other non-alphanumeric characters) is typed before typing an alphanumeric character–such as with `+TAG` filters–then `taskwarrior-tui` crashes with an unhelpful error message.

```log
[taskwarrior-tui error]: Failed to create a Task from JSON. Please report as a github issue on https://github.com/kdheepak/taskwarrior-tui
```

Strangely, if I first type the name of the tag then move the cursor to the beginning of the tag name and preprend a `+`, the filter works as expected.

**To Reproduce**

```shell
mkdir ~/taskwarrior-tui-debug
cd ~/taskwarrior-tui-debug
touch ./taskrc
TASKDATA=. TASKRC=./taskrc taskwarrior-tui
```

Then type <kbd>/</kbd>,<kbd>+</kbd>.

**Environment:**

- Operating System: Linux
- Installation: [`aur/taskwarrior-tui-git`](https://aur.archlinux.org/packages/taskwarrior-tui-git)
- taskwarrior-tui version:

```bash
taskwarrior-tui --version
taskwarrior-tui 0.8.10
``` 

**Using master @** 6fc4f8a325ee83d811bcd91b449d6da66b9c27ec
- task version:

```shell
task --version
2.5.1
```

**Additional context and information**

Asciinema demo:
[![asciicast](https://asciinema.org/a/bvyNlQuuf6NNkY4hwZTcZ4Iv2.svg)](https://asciinema.org/a/bvyNlQuuf6NNkY4hwZTcZ4Iv2)

Setting `RUST_BACKTRACE=1` did not produce any additional verbosity.

**Comment by kdheepak** [comment]
Thanks for such a detailed bug report! And nice find, sheesh. It only occurs if you type `+` and wait a few milliseconds. If `taskwarrior-tui` doesn't try to refresh the tasks when `+` is the only filter string, it works fine. 

Anyway, this is fixed in https://github.com/kdheepak/taskwarrior-tui/releases/tag/v0.8.12! And I'm working on better error messages in future releases.

**Comment by Neurognostic** [comment]
I can confirm it is working as expected now. Great work!
