### ISSUE TITLE
deleted tasks are still visible

### ISSUE THREAD

**Issue by alexzanderr** [kdheepak/taskwarrior-tui#311]
![image](https://user-images.githubusercontent.com/54772464/139898285-484e5341-12b9-4d65-887a-54587e1f2c1d.png)

how can i make the completed tasks to disappear?

before it worked. didnt modify any settings. i suddenly got this annoying situation.

is there a setting to disable viewing completed tasks inside taskwarrior-tui?

i looked through settings, both in taskwarrior and taskwarrior-tui, couldnt find anything related.

**Comment by kdheepak** [comment]
Which version of `taskwarrior` are you using?

**Comment by alexzanderr** [comment]
```
❱  task --version
2.6.0
```

**Comment by alexzanderr** [comment]
ooh. maybe got updated from my package manager?

**Comment by kdheepak** [comment]
Thanks for sharing the version. What is the filter that you are using? If you use `status:pending` it shouldn't show completed tasks. Make sure you are on the latest version of `taskwarrior-tui`.

**Comment by alexzanderr** [comment]
```
╭Filter Tasks─────────────────────────────────────────────────────────────────────────╮
│status:pending -WAITING limit:page                                                   │
╰─────────────────────────────────────────────────────────────────────────────────────╯
```

**Comment by alexzanderr** [comment]
```
❱  taskwarrior-tui --version
taskwarrior-tui 0.13.34
```
is this the latest?

**Comment by kdheepak** [comment]
No it is not, try https://github.com/kdheepak/taskwarrior-tui/releases/tag/v0.14.6.

**Comment by alexzanderr** [comment]
oh. i will try.

**Comment by kdheepak** [comment]
Is this still an issue?

**Comment by alexzanderr** [comment]
yes it is. i havent tested. i moved to `todo_list` which is made in rust. you can close this if you want.

**Comment by kdheepak** [comment]
Thanks for replying. I'm not able to replicate this issue, so I'll go ahead and close it. If you decide to use `taskwarrior-tui` again, feel free to comment here and I'll reopen, or open a new issue.
