### ISSUE TITLE
Discuss AUR package maintenance

### ISSUE THREAD

**Issue by kdheepak** [kdheepak/taskwarrior-tui#33]
Hi @loki7990 and @orhun, Thanks for maintaining `taskwarrior-tui-git` and `taskwarrior-tui` respectively on AUR! I appreciate it. 

I wanted to check if you were interested in continuing to maintain it? I'm setting up github actions to push releases to various places (github release, homebrew, snap, etc) and I could do the same for AUR. It would make releases available faster for users and decrease burden for you. I don't know if AUR has a way to add me as a maintainer to that package as well or something similar.

Thoughts? I'm happy to let you continue maintaining it if you'd like.

**Comment by orhun** [comment]
Hey Dheepak!
I'm maintaining [taskwarrior-tui-bin](https://aur.archlinux.org/packages/taskwarrior-tui-bin/) and [taskwarrior-tui](https://aur.archlinux.org/packages/taskwarrior-tui/) packages along with my [other AUR packages](https://github.com/orhun/PKGBUILDs). I check the new releases [daily](https://github.com/orhun/dotfiles/blob/master/bash/.bash_aliases#L21) and generally I'm notified through email before.
It's not a problem for me to continue maintaining those 2 packages but I can add you as a co-maintainer if you're planning to set up a CD. Or I can disown the package for you to adopt completely.
I'd like to continue maintaining but those are the other 2 ways that we can go.
Tell me what you think :)

**Comment by kdheepak** [comment]
Ah, I missed `taskwarrior-tui-bin`. Great job maintaining all those packages! 

If you can add me as a co-maintainer that would be perfect. I would like to make sure CD covers all distributions eventually. 

Question: I'm not familiar with AUR conventions. Why do you need two repositories? Couldn't you move the `taskwarrior-tui-bin` contents into `taskwarrior-tui`? I expect users will try something like `pacman -S taskwarrior-tui`. This will compile from source, correct? Whereas `pacman -S taskwarrior-tui-bin` will install precompiled binaries?

**Comment by loki7990** [comment]
Hello @kdheepak! I'm more than happy to hand over `taskwarrior-tui-git` to you if you want! Or add you as a co-maintainer instead! My only concern is whether you have access to an Arch setup. When tinkering with `PKGBUILD`, you'll want to be able to test them out with something like `namcap` before pushing changes.  Although a git package doesn't have any real maintenance to it, it pulls in the current git commit from this repository at install time. You'll have to manually reinstall it if you want to update it. Git packages are great for testing out a latest feature that's not in a current release.

To answer the questions for @orhun, the difference between `taskwarrior-tui` and `taskwarrior-tui-bin` is that the former requires compiling the current release while the latter installs a pre-compiled binary to save some time.

@orhun I saw your comment on the AUR! I'm hoping to find time before too long to add your suggestions.

**Comment by kdheepak** [comment]
Thanks for the reply @loki7990! If you can add me as a co-maintainer that would be great! I've added a github action to create the AUR package (but not push it anywhere). It seems to run successfully:

https://github.com/kdheepak/taskwarrior-tui/runs/1320579190

And, I do have access to an Arch setup, although it has been a while since I have booted the machine 😅. I'm hoping to automate as much as possible though. It would be nice if when a release is made here all packages are published to their respective locations automatically.

**Comment by orhun** [comment]
> Ah, I missed `taskwarrior-tui-bin`. Great job maintaining all those packages!
> 
> If you can add me as a co-maintainer that would be perfect. I would like to make sure CD covers all distributions eventually.

Sure thing! What's your AUR username?

> Question: I'm not familiar with AUR conventions. Why do you need two repositories? Couldn't you move the `taskwarrior-tui-bin` contents into `taskwarrior-tui`?

I guess @loki7990 answered that question very well.

> I expect users will try something like `pacman -S taskwarrior-tui`. This will compile from source, correct? Whereas `pacman -S taskwarrior-tui-bin` will install precompiled binaries?

Yes. But just to be clear, you cannot install AUR packages using `pacman`. [AUR](https://wiki.archlinux.org/index.php/Arch_User_Repository) is where the users contribute packages and these packages are mostly installed with [AUR helpers](https://wiki.archlinux.org/index.php/AUR_helpers) such as `yay`. Or you can clone the package repository and install it manually with `makepkg` like following:

```
git clone https://aur.archlinux.org/taskwarrior-tui.git && cd taskwarrior-tui && makepkg -si
```
On the other hand, packages in the [community](https://wiki.archlinux.org/index.php/Official_repositories#community) are maintained by [Trusted Users](https://wiki.archlinux.org/index.php/AUR_Trusted_User_Guidelines).
An AUR package is moved to community if it gets 10 votes on AUR and a Trusted User volunteers to maintain it.

With this being said, I might suggest you to remove `pacman -S` commands from README.md

> @orhun I saw your comment on the AUR! I'm hoping to find time before too long to add your suggestions.

Nice! You can also refer to one of my similar PKGBUILDs here: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=shy-git

> https://github.com/kdheepak/taskwarrior-tui/runs/1320579190

I had a CD workflow back in time when I was updating my 3 AUR packages with it. I'm shooting it in case you might wanna see: https://github.com/orhun/kmon/blob/2f4906da1a16c1a48e9aac6ba0bd39fea7de18b0/.github/workflows/cd.yml#L48

**Comment by kdheepak** [comment]
Thanks for the detailed comment! That explains a lot. 

I've created an AUR account, my username is the same as my username on github: [`kdheepak`](https://aur.archlinux.org/account/kdheepak/).

**Comment by orhun** [comment]
@kdheepak added you as co-maintainer. 🥂 
https://aur.archlinux.org/packages/taskwarrior-tui/
https://aur.archlinux.org/packages/taskwarrior-tui-bin/

**Comment by kdheepak** [comment]
Thank you!

**Comment by kdheepak** [comment]
I'll comment here and discuss with you first if and when I'm planning to make any changes.

**Comment by loki7990** [comment]
I've added you as a co-maintainer @kdheepak! Let me know if you want me to transfer full ownership.

**Comment by kdheepak** [comment]
Perfect! Again, I'll let you know here before I make any changes!

**Comment by kdheepak** [comment]
I'm currently building the AUR package on github actions, and can push from there directly. But since you use AUR more regularly, I'm sure you'll identify issues more readily than I will. If you ever tire of maintaining let me know! Thank you for your time and contributing to the open source community!
