### ISSUE TITLE
User pause while typing tag filter provokes error and blocking prompt, exits filter prompt

### ISSUE THREAD

**Issue by bradyt** [kdheepak/taskwarrior-tui#330]
Now that a larger issue at https://github.com/kdheepak/taskwarrior-tui/issues/320 is solved, we might see issues like the following trickle in as more subtle UX puzzles.

For taskwarrior-tui 0.14.11 and task 2.6.1, if I start to type a filter like with `/-foo`, then as I type that first minus sign, that is, with the following UI state:

```
╭Task|Projects|Calendar────────────────────────────────────────────────────────────────────────────╮
│  ID St Age  Description                                                                          │
│                                                                                                  │
│•  1 P  2min foo                                                                                  │
│                                                                                                  │
│                                                                                                  │
│                                                                                                  │
│                                                                                                  │
│                                                                                                  │
│                                                                                                  │
│                                                                                                  │
│                                                                                                  │
│                                                                                                  │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
╭Filter Tasks──────────────────────────────────────────────────────────────────────────────────────╮
│ -                                                                                                │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
```

If I pause for a tick or so, for example if I'm looking for the `f` key, then I see the following error:

```
╭Task|Projects|Calendar────────────────────────────────────────────────────────────────────────────╮
│  ID St Age  Description                                                                          │
│                                                                                                  │
│•  1╭Error───────────────────────────────────────────────────────────────────────────────────╮    │
│    │Running `"task" "rc.json.array=on" "rc.confirmation=off" "rc.report.all.filter=-"       │    │
│    │"export" "all"` failed (exit status: 2):                                                │    │
│    │                                                                                        │    │
│    │Configuration override rc.json.array=on                                                 │    │
│    │Configuration override rc.confirmation=off                                              │    │
│    │Configuration override rc.report.all.filter=-                                           │    │
│    │The expression could not be evaluated.                                                  │    │
│    │                                                                                        │    │
│    ╰────────────────────────────────────────────────────────────────────────────────────────╯    │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
╭Error─────────────────────────────────────────────────────────────────────────────────────────────╮
│Press ESC to return                                                                               │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
```

I can simply exit the error display, reenter filter prompt via `/` and continue typing `foo`, to make it `-foo`. Similar results for `+foo`, or pausing while deleting a tag filter.

This doesn't seem very severe, nor is it obvious to me how this could be improved. Curious if anyone can think of an elegant improvement.

I do see this easily comes from CLI task, with the following:

```
$ task rc.report.all.filter=- all
Configuration override rc.report.all.filter=-
The expression could not be evaluated.
```

Note, this does not occur if `task all` returns no tasks, that is, with a pristine setup.

Maybe there shouldn't be a blocking prompt for this? Just some indicator in the UI that the filter is currently invalid? Like replace the area that displays `task info` with that error message? Not that there shouldn't ever be a blocking prompt, for example if I press `/ - RET`, then I would finally get a blocking prompt upon `RET`.

**Comment by bradyt** [comment]
Asciinema recorded:

[![asciicast](https://asciinema.org/a/448093.svg)](https://asciinema.org/a/448093)

**Comment by kdheepak** [comment]
Thanks for the detailed issue. That is indeed annoying. A blocking prompt for that is definitely not ideal. I’ll change it to an indicator with a option for the user to open the error message pane.

**Comment by kdheepak** [comment]
This is partially fixed by the referenced PR. I'll make a release now since I don't want users upgrading to the latest version and having a poor experience.

**Comment by kdheepak** [comment]
This is partially resolved in https://github.com/kdheepak/taskwarrior-tui/releases/tag/v0.14.12. Currently, there's no pop up that shows the error, nor do I have a key binding in mind for what should show the error pop up. But the current command window's border will change to "red" (whatever your terminal theme's "red" is).

**Comment by bradyt** [comment]
Nice!

As for how to get the prompt, do you mean the prompt should be available somehow while the filter is invalid, but not necessarily available once filter is valid again? Why not just have `Enter` and `Esc` bring up prompt if pressed while filter is invalid?

Otherwise, maybe take ideas from GNU Readline? I think `Ctrl-g` is some sort of abort. Or `Ctrl-]` jumps to links in vim. `Enter` is a common idiom to view links. In Emacs, `Alt-.` jumps to definition. Though `Alt-.` is a bit different in GNU Readline.

**Comment by kdheepak** [comment]
> Why not just have Enter and Esc bring up prompt if pressed while filter is invalid?

I like this idea a lot!

**Comment by kdheepak** [comment]
I think your suggestion of using `Enter` to "dig" into the error feels really intuitive! I'm hoping it is easily discoverable. 

What I expect will happen is someone will type something that is invalid and hit `Enter`. The UI will update to "red". They'll probably hit `Enter` again (this is the part I'm concerned may not be discoverable). This will show the error pop up. If they press any key, they'll go back to the previous mode that they were in, and now can fix the error and hit `Enter` again.

I think that is intuitive. In the previous versions, when the user hit enter, they were immediately shown the error in the command prompt. This was more instant feedback, however only a single line and if they hit any key, they were sent back to the "report view". Meaning, they'd have to enter back into some action to try again. So overall, this should be a net improvement, even if it is one extra step to see the error.

**Comment by bradyt** [comment]
I tried building on `git checkout v0.14.13`, looks great. If filter border is red, Return shows error popup, Esc exits filter prompt.

**Comment by kdheepak** [comment]
Thanks for testing it!
