### ISSUE TITLE
Crash when filter is empty after an error

### ISSUE THREAD

**Issue by Petemir** [kdheepak/taskwarrior-tui#333]
Testing #330, I finally found the crash (or at least another one) I mentioned [here](https://github.com/kdheepak/taskwarrior-tui/issues/320#issuecomment-964543384). If the filter is set to an empty string after a filter error, the application crashes.

**To Reproduce**

- [ x  ] Reproducible using the test data located here: <https://github.com/kdheepak/taskwarrior-testdata/>

* Start Taskwarrior
* Write in the filter only a '-', in order to generate the error
* Access the filter again and then delete the whole string
* Press enter

**Environment (please complete the following information):**

- Operating System: Ubuntu 21.10
- Installation: Github Releases (AppImage)
- taskwarrior-tui version: v0.14.13
- task version: v2.6.1

**Additional context and information**
Crashlog and animation provided (for some reason it took me several times to provoke the crash).

[crashlog.txt](https://github.com/kdheepak/taskwarrior-tui/files/7511605/crashlog.txt)

![Peek 2021-11-10 10-43](https://user-images.githubusercontent.com/287105/141089863-bb43153f-280c-4cf0-bcbb-4953a23a178e.gif)

**Comment by kdheepak** [comment]
Oof. Thank you so much for reporting that, I don't know if I would have caught that, that one is nasty. I think this one should be resolved in the referenced PR.

**Comment by kdheepak** [comment]
This should be resolved in this release: https://github.com/kdheepak/taskwarrior-tui/releases/tag/v0.14.14
