### ISSUE TITLE
Filter / command history only access last item

### ISSUE THREAD

**Issue by Petemir** [kdheepak/taskwarrior-tui#336]
Hello,

I believe that at least from the last version of taskwarrior-tui the history is not working anymore. I can only access the current filter, not the ones before, and for the `add` command, I can also access only the last one.

Cheers!

**To Reproduce**

- [ x ] Reproducible using the test data located here: <https://github.com/kdheepak/taskwarrior-testdata/>

* Open taskwarrior
* Change the filter (`/`) to something else
* Go to the filter edit (`/`) again and try to access the initial filter with the arrow keys
* It only shows the current filter.

**Environment (please complete the following information):**

- Operating System: Linux (Ubuntu 21.10)
- Installation: Github AppImage Release
- taskwarrior-tui version:  v0.14.14
- task version: v2.6.1

**Additional context and information**
(when I am seemingly doing nothing, I am actually pressing the arrow keys :)) 

![Peek 2021-11-24 12-10](https://user-images.githubusercontent.com/287105/143227906-eed953c3-e358-48c8-88dd-e28fbd7be22b.gif)

**Comment by kdheepak** [comment]
That's annoying. Thanks for opening a detailed issue report btw! This is fixed in the referenced PR.
