### ISSUE TITLE
Autocomplete not working

### ISSUE THREAD

**Issue by kofm** [kdheepak/taskwarrior-tui#337]
**Describe the bug**

When I try to use autocompletion e.g. in filter, I get the autocompletion menu but when I press enter the menu is closed but no autocompletion is performed

- Press / to activate the filter
- Start typing (e.g. 'pri' for priority)
- Press TAB to bring the autocomplete menu
- Press ENTER to select the desired menu item

![twtui](https://user-images.githubusercontent.com/12545394/143423507-4a119d44-1b05-443f-b630-ac782928d2e4.gif)

**Environment:**

- Operating System: Linux
- Installation: arch
- taskwarrior-tui version: 0.14.14
- task version: 2.6.1

Thanks for this awesome tool!!

**Comment by kdheepak** [comment]
Thanks for opening a detailed issue report! This is fixed in the referenced PR.

**Comment by kofm** [comment]
Thank you very much!
