### ISSUE TITLE
Shrotcuts for scrolling task details view

### ISSUE THREAD

**Issue by k-sriram** [kdheepak/taskwarrior-tui#339]
**Description**
`taskwarrior-tui` shows details about the selected task in another panel below it. However, if the description is too long, it cuts off whatever isn't shown within the panel.

**Solution**
Add keyboard shortcuts which scroll the task details panel. This would enable the user to be able to view the entire information in the details panel.

**Comment by kdheepak** [comment]
This exists already, right? 

https://github.com/kdheepak/taskwarrior-tui/blob/b3683ae548873238c27efc10850174b69b4f597a/docs/keybindings.md#L55-L57

What happens when you try using <kbd>Ctrl e</kbd> and <kbd>Ctrl y</kbd>?

**Comment by k-sriram** [comment]
Yeah this exists. Sorry

**Comment by kdheepak** [comment]
No worries! It’s easy to miss :)
