### ISSUE TITLE
Snap does not run

### ISSUE THREAD

**Issue by kwoot** [kdheepak/taskwarrior-tui#34]
$ snap  install  taskwarrior-tui --edge
error: The publisher of snap "taskwarrior-tui" has indicated that they do not consider this revision
      to be of production quality and that it is only meant for development or testing at this
      point. As a consequence this snap will not refresh automatically and may perform arbitrary
      system changes outside of the security sandbox snaps are generally confined to, which may put
      your system at risk.

      If you understand and want to proceed repeat the command including --devmode; if instead you
      want to install the snap forcing it into strict confinement repeat the command including
      --jailmode.

$ snap  install  taskwarrior-tui --edge --jailmode
taskwarrior-tui (edge) 0+git.9f0c048 from kdheepak installed

$ taskwarrior-tui 
ERROR: ld.so: object 'libgtk3-nocsd.so.0' from LD_PRELOAD cannot be preloaded (failed to map segment from shared object): ignored.
[taskwarrior-tui error]: No such file or directory (os error 2). Please report as a github issue on https://github.com/kdheepak/taskwarrior-tui

Done as requested in last line :-)

I do not exclude the possibility that it is something I should fix on my end....
$ locate libgtk3-nocsd.so.0
/usr/lib/i386-linux-gnu/libgtk3-nocsd.so.0
/usr/lib/x86_64-linux-gnu/libgtk3-nocsd.so.0

**Comment by kdheepak** [comment]
So strange! Why is it trying to load `libgtk`?

**Comment by kwoot** [comment]
Tried: $ export GTK3_NOCSD_IGNORE=1
No difference.

**Comment by kwoot** [comment]
$ taskwarrior-tui which
ERROR: ld.so: object 'libgtk3-nocsd.so.0' from LD_PRELOAD cannot be preloaded (failed to map segment from shared object): ignored.
error: Found argument 'which' which wasn't expected, or isn't valid in this context

USAGE:
    taskwarrior-tui [OPTIONS]

For more information try --help
$ which taskwarrior-tui 
/snap/bin/taskwarrior-tui
$ ldd /snap/bin/taskwarrior-tui
	linux-vdso.so.1 (0x00007ffe58f71000)
	libgtk3-nocsd.so.0 => /usr/lib/x86_64-linux-gnu/libgtk3-nocsd.so.0 (0x000014eaa5716000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x000014eaa56f3000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x000014eaa5501000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x000014eaa54fb000)
	/lib64/ld-linux-x86-64.so.2 (0x000014eaa6dfa000)

Hm, so assuming the error can be ignored, still the program does not continue to the gui phase.

**Comment by kwoot** [comment]
When I do a strace the last lines are weird:

umask(000)                              = 002
openat(AT_FDCWD, ".", O_RDONLY|O_NOFOLLOW|O_CLOEXEC|O_PATH|O_DIRECTORY) = 3
fstat(3, {st_mode=S_IFDIR|0755, st_size=20480, ...}) = 0
chdir("/")                              = 0
getresuid([1000], [1000], [1000])       = 0
getresgid([1000], [1000], [1000])       = 0
**write(2, "need to run as root or suid", 27need to run as root or suid) = 27**
write(2, "\n", 1

**Comment by kdheepak** [comment]
I'm looking into it. I think there must be a way to tell snap that this is a binary command line tool and doesn't need to link with `libgtk3`.

**Comment by kdheepak** [comment]
It might have to do with the confinement. I've changed it to strict now.

**Comment by kdheepak** [comment]
Would you be able to try again now? I've pushed a new release from `master`: https://github.com/kdheepak/taskwarrior-tui/runs/1319577790

**Comment by kwoot** [comment]
$ sudo snap remove taskwarrior-tui
taskwarrior-tui verwijderd
$ unset GTK3_NOCSD_IGNORE
$ snap  install  taskwarrior-tui --edge --jailmode
taskwarrior-tui (edge) 0+git.9f0c048 van kdheepak geïnstalleerd
$ taskwarrior-tui 
ERROR: ld.so: object 'libgtk3-nocsd.so.0' from LD_PRELOAD cannot be preloaded (failed to map segment from shared object): ignored.
[taskwarrior-tui error]: No such file or directory (os error 2). Please report as a github issue on https://github.com/kdheepak/taskwarrior-tui

Hm, no such file. Let's have a look....

umask(000)                              = 002
openat(AT_FDCWD, ".", O_RDONLY|O_NOFOLLOW|O_CLOEXEC|O_PATH|O_DIRECTORY) = 3
fstat(3, {st_mode=S_IFDIR|0755, st_size=20480, ...}) = 0
**chdir("/")**                              = 0
getresuid([1000], [1000], [1000])       = 0
getresgid([1000], [1000], [1000])       = 0
write(2, "need to run as root or suid", 27need to run as root or suid) = 27
write(2, "\n", 1
)                       = 1
exit_group(1)                           = ?
+++ exited with 1 +++

Why does he want to chdir? Hm, it was there also the first time.

ldd:
$ ldd  /snap/bin/taskwarrior-tui
	linux-vdso.so.1 (0x00007ffefb3f3000)
	libgtk3-nocsd.so.0 => /usr/lib/x86_64-linux-gnu/libgtk3-nocsd.so.0 (0x00001458587ef000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00001458587cc000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00001458585da000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00001458585d4000)
	/lib64/ld-linux-x86-64.so.2 (0x0000145859ed3000)

$ snap info taskwarrior-tui
name:      taskwarrior-tui
summary:   A terminal user interface for taskwarrior
publisher: kdheepak
store-url: https://snapcraft.io/taskwarrior-tui
license:   unset
description: |
  A terminal user interface for taskwarrior to manage your tasks efficiently.
commands:
  - taskwarrior-tui
snap-id:      3YTCTSyWeVFbxhPTK39gSH8bxGgMYqb1
tracking:     latest/edge
refresh-date: today at 10:20 CET
channels:
  latest/stable:    –                                
  latest/candidate: –                                
  latest/beta:      –                                
  **latest/edge:      0+git.9f0c048 2020-10-27 (2) 1MB devmode**
installed:          0+git.9f0c048            (2) 1MB jailmode
$ snap refresh taskwarrior-tui
snap "taskwarrior-tui" has no updates available
$ taskwarrior-tui 
ERROR: ld.so: object 'libgtk3-nocsd.so.0' from LD_PRELOAD cannot be preloaded (failed to map segment from shared object): ignored.
[taskwarrior-tui error]: No such file or directory (os error 2). Please report as a github issue on https://github.com/kdheepak/taskwarrior-tui

**Comment by kdheepak** [comment]
> snap install taskwarrior-tui --edge --jailmode

Ah, I pushed to stable now. Sorry. Try with the following:

> snap install taskwarrior-tui

**Comment by kwoot** [comment]
$ snap install taskwarrior-tui
error: snap "taskwarrior-tui" is not available on stable but is available to install on the
       following channels:

       edge       snap install --edge taskwarrior-tui

       Please be mindful pre-release channels may include features not completely tested or
       implemented. Get more information with 'snap info taskwarrior-tui'.
 
$ snap info  taskwarrior-tui
name:      taskwarrior-tui
summary:   A terminal user interface for taskwarrior
publisher: kdheepak
store-url: https://snapcraft.io/taskwarrior-tui
license:   MIT
description: |
  A terminal user interface for taskwarrior to manage your tasks efficiently.
snap-id: 3YTCTSyWeVFbxhPTK39gSH8bxGgMYqb1
channels:
  latest/stable:    --                               
  latest/candidate: --                               
  latest/beta:      --                               
  latest/edge:      0+git.9f0c048 2020-10-27 (2) 1MB devmode

**Comment by kdheepak** [comment]
Can you try again now? I had to change some settings on my snapcraft.io account. You should be able to see stable releases now.

**Comment by kwoot** [comment]
$ snap info  taskwarrior-tui
name:      taskwarrior-tui
summary:   A terminal user interface for taskwarrior
publisher: kdheepak
store-url: https://snapcraft.io/taskwarrior-tui
license:   MIT
description: |
  A terminal user interface for taskwarrior to manage your tasks efficiently.
snap-id: 3YTCTSyWeVFbxhPTK39gSH8bxGgMYqb1
channels:
  latest/stable:    0+git.bad83ca 2020-10-28 (6) 1MB -
  latest/candidate: ^                                
  latest/beta:      ^                                
  latest/edge:      0+git.9f0c048 2020-10-27 (2) 1MB devmode

**Comment by kwoot** [comment]
$ snap install taskwarrior-tui
taskwarrior-tui 0+git.bad83ca from kdheepak installed

$ taskwarrior-tui 
ERROR: ld.so: object 'libgtk3-nocsd.so.0' from LD_PRELOAD cannot be preloaded (failed to map segment from shared object): ignored.
[taskwarrior-tui error]: No such file or directory (os error 2). Please report as a github issue on https://github.com/kdheepak/taskwarrior-tui

$ snap list
Name                     Version                     Rev    Tracking       Publisher          Notes
taskwarrior-tui          0+git.bad83ca               6      latest/stable  kdheepak           -

**Comment by kdheepak** [comment]
I spent a few hours experimenting with this. From what I can tell, snap is a confined environment and in `taskwarrior-tui` I'm calling `taskwarrior` as a child process and it appears snap doesn't like that. I _think_ I need to set it to `classic` confinement mode for this to work, but that has triggered a manual review at the snap store. I wasn't getting any libgtk issues though, so I don't know why you were seeing that.

I don't own an Ubuntu machine, and had to use a VM to set up snap in Ubuntu. But I believe snapcraft doesn't work in a VM. So I'm been going through the painful process of pushing to github, github actions pushing to snapstore, making it a stable release, downloading and testing. I've tried all sorts of options in the `snapcraft.yaml` (which you'll see in the git history) but to no avail. I'm going to post on their forum to see if they have recommendations for this use case. 

Until then, please use a different mode of installation. I've temporarily [removed `snap` instructions](https://github.com/kdheepak/taskwarrior-tui/commit/68fa9ecfaea059117432cd3f2c87169c889c15e4) from the README. I will revert this commit once I figure out what is going on.

**Comment by kwoot** [comment]
Completely understandable. If I can find some free time this weekend I will try to look at this myself. Would be my first steps in snap also so don't get your hopes up :-). Anyway, thanks for all your effort!

**Comment by kdheepak** [comment]
Thanks for offering to look into it!

**Comment by kdheepak** [comment]
After reading more documentation and some forum threads, I believe that taskwarrior needs to be bundled with taskwarrior-tui. So I've added that to the snap as well. It fails to detect `task` as an `app` though.

https://github.com/kdheepak/taskwarrior-tui/runs/1328102292#step:5:5166

I think if we figure out this issue everything should work.

**Comment by kdheepak** [comment]
These are the lines are causing the issue: https://github.com/kdheepak/taskwarrior-tui/blob/44e44591d2ab59f1dabd9af3f8dc8e3c6e038217/snap/snapcraft.yaml#L26-L27

**Comment by kdheepak** [comment]
![Screen Shot 2020-10-30 at 11 24 31 PM](https://user-images.githubusercontent.com/1813121/97771884-1ff80100-1b07-11eb-9118-349fc6040d1f.png)

I finally got it working!

**Comment by kdheepak** [comment]
If you are still having issues feel free to reopen.

**Comment by kwoot** [comment]
Hi! First; thanks for all your hard work.
Yes, it runs! But unfortunately I see no data at all. Maybe the taskwarrior-tui uses his own data store?
Ah, yes. It stores it in its own directory snap/taskwarrior-tui/
Hm, using two data stores is not a wise thing to do.
I could symlink one to the other I guess.
I wonder how other tools manage this?

**Comment by kdheepak** [comment]
Yeah, I'm not sure how other tools manage this. Happy to make changes to the snap to improve it if you have suggestions. There is a "layout" feature for snaps that might be relevant.

**Comment by kwoot** [comment]
According to https://snapcraft.io/docs/snap-layouts using the /home locations is not possible.
There are some pointers in https://forum.snapcraft.io/t/how-can-i-use-snap-when-i-dont-use-home-user/3352/34 but I am not sure if there isn't a more easy way to do this. Seems to me that a snap should be able to access data somewhere in a users homedir. Maybe $HOMEDIR is all it needs.

**Comment by kdheepak** [comment]
I believe the recommendation is to use the location that snap provides for configuration files:

https://forum.snapcraft.io/t/use-of-home-and-network-plugs/2587/28

Even $HOME is remapped inside a snap. I can add a command line option to print out the location of the `.taskrc` file, but that's about the best we can do we I'm afraid.
