### ISSUE TITLE
Add scheduled column

### ISSUE THREAD

**Issue by woodsp** [kdheepak/taskwarrior-tui#344]
**Description**

I wish outputs displayed `scheduled` dates. 

With a .taskrc containing

> report.next.columns=id,description,due.relative,scheduled.relative,priority
> report.next.filter=status:pending

running `task next` correctly displays all five columns, including both `due` and `scheduled` dates.  Taskwarrior-tui does not create a `scheduled` column.

**Additional context**

Operating system is OSX running task 2.6.1 and taskwarrior-tui 0.16.0 installed via homebrew.

Related to #224

**Comment by kdheepak** [comment]
Thanks for opening the issue! I've fixed it in the `main` branch. I'll make a new release some time next week. If you wish to try it out now, you can either build from source or use the precompiled binary from github actions.

**Comment by kdheepak** [comment]
https://github.com/kdheepak/taskwarrior-tui/actions/runs/1550540214#artifacts has a link here: https://github.com/kdheepak/taskwarrior-tui/suites/4582031548/artifacts/123437320

**Comment by woodsp** [comment]
Fantastic.  Thanks for the quick modification, and for the great tool!

**Comment by kdheepak** [comment]
Thanks for opening an issue!
