### ISSUE TITLE
No visible tasks in UI

### ISSUE THREAD

**Issue by bartenbach** [kdheepak/taskwarrior-tui#346]
**Describe the bug**
Opening the program results in no tasks and no errors.
![image](https://user-images.githubusercontent.com/572337/145698895-e16117d4-ff8e-4c57-82aa-aaed7198580e.png)

**To Reproduce**
I have no idea how to reproduce this. I can view tasks using taskwarrior and VIT normally.

**Environment (please complete the following information):**
Linux
Cargo
taskwarrior-tui 0.5.3
task 2.6.1
taskrc: https://github.com/bartenbach/dotfiles/blob/master/.config/task/taskrc

Using default next report results in the same behavior.

**Comment by kdheepak** [comment]
Hmm. Can you check the logs to see what might be going on?

**Comment by kdheepak** [comment]
Can you also share the output of `task summary`?

**Comment by bradyt** [comment]
> taskwarrior-tui 0.5.3

@kdheepak did you notice the version? Presumably you don't want to chase bugs on 0.5.3.

**Comment by kdheepak** [comment]
Oops! Thanks for catch that @bradyt!

@bartenbach can you try again with the latest version? https://github.com/kdheepak/taskwarrior-tui/releases/tag/v0.16.1  

This one is not on crates.io, so you’ll have to install from the git source or download a precompiled binary.

**Comment by bartenbach** [comment]
Nice, latest works!
![image](https://user-images.githubusercontent.com/572337/145700272-1c6de15f-635e-4fc9-9049-28d7647f17c4.png)
Thanks!
