### ISSUE TITLE
Question - how to set visible columns

### ISSUE THREAD

**Issue by sagiegurari** [kdheepak/taskwarrior-tui#347]
cool tool.
I have a question, by default i'm seeing id, age, description, urg
i would like to add tag and project, but didn't find any doc on how to do that.
i do see in your demos that its possible, so would love to know how.

**Comment by kdheepak** [comment]
If you add the following to your `.taskrc` file, it should show all these columns if there's corresponding data for the column.

```
report.next.columns=id,start.age,entry.age,depends,priority,project,tags,recur,scheduled.countdown,due.relative,until.remaining,description.truncated_count,urgency
```

i.e. it'll only show tag and project if you have a task that contains a tag or project.

**Comment by sagiegurari** [comment]
thanks. figured its TUI specific config

**Comment by kdheepak** [comment]
This is `taskwarrior` configuration. `taskwarrior-tui` tries to show the same columns as `taskwarrior`. So however you configure `taskwarrior` is the same way you can configure `taskwarrior-tui`.

**Comment by sagiegurari** [comment]
didn't work for me, but i'm using an env var to specify the taskrc location (TASKRC env).
would that cause an issue?

**Comment by kdheepak** [comment]
Do the tag and project columns show up in `taskwarrior` when you run it from the command line?

**Comment by kdheepak** [comment]
Can you try using https://github.com/kdheepak/taskwarrior-testdata and see if that works?

```
export TASKRC=`pwd`/tests/data/.taskrc
export TASKDATA=`pwd`/tests/data/.task
export TASKWARRIOR_TUI_CONFIG=`pwd`/tests/data/.config
export TASKWARRIOR_TUI_DATA=`pwd`/tests/data/.data
export TASKWARRIOR_TUI_LOG_LEVEL=debug
```

Using an environment variable shouldn't be the issue. I do it all the time. The above is what I use for testing.

**Comment by sagiegurari** [comment]
strange its not working for me. 
did the following:

```console
mkdir -p ./tests/data/ &&  git clone git@github.com:kdheepak/taskwarrior-testdata.git ./tests/data/

export TASKRC=`pwd`/tests/data/.taskrc
export TASKDATA=`pwd`/tests/data/.task
export TASKWARRIOR_TUI_CONFIG=`pwd`/tests/data/.config
export TASKWARRIOR_TUI_DATA=`pwd`/tests/data/.data
export TASKWARRIOR_TUI_LOG_LEVEL=debug

task add test
task 1 modify project:test123

taskwarrior-tui
```

its opened, i see the task, but can't see the extra columns.

**Comment by kdheepak** [comment]
Does it work when you run `task`?

**Comment by sagiegurari** [comment]
yes. doing task list does show the extra columns like project for example

**Comment by kdheepak** [comment]
Can you check the logs to see if anything stands out? The logs are in the data folder but aren’t super detailed. If you build from source I can direct you on how to debug this.

**Comment by sagiegurari** [comment]
when i built from source it works well
before that i used the version using cargo install which didn't.
so as a workaround, i'll just use this version and replace it in the cargo/bin.

**Comment by kdheepak** [comment]
> when i built from source it works well

When you build from source, tags and projects show up in `taskwarrior-tui`?

The version from cargo install is super old.

**Comment by sagiegurari** [comment]
> When you build from source, tags and projects show up in taskwarrior-tui?

yes

> The version from cargo install is super old.

that explains it. maybe worth to publish it

**Comment by sagiegurari** [comment]
anyhow i installed via ```cargo install --path .``` and now all works well.
thanks a lot for the support and the tool.
