### ISSUE TITLE
Add scrollbar when not all the tasks fit into current window

### ISSUE THREAD

**Issue by vizcay** [kdheepak/taskwarrior-tui#348]
**Description**

When the task list is long, sometimes is difficult to grasp where you are positioned in the list vertically speaking.

**Solution**

Add scrollbar in the last char of the right when not all the tasks fit into current window. Personally, scrolling by clicking on it is not important at all, but yes visual indicator of relative position.

**Comment by kdheepak** [comment]
Awesome idea! Thanks for the suggestion! It'll be part of the next release.

**Comment by kdheepak** [comment]
It'll look something like this:

![image](https://user-images.githubusercontent.com/1813121/147841279-b21a01ba-e4d7-47eb-9fbc-5d3dedfbf872.png)

The scrollbar indicator's color and symbol are configurable too.

**Comment by vizcay** [comment]
@kdheepak looks great! Thanks

**Comment by kdheepak** [comment]
I made a new release with this feature: https://github.com/kdheepak/taskwarrior-tui/releases/tag/v0.17.0
