### ISSUE TITLE
Invalid dependencies break taskwarrior tui

### ISSUE THREAD

**Issue by PatrickDaG** [kdheepak/taskwarrior-tui#358]
**Describe the bug**

When `task sync` from an empty state the dependecy resolution seems to fail so task reports 0 as dependency. This get ignored from task itself but seems to completely break taskwarrior tui,

**To Reproduce**

Edit a task with

```bash
task edit 1
```
to read
```
# Name               Editable details
# -----------------  ----------------------------------------------------
# ID:                1
# UUID:              8e739c99-2ba5-47e6-85ab-27ff09dccecf
# Status:            Pending
# Mask:              
# iMask:             
  Project:           anything
# Separate the tags with spaces, like this: tag1 tag2
  Tags:              
  Description:       test
  Created:           2021-10-19 10:06:10
  Started:           
  Ended:             
  Scheduled:         
  Due:               
  Until:             
  Recur:             
  Wait until:        
# Modified:          2022-01-10 01:45:53
  Parent:            
# Annotations look like this: <date> -- <text> and there can be any number of them.
# The ' -- ' separator between the date and text field should not be removed.
# Multiline annotations need to be indented up to <date> (21 spaces).
# A "blank slot" for adding an annotation follows for your convenience.
  Annotation:        2022-01-10 01:51:07 -- 
# Dependencies should be a comma-separated list of task IDs/UUIDs or ID ranges, with no spaces.
  Dependencies:      0
# User Defined Attributes
  UDA priority:      
# End
```
task version: 2.6.1
taskwarrior-tui version: 0.17.0

**Comment by kdheepak** [comment]
Thanks for reporting! What happens when you run `task export` in this state? Also, you edit the task and change the dependencies to 0 to reproduce this? I’ll try it when I’m back at my computer.

**Comment by PatrickDaG** [comment]
This seems to be mostly a task problem which gets ignored there. When manually editing and trying to add dependency 0 it prints an error. The way I can reproduce it reliably is to add a task with dependency, sync it, then delete my local copy.
The next sync will then pull everything and fail to resolve dependecy, replacing them all with 0.
The problem seems to be task export as well because it adds a bracket in the depend.
```
"depends":["[\"7edc8ec4-7323-4c1f-b2a3-8ecf2bc2c9f3\"","\"866e9d00-f398-4d5c-9059-c2806ab3da13\"","\"8c4bdad7-0d1c-47d3-aafe-1c9fb979a23a\"","\"b8eabcbb-0e62-4ab0-b7f5-72d706ee9bd0\"","\"dc3586bf-2509-46d2-b272-f61d5b5d4ab1\"]"]
```
Since this seems to be far more of a task problem than related to the tui, feel free to close.

**Comment by PatrickDaG** [comment]
This seems to be related: https://github.com/GothenburgBitFactory/taskwarrior/issues/2689

**Comment by kdheepak** [comment]
I don’t use `task sync`, is there another way I can reproduce it? Can you reproduce it using the test data and share the .task folder? Maybe I can better convey the error message in `taskwarrior-tui`?

**Comment by bradyt** [comment]
@kdheepak I think it can look like this:

```json
[
{"id":1,"description":"foo","entry":"20220110T000000Z","modified":"20220110T000000Z","status":"pending","uuid":"6c160610-6839-11ec-9fff-69830ce81117","depends":["[\"75f5f8ee-da19-4d56-8e07-a1883dfed61c\"]"],"urgency":0},
{"id":2,"description":"bar","entry":"20220110T000000Z","modified":"20220110T000000Z","status":"pending","uuid":"75f5f8ee-da19-4d56-8e07-a1883dfed61c","urgency":0}
]
```

In particular, I think the `task sync` produces this part:

```json
"depends":["[\"75f5f8ee-da19-4d56-8e07-a1883dfed61c\"]"]
```

If I start with a new `HOME=/tmp/test` and run `task import bad.json`, then `taskwarrior-tui` displays zero tasks.

@PatrickDaG Do I understand correctly that an aspect of the issue above was that `taskwarrior-tui` displays zero tasks, like the following?

```
╭Task|Projects|Calendar────────────────╮
│                                      │
│                                      │
╰──────────────────────────────────────╯
╭Task not found────────────────────────╮
│                                      │
│                                      │
╰──────────────────────────────────────╯
╭Filter Tasks──────────────────────────╮
│status:pending -WAITING limit:page    │
╰──────────────────────────────────────╯
```

Whereas `task` still shows two tasks:

```
% task

ID Age  Description Urg 
 1 2h   foo            0
 2 2h   bar            0

2 tasks
There are 2 local changes.  Sync required.
```

**Comment by PatrickDaG** [comment]
That's exactly it. `task` seems to just ignore the dependencies or report 0, whereas `taskwarrior-tui` breaks and is empty, or when changing the filter it seemingly shows random task only.

**Comment by bradyt** [comment]
It occurred to me that replying with the contents of `task export > bad.json`, rather than the precise state of `~/.task/*.data` files, as you requested, may not be quite the same. But I did just check, and they are very much the same in this case, the only difference is `backlog.data` has a new sync key rather than a backlog of tasks.

In other words, I think importing the `bad.json` I described above, produces a faithful representation of the issue.

However, if it makes things simpler, here is the contents of my `~/.task/*.data` after `task sync`:

```
> for x in `find .task -name '*.data'`; do echo $x; cat $x; done
.task/pending.data
[description:"foo" entry:"1641772800" modified:"1641772800" status:"pending" uuid:"00000000-0000-0000-0000-000000000000"]
[dep_[\"00000000-0000-0000-0000-000000000000\"]:"x" depends:"&open;\\\"00000000-0000-0000-0000-000000000000\\\"&close;" description:"bar" entry:"1641772800" modified:"1641772800" status:"pending" uuid:"11111111-1111-1111-1111-111111111111"]
.task/completed.data
.task/backlog.data
22222222-2222-2222-2222-222222222222
.task/undo.data
time 1641772800
new [description:"foo" entry:"1641772800" modified:"1641772800" status:"pending" uuid:"00000000-0000-0000-0000-000000000000"]
---
time 1641772800
new [dep_[\"00000000-0000-0000-0000-000000000000\"]:"x" depends:"&open;\\\"00000000-0000-0000-0000-000000000000\\\"&close;" description:"bar" entry:"1641772800" modified:"1641772800" status:"pending" uuid:"11111111-1111-1111-1111-111111111111"]
---
```

And for anyone curious, here is the contents of `$TASKDDATA/orgs/<org>/users/<credentials key>/tx.data` at the Taskserver:

```
{"description":"foo","entry":"20220110T000000Z","modified":"20220110T000000Z","status":"pending","uuid":"00000000-0000-0000-0000-000000000000"}
{"description":"bar","entry":"20220110T000000Z","modified":"20220110T000000Z","status":"pending","uuid":"11111111-1111-1111-1111-111111111111","depends":["00000000-0000-0000-0000-000000000000"]}
22222222-2222-2222-2222-222222222222
```

**Comment by kdheepak** [comment]
Thanks for sharing the `pending.data` file with the bad data. I was able to reproduce this. 

Unfortunately running the following:

```
$ task rc.json.array=on rc.confirmation=off rc.report.next.filter='(status:pending or status:waiting)' export next
[
{"id":1,"description":"foo","entry":"20220110T000000Z","modified":"20220110T000000Z","status":"pending","uuid":"00000000-0000-0000-0000-000000000000","urgency":1.8},
{"id":2,"description":"bar","entry":"20220110T000000Z","modified":"20220110T000000Z","status":"pending","uuid":"11111111-1111-1111-1111-111111111111","depends":["[\"00000000-0000-0000-0000-000000000000\"]"],"urgency":1.8}
]
```

The best I can do is add a error prompt saying that this is not valid and cannot be parsed by `taskwarrior-tui`.

**Comment by kdheepak** [comment]
It should print out something like this now:

![Screen Shot 2022-01-11 at 2 46 41 PM](https://user-images.githubusercontent.com/1813121/149026483-95972b69-474e-49e6-a857-4e01c16297b3.png)

**Comment by kdheepak** [comment]
I made a new release that contains this feature / fix: https://github.com/kdheepak/taskwarrior-tui/releases/tag/v0.18.0
