### ISSUE TITLE
add more rows on the TUI to scroll on (more than 24). more means infinity.

### ISSUE THREAD

**Issue by alexzanderr** [kdheepak/taskwarrior-tui#360]
```shell
❱  taskwarrior-tui --version
taskwarrior-tui 0.17.0
```

please add more than 24 items on the screen when scrolling.
![image](https://user-images.githubusercontent.com/54772464/148829977-6f034175-f107-4537-955a-6821e80a7828.png)

in the pending.data there are more to display.
```shell
❱  ca taskdata/pending.data | wc -l
51
```

**Comment by kdheepak** [comment]
The number of rows depends on the filter though. If you empty the filter the UI have all 51 items? You’ll have to use <kbd>j</kbd> and  <kbd>k</kbd> to scroll past the visible list obviously.

**Comment by bradyt** [comment]
It seems as if `limit:page` results in 24. Regardless of toggling task info with `z`, or shrinking terminal text size.

**Comment by kdheepak** [comment]
You’ll have to remove `limit:page` from your `taskwarrior`’s default filter string or at the very least from `taskwarrior-tui`’s filter string.

**Comment by alexzanderr** [comment]
> The number of rows depends on the filter though. If you empty the filter (hit /, backspace all characters and hit enter) does the UI have all 51 items? You’ll have to use j and k to scroll past the visible list obviously.

i've used j and k and also arrows to scroll, the scroll its working, i know that you can go beyond "visible". but my point is when you are going beyond "visible" there is a also a limit for this beyond, limit to 24.

the UI cant have more than 24. even with or without the visibles

**Comment by alexzanderr** [comment]
btw. i `couldNT` find a task-warrior-tui config file example in the readme.

**Comment by kdheepak** [comment]
See https://github.com/kdheepak/taskwarrior-tui/issues/214

**Comment by alexzanderr** [comment]
yeees. its working. thanks a lot.

**Comment by alexzanderr** [comment]
for everyone who doesnt jump to another link to find solution:

you need to add this line in `.taskrc`
```
report.next.filter=status:pending
```

**Comment by kdheepak** [comment]
`taskwarrior-tui` doesn’t have a config file and everything is configured using `taskwarrior`’s `.taskrc`. That said, I’m open to improving the docs in any way you suggest.

**Comment by bradyt** [comment]
Hmm, maybe the third file `advanced.md` at https://github.com/kdheepak/taskwarrior-tui/tree/main/docs/configuration could be added to README and MkDocs website.

**Comment by alexzanderr** [comment]
> `taskwarrior-tui` doesn’t have a config file and everything is configured using `taskwarrior`’s `.taskrc`. That said, I’m open to improving the docs in any way you suggest.

then why do you have a --config flag for a config folder for task warrior TUI when you dont have any config files ?

```shell

❱  taskwarrior-tui --help
taskwarrior-tui 0.17.0
Dheepak Krishnamurthy <@kdheepak>
A taskwarrior terminal user interface

USAGE:
    taskwarrior-tui [OPTIONS]

OPTIONS:
    -c, --config <FOLDER>      Sets the config folder for 
                               taskwarrior

```

**Comment by kdheepak** [comment]
If you use 

```
uda.taskwarrior-tui.task-report.next.filter=status:pending
``` 

instead, it’ll use this as the filter for the tui and will still allow you to use the `limit:page` when you invoke taskwarrior from the terminal.

**Comment by alexzanderr** [comment]
> uda.taskwarrior-tui.task-report.next.filter=status:pending

where do i put this config ?

**Comment by kdheepak** [comment]
> where do i put this config ?

In your `.taskrc` file. 

> then why do you have a --config flag for a config folder for task warrior TUI when you dont have any config files ?

The main reason I added a `—config` flag was because homebrew required a test that the command line worked that wasn’t help or version. 

But going forward I imagine there’ll be some `taskwarrior-tui` configuration that will be required that won’t be in `.taskrc`. Just currently it is not used. I’m relying from my phone, apologies for the terseness.

**Comment by alexzanderr** [comment]
> The main reason I added a —config flag was because homebrew required a test that the command line worked that wasn’t help or version.

please rename that to `test-homebrew` or remove it. because its very confusing.

**Comment by alexzanderr** [comment]
and thanks a lot for support and your time!

**Comment by kdheepak** [comment]
I updated the help string to clarify that a little. I am planning to use the `--config` flag, so I don't want to rename it at this point.

**Comment by alexzanderr** [comment]
nice

**Comment by kdheepak** [comment]
I also updated the README.md with an example of a `.taskrc` that has `taskwarrior-tui` configuration, and I added more links to the configuration section. Thanks for the suggestion @bradyt!
