### ISSUE TITLE
Improve context switcher key actions

### ISSUE THREAD

**Issue by simonmeggle** [kdheepak/taskwarrior-tui#367]
Hi, 

imho the context switcher menu (`c`) behaves a little bit un-intuitive. 

Current behaviour: 
* (press `c` to open context switcher)
* press **arrow keys** to select context 
* press **ENTER** to activate context 
* press **Esc** to exit context switcher

Expected/improved behaviour:
* (press `c` to open context switcher)
* press **arrow keys`` to select **and activate** context => "live preview"
* press **ENTER** to **activate context** and **exit** context switcher

I think this would be more intuitive. I am glad to hear your thoughts. 
Thanks & Regards,
Simon

**Comment by kdheepak** [comment]
Thanks for opening an issue! I do like the idea. However, switching contexts lags the interface a little. I've implemented the feature but placed it behind an option that the user will have to opt in to.

```
uda.taskwarrior-tui.context-menu.select-on-move=true
```

This will be part of the next release.

**Comment by kdheepak** [comment]
I made a new release with this change: https://github.com/kdheepak/taskwarrior-tui/releases/tag/v0.18.0
