### ISSUE TITLE
Autocomplete won't work with spaces in project name

### ISSUE THREAD

**Issue by PatrickDaG** [kdheepak/taskwarrior-tui#369]
Thanks for the project it proves really helpful recently.

I have a few project names that have spaces in them. When autocompleting those there aren't any quotes surrounding the name so task only gets the first word as project name and ignores any following words, leading to not finding any tasks.

**Describe the bug**

**To Reproduce**
Add any task with a project that has space in its name.
```bash
task add project:"Test Project" "this task is invisible"
```
Now when opening `taskwarrior-tui` and using autocomplete while changing filter it will read
```bash
╭Task|Projects|Calendar────────────────────────────╮
│                                                  │
│                                                  │
│                                                  │
╰──────────────────────────────────────────────────╯
╭Task not found────────────────────────────────────╮
│                                                  │
│                                                  │
│                                                  │
│                                                  │
╰──────────────────────────────────────────────────╯
╭Filter Tasks────────────────────────────── 48 / 48╮
│status:pending project:Test Project               │
╰──────────────────────────────────────────────────╯
```
Hopefully this is fixed easily, if you're working on this part a nice quality of life update would be when autocompleting to insert a space afterwards.
- taskwarrior-tui --version: 0.17.0

- task version: 2.6.1

**Comment by kdheepak** [comment]
Thanks for opening an issue! I have fixed this in a PR, I'll make a new release shortly.

![Screen Shot 2022-01-11 at 12 35 12 PM](https://user-images.githubusercontent.com/1813121/149009432-952900db-63ae-4c5c-8aeb-f5caa12ee6d7.png)

**Comment by kdheepak** [comment]
I made a new release with this change: https://github.com/kdheepak/taskwarrior-tui/releases/tag/v0.18.0
