### ISSUE TITLE
Columns jump around with tasks with long project names and descriptions

### ISSUE THREAD

**Issue by javabird25** [kdheepak/taskwarrior-tui#37]
**Describe the bug**

Columns start to appear and disappear every second if there is a pending task with both long description and long project name.
The bug goes away if the terminal is wide enough to display all task columns such as urgency.

**To Reproduce**

1. Create a task with a long description and with a long project name:
```sh
$ task add project:`python -c 'print("a"*100)'` `python -c 'print("a"*100)'`
```
2. Make the terminal window narrow enough to hide the urgency column.

**Environment (please complete the following information):**

- Operating System: Linux
- Installation: github releases and arch
- taskwarrior-tui version: 0.8.5
- task version: 2.5.1

**Additional context and information**

![long-proj](https://user-images.githubusercontent.com/12773022/97775353-b6690880-1b81-11eb-9efb-30e02ae511ac.gif)

**Comment by kdheepak** [comment]
Thanks for the detailed bug report! I'm aware this is a issue. The current column spacing algorithm can handle any number of columns and any kind of columns that taskwarrior supports, and is better suited for the more common case (i.e. long descriptions with every other label being short). But the same spacing algorithm has issues when handling the edge cases like the one you shared. I think if I decide to handle just a subset of the columns that taskwarrior supports, implementing this becomes more straightforward. 

I agree though that this is annoying and this is a bug. I'll spend some time brainstorming ideas to deal with this.

**Comment by kdheepak** [comment]
Thanks again for reporting! This is fixed now!

**Comment by kdheepak** [comment]
Can you try the latest release when you get the chance? https://github.com/kdheepak/taskwarrior-tui/releases/tag/v0.8.14. Thanks!

**Comment by javabird25** [comment]
Awesome, the bug is gone now. :+1:
