### ISSUE TITLE
Parse error caused by copy of `all` report, alternatively, a report other than `all` lacking a filter

### ISSUE THREAD

**Issue by bradyt** [kdheepak/taskwarrior-tui#380]
- taskwarrior-tui 0.18.2, built from source, recent commit
- Taskwarrior 2.6.1, built from source at `develop` branch, recent commit

```
> mkdir /tmp/testing
> cd /tmp/testing
> HOME=$(pwd)
> task show report.all > .taskrc
```

I then edit .taskrc, adding only `copy_` and `=`, with the following result:

```
% cat .taskrc
report.copy_all.columns     = id,status.short,uuid.short,start.active,entry.age,end.age,depends.indicator,priority,project.parent,tags.count,recur.indicator,wait.remaining,scheduled.remaining,due,until.remaining,description
report.copy_all.context     = 1
report.copy_all.description = All tasks
report.copy_all.labels      = ID,St,UUID,A,Age,Done,D,P,Project,Tags,R,Wait,Sch,Due,Until,Description
report.copy_all.sort        = entry-
```

I then see the following issue:

```
% taskwarrior-tui -r copy_all
[taskwarrior-tui error]: Unable to parse `task show report.copy_all.filter`.

If you need additional help, please report as a github issue on https://github.com/kdheepak/taskwarrior-tui
```

If it helps, the output for that command is as follows:

```
% task show report.copy_all.filter

Config Variable Value
No matching configuration variables.
```

I think the output for `task show report.all.filter` is identical. Yet `taskwarrior-tui -r all` seems to works fine.

This may be related to https://github.com/kdheepak/taskwarrior-tui/issues/313. I thought maybe the fix for it would be a special case on `all`, but that doesn't seem to be the case. It seems only the unit test is a special case for `all`.

This doesn't seem severe, a quick fix is to put for example, `report.copy_all.filter=`.

**Comment by kdheepak** [comment]
I think I did this on purpose, and wanted users to explicitly add `report.{report_name}.filter={filter}` for any `report_name`, even if that meant `{filter}` was empty. Thoughts? I can remove this restriction if you think it makes sense and default to an empty string if it doesn't exist. The only drawback is that there wouldn't be a warning if `taskwarrior-tui` isn't able to get a filter string even the user specified it, it would silently fallback to an empty string. Maybe it is fine to have that behavior, since users would just report it in that case.

**Comment by bradyt** [comment]
> if `taskwarrior-tui` isn't able to get a filter string even the user specified it,

I'm not sure I understand this scenario.

**Comment by kdheepak** [comment]
If `taskwarrior-tui` isn't able to get a filter string when the user specified it, it's a bug in `taskwarrior-tui` and I thought that should be reported as early as possible. But I guess even in this scenario, defaulting to an empty string would convey to the user something is wrong. So I think you've convinced me / I've convinced myself that we can make this change.

**Comment by bradyt** [comment]
I guess I was trying to understand if getting no filter string after user has specified one would be specific enough to deliberately throw an exception somehow.

But I'm glad if I have one less surprise when using no explicit filter. Thank you!

**Comment by kdheepak** [comment]
I made a new release with this fix: https://github.com/kdheepak/taskwarrior-tui/releases/tag/v0.18.3
