### ISSUE TITLE
UI omits end date column

### ISSUE THREAD

**Issue by bradyt** [kdheepak/taskwarrior-tui#384]
Taskwarrior 2.6.1, taskwarrior-tui 0.18.3.

I created a report to view logged items, at .taskrc as follows:

```
% cat .taskrc
report.Log.columns     = end,description
report.Log.description = Log
report.Log.labels      = Done,Description
report.Log.sort        = entry+
report.Log.filter      = status:completed
```

When I run `taskwarrior-tui -r Log`, I expect to see two columns with the logged date and the description, but the end date column is completely omitted, and only the column of descriptions is seen.

I tried `M-x rgrep`'ing the source for `description`, this all seems to happen in `./src/task_report.rs`, in `get_string_attribute`. Looking at that, I wondered if `report.Log.columns = entry,description` would also not work. It looks like putting `entry`, rather than `entry.age`, would also be an omitted column. That seemed to confirm I was in the right place.

Looks like a bit of work, both to decide whether to allow more column types, then which ones, if more than one more, and then to go about implementing one more or even more of these. I hope this isn't just me, that you already wanted to add more columns, but just had found a convenient place to postpone implementing more.

**Comment by kdheepak** [comment]
Yes, these are not implemented yet. Can you try the referenced PR? I think there are more columns that might be necessary to implement for completeness, and this is currently "a very implement what is needed" kind of situation.

**Comment by bradyt** [comment]
Progress was made. Hmm. It looks like the `%d` of `%Y-%m-%d` was truncated somehow.

Here is the `taskwarrior-tui` result:

```
╭Task|Projects|Calendar────────────────────────────────╮
│Done       Description                                │
│                                                      │
│• 2021-01- one                                        │
│  2021-01- two                                        │
│  2021-01- three                                      │
│                                                      │
│                                                      │
│                                                      │
│                                                      │
│                                                      │
│                                                      │
╰──────────────────────────────────────────────────────╯
╭Filter Tasks──────────────────────────────────────────╮
│status:completed                                      │
╰──────────────────────────────────────────────────────╯
```

For comparison, here is the Taskwarrior result:

```
% task Log              

Done       Description
2021-01-01 one
2021-01-01 two        
2021-01-01 three

3 tasks
```

**Comment by kdheepak** [comment]
Yeah, I'm noticing a few other bugs / inconsistencies between `taskwarrior` and `taskwarrior-tui`! I'll have to look into it tonight.

**Comment by kdheepak** [comment]
I haven't checked for a comprehensive list of possible columns yet. At the very least, `end` should work now.
