### ISSUE TITLE
"project.not" isn't suggested in the autocomplete

### ISSUE THREAD

**Issue by ofirgall** [kdheepak/taskwarrior-tui#386]
**Describe the bug**

"project.not" isn't suggested

**To Reproduce**

Go to the filter input, type "project." hit <Tab>, no suggestions

**Environment:**

- Operating System: Linux
- Installation: github releases
- taskwarrior-tui version: 0.18.2
- task version: 2.6.1

**Comment by kdheepak** [comment]
It's being suggested for me fine:

<img width="390" alt="Screen Shot 2022-01-25 at 4 58 01 AM" src="https://user-images.githubusercontent.com/1813121/150973031-5c6b0419-0a02-483e-8566-6aae63cfa7d1.png">

Are you trying `project.` instead of `project:`?

**Comment by bradyt** [comment]
This might be relevant, from https://taskwarrior.org/support/faq.html#q14:

> Q: Why have attribute modifiers (`urgency.over:10`) rather than the more readable and algebraic form (`urgency>10`)?
> 
> Taskwarrior already supports both forms. The attribute modifier form is older and predates more complex filter support. The algebraic form requires that you escape any characters that the shell will otherwise interpret.
> 
> At some point the attribute modifier form will likely be deprecated. The algebraic form is already much more capable.
> 
> ```
> $ task help
> ...
> Attribute modifiers make filters more precise.  Supported modifiers are:
> 
>   Modifiers         Example            Equivalent           Meaning
>   ----------------  -----------------  -------------------  -------------------------
>                     due:today          due = today          Fuzzy match
>   not               due.not:today      due != today         Fuzzy non-match
>   before, below     due.before:today   due < tomorrow       Exact date comparison
>   after, above      due.after:today    due > tomorrow       Exact date comparison
>   none              project.none:      project == ''        Empty
>   any               project.any:       project !== ''       Not empty
>   is, equals        project.is:x       project == x         Exact match
>   isnt              project.isnt:x     project !== x        Exact non-match
>   has, contains     desc.has:Hello     desc ~ Hello         Pattern match
>   hasnt,            desc.hasnt:Hello   desc !~ Hello        Pattern non-match
>   startswith, left  desc.left:Hel      desc ~ '^Hel'        Beginning match
>   endswith, right   desc.right:llo     desc ~ 'llo$'        End match
>   word              desc.word:Hello    desc ~ '\bHello\b'   Boundaried word match
>   noword            desc.noword:Hello  desc !~ '\bHello\b'  Boundaried word non-match
> ...
> ```
> 
> See 'man task', for the `ATTRIBUTE MODIFIERS` and `EXPRESSIONS AND OPERATORS` sections.

It sort of looks like three degrees of freedom on completion, where completion shows multiple attribute keys, multiple attribute modifiers, and multiple attribute values. This looks like a difficult design decision, with likely not much precedence. Are there any apps, even outside of Taskwarrior ecosystem, that provide ideas towards such a design?

**Comment by kdheepak** [comment]
I didn't even know about these attribute modifiers! Thanks for sharing the link.

These more complex filters don't seem to work properly when passing them through from `taskwarrior-tui`'s command input. It appears rust's `Command` doesn't pass through everything you type, and I'm getting odd behavior when trying out the more complex examples.

Nevertheless, it should be easy to add the attribute modifier form to taskwarrior-tui's completion. I just have to make sure the precedence is sane. I think the `.modifiers` should show up only if you've typed a `.`, and the rest can remain the same.

**Comment by kdheepak** [comment]
I'm pretty sure I've got this working now:

![Screen Shot 2022-02-06 at 10 37 18 PM](https://user-images.githubusercontent.com/1813121/152730495-f0abd6b9-d710-44e6-a7f9-c15a68cc8233.png)
![Screen Shot 2022-02-06 at 10 37 35 PM](https://user-images.githubusercontent.com/1813121/152730497-44ce00d1-3a7c-4658-80d1-4df8d161cab8.png)
![Screen Shot 2022-02-06 at 10 37 53 PM](https://user-images.githubusercontent.com/1813121/152730498-cd75efed-d2c0-48e6-b82f-594e0a2a5dff.png)

**Comment by kdheepak** [comment]
This feature should be available in https://github.com/kdheepak/taskwarrior-tui/releases/tag/v0.19.0.

**Comment by ofirgall** [comment]
Hey, I just want to thank you personally, your quick replies and your quick
work is verry appreciated!

**Comment by kdheepak** [comment]
Thank you!
