### ISSUE TITLE
Error when compiling 0.18.5

### ISSUE THREAD

**Issue by CleanAir777** [kdheepak/taskwarrior-tui#390]
**Describe the bug**

I just downloaded the source code for 0.18.5 and am trying to build it with "cargo build --release"

It breaks with the following error message:

   Compiling clap_derive v3.0.0
error[E0658]: arbitrary expressions in key-value attributes are unstable
  --> /home/xxx/.cargo/registry/src/github.com-1ecc6299db9ec823/clap_derive-3.0.0/src/lib.rs:16:10
   |
16 | #![doc = include_str!("../README.md")]
   |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: see issue #78835 <https://github.com/rust-lang/rust/issues/78835> for more information

error: aborting due to previous error

For more information about this error, try `rustc --explain E0658`.
error: could not compile `clap_derive`

**To Reproduce**

- [ ] Reproducible using the test data located here: <https://github.com/kdheepak/taskwarrior-testdata/>

**Environment (please complete the following information):**

- Operating System:  Linux Mint
- Installation:  github release
- taskwarrior-tui version: 0.18.5

```bash
taskwarrior-tui --version
```

- task version: 2.6.1

```bash
task --version
```

**Additional context and information**

**Comment by kdheepak** [comment]
What version of rust are you using?

**Comment by kdheepak** [comment]
Clap's documentation says this: 

> We will support the last two minor Rust releases (MSRV, currently 1.54.0)

https://docs.rs/clap/latest/clap/

So that must be the problem.

**Comment by kdheepak** [comment]
I'm able to compile it fine using 1.58.1, so I'll close this issue.
