### ISSUE TITLE
Can't parse context with both project and tag in it

### ISSUE THREAD

**Issue by wrvsrx** [kdheepak/taskwarrior-tui#391]
**Describe the bug**

Can't parse context with both project and tag in it

**To Reproduce**

1. create a task with "tag:tag1" and "project:pro1"
2. define a context "con1" as "context.con1.read=project:pro1 tag:tag1"
3. open taskwarrior-tui and select context "con1"
4. there's nothing in the list

Here's two screenshots:
- When using no context
![图片](https://user-images.githubusercontent.com/42770726/151646751-a299e54d-bfca-46b5-8b0c-a2c96a040da4.png)
- When using context "con1"
![图片](https://user-images.githubusercontent.com/42770726/151646761-3579a4cc-eb35-4ad2-aad3-70dbec0e3d19.png)

**Environment (please complete the following information):**

- Operating System: Linux
- Installation: archlinux aur repo
- taskwarrior-tui version: 0.18.5
- task version: 2.6.1

**Comment by kdheepak** [comment]
Can you try making the context `context.con1.read="project:pro1 tag:tag1"`? i.e. add double quotes and see if it works? If it does, I'll make the appropriate change next week, I have other commitments this weekend.

**Comment by wrvsrx** [comment]
Adding quote makes the context invalid, which means it doesn't filter anything.

**Comment by kdheepak** [comment]
Okay thanks for checking I’ll look into it.

**Comment by kdheepak** [comment]
The problem appears to be that filters in taskwarrior seem to be sensitive to double quotes in a weird way.

```
$ task rc.verbose:override=false "project:pro1 tag:tag1" export                                                                                                                                                                                            
[
]

$  task rc.verbose:override=false project:pro1 tag:tag1 export                                                                                                                                                                                              
[
{"id":27,"description":"test","entry":"20220207T054616Z","estimate":"30","modified":"20220207T054616Z","project":"pro1","status":"pending","uuid":"8552980b-2025-4443-b24c-feda8fd3aa5f","tags":["tag1"],"urgency":2.8}
]
```

I'm looking into what is the best way to handle this.

**Comment by kdheepak** [comment]
This fix is available in https://github.com/kdheepak/taskwarrior-tui/releases/tag/v0.19.0
