### ISSUE TITLE
Context not switched when context contains no taks

### ISSUE THREAD

**Issue by CleanAir777** [kdheepak/taskwarrior-tui#392]
**Describe the bug**

I had a crash the other day, so I had to rebuild my task-warrior database, i.e. start from scratch by re-entering my tasks one by one. My .taskrc was still intact and contained al my definitions of contexts etc.

When I have e.g. context " work"  active, use my shortcut key to switch to context "home", it doesn't change any further. It took me a while to figure out this was caused by the fact that there where no tasks (yet) in this context. Using tasksh or task works well.

Trying to change context back to "work" or "none" does not work either.

**To Reproduce**

- [ ] Reproducible using the test data located here: <https://github.com/kdheepak/taskwarrior-testdata/>

**Environment (please complete the following information):**

- Operating System: Linux 
- Installation: github release 
- taskwarrior-tui version: 0.18.5

```bash
taskwarrior-tui --version
```

- task version: 2.6.1

```bash
task --version
```

**Additional context and information**

**Comment by kdheepak** [comment]
That’s odd. Can you reproduce it using the test data repo? Alternatively, can you share your .taskrc file?

**Comment by kdheepak** [comment]
I think I'm able to reproduce this but I'm not sure exactly what is going on yet. It appears to be related to shortcuts. Switching using the context switcher works fine. I'll look into it when I get the chance.

**Comment by kdheepak** [comment]
This fix is available in https://github.com/kdheepak/taskwarrior-tui/releases/tag/v0.19.0
