### ISSUE TITLE
Completed tasks are shown when filtering pending tasks in a context

### ISSUE THREAD

**Issue by Petemir** [kdheepak/taskwarrior-tui#397]
Hello once again :),

With the last update I am shown the completed tasks when I am filtering only by pending status in a specific context. I filled most of the information I could, let me know if there's any other info I can provide. Cheers!

**To Reproduce**

- [ x ] Reproducible using the test data located here: <https://github.com/kdheepak/taskwarrior-testdata/>

* In the test data environment, modify a task and add a tag (in my example, `+life`)
* Create a context which filters by that tag (in my example, my context filters by `+usi or +life or project:life or project:usi`
* Filter tasks with "status:pending -WAITING"
* Switch to the created context 
* Completed tasks are shown when only pending tasks should be

**Environment (please complete the following information):**

- Operating System: Linux
- Installation: Github releases
- taskwarrior-tui version: v0.19.0
- task version: 2.6.1

**Additional context and information**
![Peek 2022-02-07 16-57](https://user-images.githubusercontent.com/287105/152824255-6ee91c96-591d-4bdc-b032-75ba387a509b.gif)

**Comment by kdheepak** [comment]
Ugh sorry about the regression and thanks for the detailed issue. I think this is related to https://github.com/kdheepak/taskwarrior-tui/issues/391#issuecomment-1031102888. I need to find a way to handle both cases.

**Comment by kdheepak** [comment]
I don't understand why this happens but this appears to be the source of the problem:

```shell
$ # only shows pending
$ task rc.verbose:override=false "rc.report.next.filter=status:pending +life or +usi" export next  
[
{"id":20,"description":"new task","entry":"20200804T111805Z","estimate":"30","modified":"20220207T171457Z","status":"pending","uuid":"d63bb624-27f6-4ba5-bb3e-9eed3fb6f389","tags":["life"],"urgency":1.8}
]

$ # shows pending and completed
$ task rc.verbose:override=false "rc.report.next.filter=status:pending +usi or +life" export next 
[
{"id":20,"description":"new task","entry":"20200804T111805Z","estimate":"30","modified":"20220207T171457Z","status":"pending","uuid":"d63bb624-27f6-4ba5-bb3e-9eed3fb6f389","tags":["life"],"urgency":1.8},
{"id":0,"description":"Mark task as done using 'd'","end":"20220207T172345Z","entry":"20201021T065354Z","estimate":"30","modified":"20220207T172345Z","status":"completed","uuid":"88ff806a-f7f5-4107-90b4-8bc4a2c81657","tags":["life"],"urgency":1.8}
]
```

I know how to fix this but I'm not confident that I've tested all combinations of accepted inputs that the taskwarrior command line tool accepts.

**Comment by kdheepak** [comment]
This should work in https://github.com/kdheepak/taskwarrior-tui/releases/tag/v0.19.1.

**Comment by Petemir** [comment]
Great, thanks! Don't worry about the testing, when something comes up I'll let you know ;).
