### ISSUE TITLE
crash on windows 10

### ISSUE THREAD

**Issue by x1y9** [kdheepak/taskwarrior-tui#401]
- Operating System: windows 10
- Installation:  github
- taskwarrior-tui version: 0.19.1

When i run taskwarrior-tui, i get the following msg:

> thread panicked while processing panic. aborting.

**Comment by kdheepak** [comment]
Does it print a traceback or stacktrace?

**Comment by x1y9** [comment]
No stacktrace even i set the RUST_BACKTRACE and TASKWARRIOR_TUI_LOG_LEVEL.

But it's normal when I run with --help.

**Comment by kdheepak** [comment]
Can you check the log file?

**Comment by kdheepak** [comment]
Also, would it be possible to share a screenshot or the crash? Maybe it’ll provide some more context. 

Also, what version of taskwarrior are you using?

**Comment by kdheepak** [comment]
Also, can you run it with the flag `—data ./tmp` and share the contents of the `tmp` folder?

**Comment by kdheepak** [comment]
It should have given a different error in that case. I’m not sure what’s causing this crash. Try it with taskwarrior and let me know what happens. I don’t have windows so I can’t test.

**Comment by xarthurx** [comment]
@x1y9  There is no taskwarrior in Windows. You need to use WSL2 for that.

**Comment by x1y9** [comment]
@xarthurx ok, thanks, I close the issue.
