### ISSUE TITLE
case insensitive auto-completion 

### ISSUE THREAD

**Issue by xarthurx** [kdheepak/taskwarrior-tui#407]
**Current behaviour:**

Related to the discussion here:
https://github.com/kdheepak/taskwarrior-tui/issues/218#issuecomment-1043226479

When using `tab` for auto-completion, the current mechanism is case sensitive.
For instance, if there is a project `Abc` in the completion list, and after `project:` you type `a` and press `tab`, the project `Abc` will not come up.

**Expected behaviour:**

Make the auto-completion case-insensitive.

**Comment by kdheepak** [comment]
This should be available in https://github.com/kdheepak/taskwarrior-tui/releases/tag/v0.20.0
