### ISSUE TITLE
Projects page cannot display project name that contains `.`

### ISSUE THREAD

**Issue by xarthurx** [kdheepak/taskwarrior-tui#409]
**Describe the bug**

I have a project that has a name with the form "A.B". 
In the task page, everything works fine.
However, in the `Project` page, the TUI separate it into two different projects, as the `lecture.series` shown below:
![image](https://user-images.githubusercontent.com/1921878/155220073-a633bd06-495e-44cf-a132-23f3db6427d0.png)

1. add a task with a project name `A.B`.
2. check it in the `Project` page.

**Environment (please complete the following information):**

- Operating System:  Windows 
- Installation:  compilation from source
- taskwarrior-tui version: newest

```bash
taskwarrior-tui --version
```

- task version: newest

```bash
task --version
```

newest

**Comment by kdheepak** [comment]
Related to #317

**Comment by xarthurx** [comment]
So at the moment, the `.` is preserved for hierarchical projects?

**Comment by xarthurx** [comment]
`A.B` means sub-project `B` under `A`?

**Comment by kdheepak** [comment]
What is your output of `task summary`?

**Comment by xarthurx** [comment]
![image](https://user-images.githubusercontent.com/1921878/155222319-8ff6e4ae-77b3-44d7-bf9d-af517cdec84e.png)

Check here for `subproject`:
https://randomgeekery.org/post/2019/02/taskwarrior-projects/

I think it is a `taskwarrior` embedded setting?

**Comment by kdheepak** [comment]
It does appear to be so.
