### ISSUE TITLE
Due dates displayed wrongly

### ISSUE THREAD

**Issue by OnkV** [kdheepak/taskwarrior-tui#411]
**Describe the bug**

Shown due dates are one day behind the actual due dates.

Example: today is 2022-03-02.  My filter settings are `status:pending due:today`.  Taskwarrior-tui lists the tasks which are due today, but the dates in the "Due" column are all shown as 2022-03-01.
This also happens without using a "due:" filter.

**To Reproduce**

- [ ] Reproducible using the test data located here: <https://github.com/kdheepak/taskwarrior-testdata/>

No, there are no due dates in the test data.

Start the program, look at the due dates.

[Screenshot](https://cloud.acat.cc/index.php/s/kX1R9EI62e6wh0c)

**Environment (please complete the following information):**

- Operating System: Linux (Debian 11)
- Installation: github releases
- taskwarrior-tui version: 0.20.1
- task version: 2.6.1

**Additional context and information**

Date specific configuration:
```
dateformat=D.M.Y
dateformat.holiday=YMD
dateformat.report=D.M.Y
dateformat.annotation=D.M.Y
weekstart=Monday
displayweeknumber=yes
due=7
```

My task database is somewhat old (about 10 years) and large:
```
% task count
20026
```

**Comment by kdheepak** [comment]
Can you share your .taskrc’s columns?

**Comment by kdheepak** [comment]
I just added a task using `task add "test task" due:today` and using the following in my `.taskrc` file:

```
report.next.columns=id,start.age,entry.age,depends,priority,project,tags,recur,scheduled.countdown,due,until.remaining,description,ref,urgency
report.next.labels=ID,St,Age,Dep,P,Pro,Tag,Recur,Sch,Due,Until,Description,Ref,Urg
```

<img width="720" alt="Screen Shot 2022-03-02 at 1 19 52 PM" src="https://user-images.githubusercontent.com/1813121/156442992-4b75444c-6538-4ebc-893a-c2608bc366d3.png">

So I'm not able to replicate your issue.

**Comment by OnkV** [comment]
{{{
report.next.columns=id,project,priority,due,start.active,entry.age,description
report.next.labels=ID,Project,Pri,Due,Active,Age,Description
}}}

**Comment by OnkV** [comment]
I added a task with `task add "test task" due:today` and the result is the same.  Colum `Due` contains the value `2022-03-01`.

**Comment by OnkV** [comment]
Taskwarrior shows the correct date:
```
% task "test task"

ID  Due        Age  Description
380 02.03.2022 3min test task  

1 task
```

**Comment by kdheepak** [comment]
Can you run `task export` and share that with me? I just need the output of the task that is due today.  Also share the output of `date` when you run that.

**Comment by OnkV** [comment]
```
% task 0e53cd5a-2321-4599-8e0c-601fe4aec89c export
[
{"id":380,"description":"test task","due":"20220301T230000Z","entry":"20220302T204740Z","modified":"20220302T204740Z","status":"pending","uuid":"0e53cd5a-2321-4599-8e0c-601fe4aec89c","urgency":9.25493}
]

% date
Mi 02 Mär 2022 23:53:07 CET

% echo $LC_ALL
de_AT.UTF-8
```

**Comment by OnkV** [comment]
2022-03-01  23:00 -- timezone issue?

**Comment by kdheepak** [comment]
It might be related to that. It looks like this line:

https://github.com/kdheepak/taskwarrior-tui/blob/9517bc196660cef6dcb8a4ae578be39580af4841/src/task_report.rs#L228

is not converting the `v` to local time and then creating a `NaiveDateTime` object.

**Comment by kdheepak** [comment]
I have opened a PR that should resolve this. Would you be able to test it out?

**Comment by OnkV** [comment]
Sorry, I'm not a git / github user.  But if you can provide a branch containing the changes, I'll compile and test it.

**Comment by bradyt** [comment]
@OnkV I think this might work:

```
curl -L https://github.com/kdheepak/taskwarrior-tui/tarball/convert-to-local-time | tar zx
```

I just searched for, "how to download a github branch without git", so you might find better information than I did.

I determined it was the `convert-to-local-time` branch by navigating to the "Pull requests" tab, and visually scanning.

**Comment by OnkV** [comment]
I'm sorry to report that the bug is still there.

**Comment by kdheepak** [comment]
FWIW, the PRs / branches have artifacts: https://github.com/kdheepak/taskwarrior-tui/actions/runs/1925206144

You can download the zip file with a precompiled binary for your platform for a particular branch. 

Surprising that doesn’t work though! I need a reproducible test case on my end to debug further. I’ll try to look into this more over the weekend.

**Comment by bradyt** [comment]
I think I got a reproduce with:

```
export TZ=CET
task add foo due:today
taskwarrior-tui
```

**Comment by OnkV** [comment]
I'm in CET, which is UTC +1.

**Comment by kdheepak** [comment]
This should be resolved now! Thanks for reporting and thanks to @bradyt for sharing a reproducible case!

**Comment by kdheepak** [comment]
I made a new release with this fix: https://github.com/kdheepak/taskwarrior-tui/releases/tag/v0.21.0

**Comment by OnkV** [comment]
Great, thank you!
