### ISSUE TITLE
Ability to control refresh rate

### ISSUE THREAD

**Issue by whugoh** [kdheepak/taskwarrior-tui#416]
**Description**

Taskwarrior-tui seems to be refreshing the list of tasks at least every second. It looks like it has an impact on responsiveness of some action, and in my case, it's unnecessary: I tend to leave it running in the background, and use it just a few times a day. Right now, there are a *lot* of `task` calls happening without me looking at their output.

I'd be happy to have it automatically refresh every 10 minutes, or even just manually.

**Solution**

Add a config switch to control the auto-refresh rate, and maybe add a special value to turn it off altogether.

**Comment by kdheepak** [comment]
There's already an (undocumented) option for this. If you add the following to your `.taskrc` file:

```
uda.taskwarrior-tui.tick-rate=2500
```

`taskwarrior-tui` will refresh every 2500 millseconds, i.e. 2.5 seconds. You can set it to an arbitrarily large number and use `r` to do a manual refresh.
