### ISSUE TITLE
Tasks appear on incorrect days on the calendar

### ISSUE THREAD

**Issue by src52** [kdheepak/taskwarrior-tui#417]
**Describe the bug**

If you create a task that is due on a particular day with a time greater that 17:00, the calendar highlights the following day to indicate it's due date. 

**To Reproduce**

Create two tasks that have a color, due on the same day. One due before 17:00, and one after.

Create a task that is due at 16:59, "Test" due:2022-03-19T16:59, and check the calendar. The 19th should be highlighted to indicate it's due date.

Create another task that is due at 17:00, "Test" due:2022-03-19T17:00, and check the calendar. The 20th should now be highlighted instead of the 19th, even though it's due on the 19th.

**Additional context and information**

**Comment by bradyt** [comment]
I see same behavior with `TZ=America/Los_Angeles`.

**Comment by kdheepak** [comment]
Thanks for reporting and providing reproducible steps. I’ll have to look into this over the weekend.

**Comment by src52** [comment]
> I see same behavior with `TZ=America/Los_Angeles`.

It could be an issue related to that, yeah. That's the timezone I'm in.

**Comment by kdheepak** [comment]
I have a fix for this. 

However there are other places that use a timezone agnostic handling of `DateTime` including the `task-hookrs` library. I'll have to address that separately and I've created an issue to track that: #419.

**Comment by kdheepak** [comment]
I made a new release with this fix: https://github.com/kdheepak/taskwarrior-tui/releases/tag/v0.21.0
