### ISSUE TITLE
Show slightly more precise due date information in Task panel?

### ISSUE THREAD

**Issue by src52** [kdheepak/taskwarrior-tui#421]
**Description**

As a student who uses taskwarrior-tui to keep track of my upcoming assignments and exam dates, I often think it would be helpful to make the due date column slightly more precise. Specifically for due dates that fall within the 1d - 13d range (before it turns into 2w), it would be nice to be able to see how many hours are left at a glance

**Solution**

A togglable feature that modifies the due column to include the hours remaining, for all tasks due within 1 to 13 days.

For example, instead of showing 1d for the due date, it would show 1d1h, or 1d23h. The two dates are very different, yet are represented in the same way with the current implementation.

**Comment by kdheepak** [comment]
Is there a `taskwarrior` feature that does this or you just want `taskwarrior-tui` to handle this?

For example, this function handles the vague date time formatting:

https://github.com/kdheepak/taskwarrior-tui/blob/a3164b599056b0c6a1e7ad44905714886f3caa26/src/task_report.rs#L22-L47

And is called from here:

https://github.com/kdheepak/taskwarrior-tui/blob/a3164b599056b0c6a1e7ad44905714886f3caa26/src/task_report.rs#L225-L228

It would be trivial to add a new function like `more_precise_but_still_vague_format_date_time` and call it when matched with something like `due.relative-precise`, and if you used that option in your `.taskrc` file, it would do what you wanted.

But that would differ from how `taskwarrior` does it and I'm still trying to figure out how I feel about that. It would be ideal if `taskwarrior` implemented this feature first.

**Comment by kdheepak** [comment]
I see the value in this feature though. I've added it as a global configuration option. So it's not exactly "toggleable" the way you requested, but you can set it in your `.taskrc` once and it'll work for all vague date time representations in taskwarrior-tui:

`uda.taskwarrior-tui.task-report.date-time-vague-more-precise=false`

![Screen Shot 2022-03-20 at 3 42 41 PM](https://user-images.githubusercontent.com/1813121/159187156-cc902f27-8be9-4bea-b909-8b6b775a4dd9.png)

`uda.taskwarrior-tui.task-report.date-time-vague-more-precise=true`

![Screen Shot 2022-03-20 at 3 42 46 PM](https://user-images.githubusercontent.com/1813121/159187155-39027370-10db-4201-90a6-e5f7dd2e5bb8.png)

**Comment by bradyt** [comment]
Awesome!

Small nit: Taskwarrior displays dates more than 365 days away with one decimal, like `1.0y`, `1.1y`, etc.

**Comment by src52** [comment]
> I see the value in this feature though. I've added it as a global configuration option. So it's not exactly "toggleable" the way you requested, but you can set it in your `.taskrc` once and it'll work for all vague date time representations in taskwarrior-tui:
> 
> `uda.taskwarrior-tui.task-report.date-time-vague-more-precise=false`
> 
> ![Screen Shot 2022-03-20 at 3 42 41 PM](https://user-images.githubusercontent.com/1813121/159187156-cc902f27-8be9-4bea-b909-8b6b775a4dd9.png)
> 
> `uda.taskwarrior-tui.task-report.date-time-vague-more-precise=true`
> 
> ![Screen Shot 2022-03-20 at 3 42 46 PM](https://user-images.githubusercontent.com/1813121/159187155-39027370-10db-4201-90a6-e5f7dd2e5bb8.png)

Wow, this is great thanks! I really appreciate it!

**Comment by kdheepak** [comment]
This feature is available in https://github.com/kdheepak/taskwarrior-tui/releases/tag/v0.21.1.
