### ISSUE TITLE
More UI customization

### ISSUE THREAD

**Issue by fullstopslash** [kdheepak/taskwarrior-tui#425]
I may have missed some bits in the documentation, but the ability to customize the colors of the UI would be rather neat.  I also noticed there's a setting to change the scrollbar indicator, but not a setting to change the actual scrollbar. Either way, I simply adore this project, and it's an integral part of my workflow!

**Comment by kdheepak** [comment]
Thanks for the kind words. 

Can you elaborate on what you mean by change the actual scrollbar?  You can currently use this to change the indicator character and the foreground and background color:

```
uda.taskwarrior-tui.scrollbar.indicator=O
uda.taskwarrior-tui.style.report.scrollbar=red on blue
```

<img width="710" alt="Screen Shot 2022-03-21 at 9 49 32 PM" src="https://user-images.githubusercontent.com/1813121/159404247-faca413c-d916-4e00-9b31-72b314e7de25.png">

**Comment by kdheepak** [comment]
I've added customization for the "background area" of the scrollbar:

```
uda.taskwarrior-tui.scrollbar.area=I
uda.taskwarrior-tui.style.report.scrollbar.area=blue on red
uda.taskwarrior-tui.scrollbar.indicator=O
uda.taskwarrior-tui.style.report.scrollbar=red on blue
```

<img width="54" alt="Screen Shot 2022-03-21 at 10 03 52 PM" src="https://user-images.githubusercontent.com/1813121/159405735-5fa36043-3eec-4a3a-80c1-52638a0793f5.png">

**Comment by kdheepak** [comment]
This feature is available in https://github.com/kdheepak/taskwarrior-tui/releases/tag/v0.21.1.

**Comment by fullstopslash** [comment]
Oh wow!  I did not expect that kind of turn around on a comment!  You caught my meaning on the scrollbar settings!  I should have been more clear and specific.  I couldn't seem to find the settings for the top and bottom border colors, the colors of the separator if a task is zoomed, and so on.  Seriously though. Impressive turn around!
