### ISSUE TITLE
Document how to set context from tui shell

### ISSUE THREAD

**Issue by sdondley** [kdheepak/taskwarrior-tui#429]
See https://github.com/kdheepak/taskwarrior-tui/discussions/428 for details.

Stock config of zsh and taskwarrior.

**Environment (please complete the following information):**

- Operating System:  Mac 
- Installation: homebrew 
- taskwarrior-tui version: .21.1

2.6.2 TW.

**Comment by kdheepak** [comment]
It seems to be working for me:

https://user-images.githubusercontent.com/1813121/159824511-de66d4fc-0a59-4a65-9c74-7419c127481e.mov

Did you change the default tick rate?

**Comment by kdheepak** [comment]
Also the "subprocess" shell action calls `update(force=true)` if the subprocess was successful:

https://github.com/kdheepak/taskwarrior-tui/blob/d5fb99a8d7bdf99d806ae9dca0988a41b459cadd/src/app.rs#L2868-L2872

and that should definitely recalculate the contexts:

https://github.com/kdheepak/taskwarrior-tui/blob/d5fb99a8d7bdf99d806ae9dca0988a41b459cadd/src/app.rs#L1226

So something else is going on with your setup.

Can you fetch the latest `main` branch (I just pushed some debug statements) and try again with the following environment variables set:

```
export TASKWARRIOR_TUI_DATA=`path/of/your/choosing/.data
export TASKWARRIOR_TUI_LOG_LEVEL=debug
```

This should put a log file in the path defined in the first variable, and may contain some more useful information. You can also leave out the first environment variable and the program will use your default `data` folder but I'm not sure where exactly that is on your machine.

**Comment by sdondley** [comment]
Looks like you have confirmation turned off in the argument to TW. Went be too fast to see it, though.

**Comment by kdheepak** [comment]
Yes, if you don’t have confirmation turned off then taskwarrior will prompt you and this shell subprocess doesn’t support prompt inputs

**Comment by sdondley** [comment]
OK, this should definitely be documented. If it is, I can't find it.

**Comment by kdheepak** [comment]
I added some text here: https://kdheepak.com/taskwarrior-tui/faqs/

And the latest version of `taskwarrior-tui` will show "an error prompt" with more information about what happened when you ran the shell command.

I think there's a lot more I can do to improve documentation (https://github.com/kdheepak/taskwarrior-tui/issues/145, https://github.com/kdheepak/taskwarrior-tui/issues/427) and improve usability in this regard, but I'm pressed for spare time at the moment and for now this will have to do :)

**Comment by sdondley** [comment]
I get it. Believe me. Keep plugging. I'd help but I'm overextended myself.
