### ISSUE TITLE
Modifying a task changes the due time (Europe DST problem?)

### ISSUE THREAD

**Issue by Petemir** [kdheepak/taskwarrior-tui#432]
**Describe the bug**

Hello once again! I have a strange issue where the "Modify" prompt in some tasks changes the due time, forwarding it one hour. This issue doesn't happen at every task. My best guess so far, from what I saw on some of my tasks, is that it may happen in recurring tasks that had an occurrence somewhere before the European DST change (27/03/2021).

**To Reproduce**

- [?] Reproducible using the test data located here: <https://github.com/kdheepak/taskwarrior-testdata/>

Steps to reproduce the behaviour:

As I am unsure about the exact steps, this is a recurring task where the error happens; I got it from the file `pending.data`.

```
[description:"Check tolls" due:"1638172800" entry:"1637574207" mask:"XXXXXXXXXXXXXXXXXXXX" modified:"1649239954" project:"life.chores" recur:"weekly" rtype:"periodic" status:"recurring" tags:"alarm,life" tags_alarm:"x" tags_life:"x" uuid:"72e4580e-3a1e-4580-8936-ec0f0ae565c7" wait:"1638172800"]
```

As usual, let me know whatever else I can do to help with this.

**Environment (please complete the following information):**

- Operating System: Linux (K)Ubuntu 21.10
- Installation: github releases
- taskwarrior-tui version: v0.22.0
- task version: v2.6.1

**Additional context and information**
![Peek 2022-04-06 12-40](https://user-images.githubusercontent.com/287105/161957343-2e93463e-e3d4-4337-8014-18d51eb7cf9c.gif)

Thanks!

**Comment by kdheepak** [comment]
Thanks for reporting! That is super weird. That modify command is sent straight to `taskwarrior` as a `task modify ...` subprocess. 

Does the same thing happen when you run `task 53 modify due:'2021-11-29T10:00:00'` from the terminal, i.e. not inside `taskwarrior-tui`?

**Comment by Petemir** [comment]
No, the `task modify` command seems to work OK.

e.g.:
``$ task 53 modify due:'2021-11-29T10:00:00'
Modifying task 53 'Check tolls'.
Modified 1 task.

$ task 53
[...]
Due             2021-11-29 10:00:00
[...]
[last line:]
2022-04-08 10:58:11 Due changed from '2021-11-29 09:00:00' to '2021-11-29 10:00:00'.
```

I would expect, though, that the problem isn't the modify command that is sent, but how taskwarrior-tui prefills the modify command when entering the TaskModify mode. When I enter the modify task mode, that's when I see the mismatch between the current due date, and what TaskWarrior is about to send.

**Comment by kdheepak** [comment]
Ah, yes, you are right. I misunderstood. I'll look into this now.

**Comment by kdheepak** [comment]
I have a PR that fixes it by adding `±HH:MM` to the timestamp and taskwarrior accepts that format (https://taskwarrior.org/docs/dates.html) so that _should_ solve it. 

Would you be able to test it?

**Comment by Petemir** [comment]
I tested it with the appropriate change []().
<img width="483" alt="image" src="https://user-images.githubusercontent.com/287105/162436039-2fb9f46c-5f1f-4aa3-a43c-80c366d2624d.png">

It works (i.e., if I enter "TaskModify"  mode and press enter immediately, the due date doesn't change), but I have to say it is a bit confusing, i.e., I have 10:00 as base time, +02:00 as a timezone offset, yet the final time is 09:00:00 :grin: .

**Comment by kdheepak** [comment]
One thing that would help is if `taskwarrior` displayed times with the offset, i.e. if the task details showed `2021-11-29T09:00:00+01:00` that would make it clear as to what was going on.

**Comment by kdheepak** [comment]
I'll merge this PR, since the old behavior can result in unwanted outcomes but the new behavior is just confusing. I'm open to suggestions to improve this, and I'll look into incorporating `chrono_tz` to see if that helps.

**Comment by Petemir** [comment]
Ok! Yes, how you specified the problem is clear. I fear timezones are NP-complete :smile: ... 

I agree that having the offset after the time would make it as clear as  possible :). 

Thanks!

**Comment by kdheepak** [comment]
I've made a new release that fixes this: https://github.com/kdheepak/taskwarrior-tui/releases/tag/v0.23.0.

**Comment by Petemir** [comment]
@kdheepak Thanks! fyi, I have been noting some delay/freezing when modifying a task and saving the modifications. Perhaps it's only me, but just in case,,,

**Comment by kdheepak** [comment]
You’ve been noticing this delay with the new version?

**Comment by Petemir** [comment]
Yes. I have just checked v0.22.0 and it was definitely snappier than v0.23.0, it is still very subtle (probably half a second) but it caught my attention. Sadly I cannot make a peek recording for this as there would be no way to mark when I press the enter... perhaps I could record myself if you aren't experiencing this. Still, it could be just me.

**Comment by kdheepak** [comment]
Interesting. Thanks for reporting. I switched out the async runtime between v0.22 and v0.23 so I’m expecting there will be some issues there, but I didn’t notice this particular issue in my testing. Let me have a further look. If you would like to open a new issue to track this that’d be great. No need to provide a recording.

**Comment by kdheepak** [comment]
I think I figured out the issue. The task details view needs to be generated by calling subprocesses, and I prepopulate a hashmap with that information. However, in this rewrite I ended up accidentally doing that in serial instead of in a parallel manner.

This should be resolved in https://github.com/kdheepak/taskwarrior-tui/releases/tag/v0.23.1.

**Comment by Petemir** [comment]
Sorry, didn't make it in time to create the issue it seems. Now it's definitely better, thanks!

**Comment by Petemir** [comment]
Hello!

Just as an FYI, CEST (GMT+2) ended on October 30th and we changed to CET (GMT+1). My tasks moved from "+01:00" (perhaps they should have been set as +02:00?), to "+00:00". I have no idea if it was expected or not :rofl: , but just in case I am letting you know!

**Comment by Petemir** [comment]
Hello!

Just as an FYI, CEST (GMT+2) ended on October 30th and we changed to CET (GMT+1). My tasks moved from "+01:00" (perhaps they should have been set as +02:00?), to "+00:00". I have no idea if it was expected or not :rofl: , but just in case I am letting you know!

And in fact, if I now try to manually modify the tasks' timezone from "+00:00" to "+01:00", nothing happens, i.e., when I go to edit the task again it still shows "00:00".
