### ISSUE TITLE
crash when a column label contains a space

### ISSUE THREAD

**Issue by TheTaoOfPhil** [kdheepak/taskwarrior-tui#433]
**Describe the bug**
Consider the following report definition:

```
####################################################################################
########### CUSTOM REPORT: ZCTSK·
task config report.zctsk.description 'list of complex tasks'
task config report.zctsk.labels      'Ctsk-sort,Abv,Proj,Est,ID,Desc'
task config report.zctsk.columns     'sort_ctsk,ctsk_abbv,project,est_time,id,description.truncated_count'
task config report.zctsk.sort        'project+,ctsk_desc-,sort_ctsk+'
task config report.zctsk.filter      'projoect.has:0 status.not:completed status.not:deleted status.not:recurring limit:N'
########### END CUSTOM REPORT: ZCTSK·
####################################################################################
```

Note that the first column label hyphenates "Ctsk" and "sort".  I had to add that hyphen, because when the two words were separated by a space, using the report with the ``-r`` parameter (i.e., ``taskwarrior-tui -r zctsk``) resulted in the following error:

```
Backtrace omitted. Run with RUST_BACKTRACE=1 to display it.
Run with RUST_BACKTRACE=full to include source snippets.

The application panicked (crashed).
  index out of bounds: the len is 1 but the index is 1
in src/app.rs, line 1073
thread: main
```
The same result obtains when the space is between the end of the column label and the following comma.

**To Reproduce**

* Comprise a column label consisting of two (or more) words
* Separate the two (or more) words by spaces
* Attempt to use the report as an argument to ``taskwarrior-tui -r <report-name>``

Alternatively, introduce a space between a single-word column name and the following comma.
 
**Environment (please complete the following information):**

- Operating System: macos BigSur 11.5.2
- Installation:  homebrew 
- taskwarrior-tui version: 0.22.0
- task version: 2.6.2

**Additional context and information**

At the time that I figured this issue out, I had set ``RUST_BACKTRACE=1`` but did not realize
that the log file would be in ``$HOME/Library/Application Support/taskwarrior-tui`` per the instructions here (that 
detail does not appear to be documented in the documentation). But I think my description of the problem and the error report at the commandline are descriptive.

**A Question about Filters**

I have a question that is tangential to the above reported problem, but perhaps it's a feature request.

I am delighted with this tool. I had been considering developing something like it for myself, but I think this will meet my needs quite handily.  I will be making a number of aliases  to invoke ``taskwarrior-tui`` with the ``-r`` parameter for various reports. 

In ``task``, I am used to filtering the input to the report, as in ``task ctsk_abbv:rnxt zctsk``. I have for example an alias that invokes ``zctsk`` and parameterizes the filter (``task ctsk_abbv:${user_abbv} zctsk``) so I can easily narrow down my view of the tasks to just what I need. 

I tried doing this with the ``-r`` parameter (i.e., ``taskwarrior-tui -r ctsk_abbv:rnxt zctsk``), but got the error:

```
Found argument 'zcstk' which wasn't expected, or isn't valid in this context
```

I am hoping it is possible to do this but that I've just missed something somewhere in the docs (my apologies if it should have been obvious).

Many thanks for the great work on this tool!
--Phil

**Comment by kdheepak** [comment]
I've made a new release that should fix this: https://github.com/kdheepak/taskwarrior-tui/releases/tag/v0.23.0

Thanks for reporting the issue btw! With regards to your question, I don't think I fully follow it. Can you elaborate on what you mean by "alias that invokes `zctsk`"? Sorry about the delayed response to this, I've had a crazy few weeks.
