### ISSUE TITLE
[Question]: Changing title bar and 'Filter Tasks' bar color

### ISSUE THREAD

**Issue by lmburns** [kdheepak/taskwarrior-tui#441]
I've looked through the documentation on your website and I didn't see any setting which would allow for me to change the color of the bars on the top and bottom of the screen. The bars that I am talking about are these:

 Top one contains:
```
 Tasks   Projects   Calendar                                                                        [none]
```

And the bottom one contains:
```
Filter Tasks
```

These used to not be this way until one of the more recent updates.
If I did somehow miss the setting which corresponds to these, I'm sorry.

**Comment by kdheepak** [comment]
I think that doesn’t exist at the moment but it should be pretty straightforward to add. I’ll do it this week.

**Comment by lmburns** [comment]
Okay, I should've added a picture in my first comment. The reason is because after one of these updates, both of the bars have changed colors and are now white, when they used to not have a background. Something else I noticed is that the selected tab has a bold background (I have my terminal display bold as bright colors). So the selection part could be something else to add.
![2022-04-26_21-05](https://user-images.githubusercontent.com/44355502/165423495-00e32819-fa69-4b7a-bddc-d5810f10aaa7.png)

**Comment by kdheepak** [comment]
I've made a new release with this fix: https://github.com/kdheepak/taskwarrior-tui/releases/tag/v0.23.0 

If you add the following to your `~/.taskrc`:

```
uda.taskwarrior-tui.style.navbar=red on white
uda.taskwarrior-tui.style.command=red on white
```

you should see the colors change for the navbar and the command prompt respectively.
