### ISSUE TITLE
Unit tests are timing out (running for over 60 seconds)

### ISSUE THREAD

**Issue by orhun** [kdheepak/taskwarrior-tui#442]
**Describe the bug**

When I try to run tests:

```
running 7 tests
test config::tests::test_get_config_last_long_value ... ok
test config::tests::test_get_config_long_value ... ok
test config::tests::test_get_config_long_value_followed_by_default_value ... ok
test table::tests::table_invalid_percentages - should panic ... ok
test config::tests::test_colors ... ok
test app::tests::test_centered_rect ... ok
test app::tests::test_taskwarrior_tui has been running for over 60 seconds
```

And then I have to kill the process because it's hung.

**To Reproduce**

- [x] Reproducible using the test data located here: <https://github.com/kdheepak/taskwarrior-testdata/>

I ran into this issue while building taskwarrior `0.23.0` for Arch Linux. Reproducing steps are the same as I previously described in #277 (fetch the `PKGBUILD` & build in clean chroot) 

**Environment (please complete the following information):**

- Operating System: Arch Linux (clean chroot)
- Installation: from source
- taskwarrior-tui version:  `0.23.0` 
- task version: `2.6.2`

**Additional context and information**

I added some debug statements around the test case (`test_taskwarrior_tui`) and it hangs on this line:

https://github.com/kdheepak/taskwarrior-tui/blob/e4a33c1aebe574bbe2b30c0bb407ecded80bec79/src/app.rs#L3856

I deleted `#[tokio::test(flavor = "multi_thread", worker_threads = 4)]` attribute from the function and tried plain `#[tokio::test]` but then this time it was stuck after importing the tasks.

**Comment by kdheepak** [comment]
I switched from `async-std` to `tokio`, and I think what's happening here is that the individual test was still being run with one thread (???). I added a flag to prevent the "event loop" from being instantiated in the tests. I think this should resolve it. I made a new release with this change: https://github.com/kdheepak/taskwarrior-tui/releases/tag/v0.23.1

It'd be really nice to run tests on github actions, but unfortunately I'm getting errors saying resource not available. I might open a stackoverflow bounty for this if I'm not able to figure it out.

**Comment by orhun** [comment]
> I switched from `async-std` to `tokio`, and I think what's happening here is that the individual test was still being run with one thread (???). I added a flag to prevent the "event loop" from being instantiated in the tests. I think this should resolve it. I made a new release with this change: [`v0.23.1` (release)](https://github.com/kdheepak/taskwarrior-tui/releases/tag/v0.23.1)

All good now. I just updated the Arch package as well. Thanks for the explanation and quick fix/release! 🐻 

> It'd be really nice to run tests on github actions, but unfortunately I'm getting errors saying resource not available. I might open a stackoverflow bounty for this if I'm not able to figure it out.

Can you give more details about why you can't run test on CI? I think it should be fine and even more stable since it's an isolated environment. I might help about it.

**Comment by kdheepak** [comment]
It's a super weird issue that I've only seen occur on GitHub CI, and I believe it only started occurring after I introduced `async` code into the project. I made a PR where I commented the lines that bypass the CI. You should see the resource error show up in the following log:

https://github.com/kdheepak/taskwarrior-tui/runs/6201960675?check_suite_focus=true

The PR in question is here: https://github.com/kdheepak/taskwarrior-tui/pull/444

**Comment by kdheepak** [comment]
I posted an issue about it here: https://github.com/kdheepak/taskwarrior-tui/issues/445.
