### ISSUE TITLE
Undo the Undo

### ISSUE THREAD

**Issue by TornaxO7** [kdheepak/taskwarrior-tui#450]
**Description**

Sometimes I'm accidently hitting the `u` (the undo key) which undos (obviously) some stuff which shouldn't happen.

**Solution**

Anohter keybinding like on `U` which reverts the undo command.

**Additional context**

**Comment by kdheepak** [comment]
Thanks for making the feature request. Unfortunately, `taskwarrior` doesn't support "undoing" `task undo`. I do have plans to implement this though. One way to do this would be to store the `.task` folder as a backup, and revert to that on pressing `U`. 

Again, this might only happen after #349.

**Comment by maxdiebold-erg** [comment]
Although it's not very Vim-like, I would personally prefer a confirmation prompt in the meantime. It's a lot easier to accidentally press `u` twice than to type `task undo` twice.

**Comment by kdheepak** [comment]
@maxdiebold-erg I made a new release https://github.com/kdheepak/taskwarrior-tui/releases/tag/v0.25.2 that has the ability to set up prompt on pressing `u`. If you set it to `true`, you can press `u` twice to confirm the undo, similar to the prompts for delete and done.

**Comment by maxdiebold-erg** [comment]
Wow, that was fast. That helps a lot, thanks!

**Comment by TornaxO7** [comment]
I can close this issue for the time being
