### ISSUE TITLE
Calendar view doesn't show Monday as first day of week

### ISSUE THREAD

**Issue by neurosys** [kdheepak/taskwarrior-tui#452]
**Describe the bug**
Taskwarrior is configured to show Monday as first day of week. But taskwarrior-gui in calendar view shows Sunday as the first day.

![image](https://user-images.githubusercontent.com/299203/173789525-8018239b-21d3-47dc-8023-16e9d690efdc.png)

![image](https://user-images.githubusercontent.com/299203/173789807-be511a5f-6886-4501-8002-4d43ce895295.png)

**To Reproduce**

Set in .taskrc `weekstart=monday`
Run `task calendar` so you can see the configuration is ok and Monday is set as first day of week.
Run `taskwarrior-gui` and go to the calendar view where Sunday is displayed as the first day of week.

- Operating System: Mac (I think I've seen this on Linux as well)
- Installation: brew
- taskwarrior-tui version: v0.23.4

**Comment by kdheepak** [comment]
This is implemented in https://github.com/kdheepak/taskwarrior-tui/releases/tag/v0.23.6

Many thanks to @KohlJary!
