### ISSUE TITLE
Key binding for getting out of quotes on adding a task

### ISSUE THREAD

**Issue by mizzunet** [kdheepak/taskwarrior-tui#453]
**Description**

I need to add a task `Clean the floor priority:H`, for that we would,
1. Press `a`
2. It displays input field and cursor being inside quotes
3. We type `Clean the floor`
4. Press left key/Ctrl+F two times for moving cursor to type `priority:H`
This seems a bit hard/weird to do being a vim user.

**Solution**

It would quite handy to have, 
* a key binding for the cursor get out the quotes say Tab or Escape.

Thanks for this awesome project :heart:

**Comment by kdheepak** [comment]
Great!
