### ISSUE TITLE
How to access "Projects" and "Calendar" ?

### ISSUE THREAD

**Issue by LeNouveau** [kdheepak/taskwarrior-tui#457]
Hi, 

I updated to 0.23.4. 
Now, there are tabs "Projects" and "Calendar", but I did not succeed to select it. 
![image](https://user-images.githubusercontent.com/3670305/180205488-0d49cf00-cdc9-45d9-983e-9d4cc4c348f1.png)

What are those and how to access ?
(sorry for this stupid question ^^')

Regards,

**Comment by maxmahlke** [comment]
Those are different views, use `[` and `]` to move between them.

https://kdheepak.com/taskwarrior-tui/keybindings/

**Comment by LeNouveau** [comment]
It works. 
I did not understand those are views. 

Thank you !

**Comment by kdheepak** [comment]
Suggestions for better UX for this are welcome!
