### ISSUE TITLE
`[` and `]` could rotate between panes

### ISSUE THREAD

**Issue by XVilka** [kdheepak/taskwarrior-tui#459]
Currently, pressing `[` always stops at the **Tasks** pane, and `]` always stops at the **Calendar** pane no matter how many times you press them. I suggest allowing rotating, e.g., when `[` pressed while being on **Tasks**, it will jump to **Calendar**. Conversely, `]` would jump from **Calendar** to **Tasks**.

**Comment by kdheepak** [comment]
Thanks for opening an issue and making a suggestion! This feature will be available in https://github.com/kdheepak/taskwarrior-tui/releases/tag/v0.23.5.
