### ISSUE TITLE
Application crashes when I go to calendar

### ISSUE THREAD

**Issue by pianocomposer321** [kdheepak/taskwarrior-tui#474]
Hey, thanks for making this. I'm just testing it out, so I don't know if I'm doing something wrong or what's going on...

When I open the program, at first everything's fine. But then if I go to the Calendar view by hitting `]` twice, the app crashes:

```
Backtrace (most recent call first):
  File "<unknown>", line 0, in __libc_start_main

The application panicked (crashed).
  index out of bounds: the len is 6795 but the index is 6826
in /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tui-0.19.0/src/buffer.rs, line 297
thread: main
```

**Comment by kdheepak** [comment]
Can you share the full stacktrace?

**Comment by pianocomposer321** [comment]
How would I do that? The output I posted is all I get when I do `RUST_BACKTRACE=full taskwarrior-tui`.

**Comment by pianocomposer321** [comment]
Ok...so I just tried again and it worked...turns out it only happens when I run it in a tmux pane that's zoomed...

(tmux-leader z) -> error
(tmux-leader z again) -> fine

**Comment by pianocomposer321** [comment]
Oh wait, actually, it also happens when there's only one tmux pane. It does not happen when not in tmux.

**Comment by kdheepak** [comment]
Can you try the following:

```
export TASKWARRIOR_TUI_LOG_LEVEL=debug
export RUST_BACKTRACE=1
```

**Comment by pianocomposer321** [comment]
```
Backtrace (most recent call first):
  File "<unknown>", line 0, in start_thread_main
  File "<unknown>", line 0, in clone
The application panicked (crashed).
The application panicked (crashed).795 but the index is 6826
  called `Result::unwrap()` on an `Err` value: SendError(Closed)tui-0.19.0/src/buffer.rs, line 297
in src/event.rs, line 73
thread: tokio-runtime-worker
```

**Comment by kdheepak** [comment]
Hmm I think what’s happening is that when you use tmux zoom taskwarrior-tui doesn’t respond to the resize event. I’ll look into it.

**Comment by P4RK-J4EWOONG** [comment]
In my case I get this error message.
I get the error even when I'm not using tmux.

```
Backtrace omitted. Run with RUST_BACKTRACE=1 to display it.
Run with RUST_BACKTRACE=full to include source snippets.

The application panicked (crashed).
  called `Result::unwrap()` on an `Err` value: SendError(Closed)
in src/event.rs, line 73aches/Homebrew/cargo_cache/registry/src/github.com-1ecc6299db9ec823/tui-0.19.0/src/buffer.rs, line 297
thread: tokio-runtime-worker
```
