### ISSUE TITLE
Completed.data converted into binary file

### ISSUE THREAD

**Issue by Petemir** [kdheepak/taskwarrior-tui#478]
Hello! After some days off, I resumed my computer from sleep, went to taskwarrior-tui, tried to complete some tasks from the previous days, but they didn't appear as completed. Eventually I got an error and taskwarrior-tui crashed. As I run it on a standalone terminal window it closed as soon as it crashed so I couldn't save the log, but it briefly flashed something about seeing an empty line on completed.data. When I went to look that file, it was binary :open_mouth: . The file is around the size it should be (I have a smaller backup versioned), but it appears to my Linux system as binary.

Clearly, I don't have enough here to do any type of backtrace/debugging, I am not even sure if taskwarrior-tui may have been the problem (it's my only interface with taskwarrior, so I do think that it may have had something to do with it), so I expect this to be quickly closed. I am just signalling that this happened, and perhaps @kdheepak / anyone knows why/how the completed.data file has become a binary file. 

Thanks! And let me know if there's anyway I can help.

**Environment (please complete the following information):**

- Operating System: Linux, Ubuntu 22.04
- Installation: github releases
- taskwarrior-tui version: v0.23.6
- task version: 2.6.1

**Comment by kdheepak** [comment]
Can you use `hexyl` or any other binary inspecting tool to try to figure out what’s in the data? My best guess is the Unicode encoding somehow got messed up but I have no idea how that would happen.

**Comment by kdheepak** [comment]
There should also be a log file in the .task folder from taskwarrior-tui that might have some clues into what is going on. 

There’s a couple of Python packages that you can use to run locally and find what is the Unicode encoding of your file and your backup file. Can you try something like that and see if they are the same? If they are not, somehow the encoding of the data got messed up. 

taskwarrior-tui only interacts with taskwarrior and never touches any data file directly. So I’m not quite sure what is happening here.

**Comment by Petemir** [comment]
> Can you use `hexyl` or any other binary inspecting tool to try to figure out what’s in the data? My best guess is the Unicode encoding somehow got messed up but I have no idea how that would happen.

Sure

```
$ hexdump completed.data.old 
0000000 0000 0000 0000 0000 0000 0000 0000 0000
*
0069080 0000 0000 0000 0000 0000 0000 0000     
006908d
```

It seems that it is not only the encoding, the whole file got zeroed. The only log file I can find is on ~/local/share/taskwarrior-tui/taskwarrior-tui.log, but the first entry is after I found the issue. In the ~/.task folder, I only have the .data files (backlog, completed, pending, undo).

Given that it is whole zeroes, it may be some filesystem corruption. I am at a loss, and if taskwarrior-tui doesn't touch any files (now that I think about it, yeah, it shouldn't), I think this is better closed. Sorry!

**Comment by kdheepak** [comment]
I’m sorry that happened, there’s annoying. 

Did you have taskwarrior-tui running with regular updates? ie is it doing refreshes periodically?

**Comment by Petemir** [comment]
@kdheepak Hello, sorry, I travelled for the Holidays and totally forgot about this. I am not sure what you are asking about though :) , but if I add some task out of the app with the `task` command, it does appear in `taskwarrior-tui` (I don't know if you are talking about this type of updates or updating the app, which indeed is in the last version).
