### ISSUE TITLE
Can't see UNTIL field

### ISSUE THREAD

**Issue by traycerb** [kdheepak/taskwarrior-tui#480]
One of the date fields is `UNTIL` which auto-expires tasks after the `UNTIL `time is reached. From the [docs](https://taskwarrior.org/docs/using_dates/):

```
...but this is the kind of task where I don't want to complete it late,
 I'd rather just forget it, and wish Alice a belated happy birthday in 
person. I could simply delete or complete the task, but there is 
another option, which is to add an until date:

$ task add Send Alice a birthday card \
           due:2016-11-08 \
           scheduled:2016-11-04 \
           wait:november \
           until:2016-11-10

```

This shows up in my `task` command line reports, but not the TUI

Commandline:
![taskwarrior tui until](https://user-images.githubusercontent.com/4313283/211132337-ef1eafb3-25a4-47e1-946a-c85b21c28d13.png)

taskwarrior-tui

![taskwarrior tui until 02](https://user-images.githubusercontent.com/4313283/211132346-379d0d38-d537-4b0f-bfb7-6c9d9374fd5e.png)

I'm on tui 0.23.6 and task 2.6.1 on WSL

kdheepak I understand you are taking a break these days, so just posting this for later, when/if you resume.

Additionally (and I can make this a separate issue when you are back to working on this), is there any way to not hide empty columns fields?  Somehow TaskWarrior and Taskwarrior-TUI both make decisions about which empty fields to ignore, and they aren't always the same.  While hiding columns that are empty in all tasks is clever and desirous in most cases, I prefer a column showing empty fields, as it stays the same visually as I update the fields (or even better, an option to for certain columns to: 1) always show or 2) hide if empty).  But this latter point might be a better discussion in the taskwarrior repo...

**Comment by kdheepak** [comment]
Thanks for opening the issue (and for being considerate, and even not tagging me! I appreciate the gesture). 

When I get back to it, I’ll look into this. The TUI is supposed to show the exact same results as taskwarrior. 

Yes, please open a new issue here! It’ll be easy to add a “always slow” option here.

**Comment by mediapathic** [comment]
I believe this is an addendum, though it could be a separate issue: I've also noticed that a 'scheduled' column, which shows up fine in taskwarrior, does not appear if the same report is called by taskwarrior-tui.

**Comment by kdheepak** [comment]
Hi @traycerb, thanks for being patient about this.

I just looked into this and I'm seeing `Until` in my columns. 

<img width="747" alt="image" src="https://github.com/kdheepak/taskwarrior-tui/assets/1813121/9b1d85e4-a1fc-4331-ab06-0d660a4b1807">

This is with an empty `.taskrc` file. Is there something in your .taskrc that might be preventing it from showing the until column?

**Comment by kdheepak** [comment]
With the following `report.next.labels`, I'm seeing a `scheduled.relative` column as well but no `scheduled.countdown`:

```
report.next.labels=ID,Active,Age,Deps,P,Project,Tag,Recur,S,Scheduled,Due,Until,Description,Urg
report.next.columns=id,start.age,entry.age,depends,priority,project,tags,recur,scheduled.countdown,scheduled.relative,due.relative,until.remaining,description.truncated_count,urgency
report.next.filter=(status:pending or status:waiting)
```


<img width="1512" alt="image" src="https://github.com/kdheepak/taskwarrior-tui/assets/1813121/d4f87395-043f-4ef6-b357-b675bce1e4e1">

`schedule.countdown` is not implemented yet though. Only the following attributes are implemented:

https://github.com/kdheepak/taskwarrior-tui/blob/4abb3bdbc826807205f22c7c60420dc15fc90d02/src/task_report.rs#L256-L446

**Comment by kdheepak** [comment]
If you share what your `.taskrc`s `report.next.columns` values, I'll be able to add them into this function.
