### ISSUE TITLE
New release on crates.io?

### ISSUE THREAD

**Issue by alichtman** [kdheepak/taskwarrior-tui#506]
https://crates.io/crates/taskwarrior-tui

The latest version there is 0.5.3, and the latest on github is 0.24.2.

It would be great if I could just run `cargo install taskwarrior-tui` to install this.

**Comment by kdheepak** [comment]
Thanks for opening an issue! I was waiting for a new version of `task-hookrs` to be released which appears to have happened a couple of days ago. 

I have published a new version on crates now: https://crates.io/crates/taskwarrior-tui/0.25.0

I will be publishing another v0.25.1 later today.

**Comment by alichtman** [comment]
Thanks!
