### ISSUE TITLE
Expand task ID in command

### ISSUE THREAD

**Issue by nickwynja** [kdheepak/taskwarrior-tui#51]
Thanks for making this! I've been curious about Taskwarrior for a while and a tui exactly like this was the missing piece for me.

**Description**

I would like to use the new custom command to integrate with other scripts, like for example pulling data out of the DOM for the current task and acting on it. To be able to get data out of the DOM and pass into other scripts, I'd like to be able to pass the ID of the currently selected task into a command.

**Solution**

For example, assume I have a UAD called `URL`. With a command, I'd like to be able to open this URL in a browser. On the command line, I'm able to run something like `open $(task _get 1.url)` to open the URL. If I could do something like `! open task _get {id}.url`, where `{id}` is replaced with the selected task ID, then I'd be able to execute scripts based on the selected task.

**Additional context**

I'm sure many other variables would be useful to expand in commands, much like you can in vim. Thanks again!

**Comment by kdheepak** [comment]
That is a awesome idea! It should be straightforward to implement too.

I think in addition to what you suggested, we could add something that let's you define custom commands in your `.taskrc` and define a keyboard shortcut to run them.

**Comment by nickwynja** [comment]
Yes, I love that idea! I would definitely use keyboard shortcuts for custom commands.

**Comment by kdheepak** [comment]
The first part should be more straightforward to implement now and will need to be implemented anyway for the keyboard shortcuts to work, but I'm not sure how useful that will be because it is a lot of manual typing, right? I'll test an implementation tonight.

The keyboard shortcut feature will be pending a rewrite to the event handling system (currently partly in progress here: https://github.com/kdheepak/taskwarrior-tui/pull/48). So I wouldn't hold your breath for this feature :) I can keep this issue open to track that development.

**Comment by nickwynja** [comment]
Ultimately the keyboard shortcuts will be the most helpful but expanding in the command is a step in the right direction. It will be some extra typing but I can use snippets or my clipboard manager to help with that in the meantime. I do also find expanding in the command helpful in one-off commands where it's not recurring enough to need a key binding.

Thanks again for taking a look at this. Happy to test a branch or PR.

**Comment by kdheepak** [comment]
I'm having issues with shell escaping `open $(task _get 1.url)` correctly in a way that it works as expected. I'm pushing features to this branch at this point. I'll have to experiment more before making a PR for this, and I'll post updates on this thread.

**Comment by nickwynja** [comment]
Thanks @kdheepak! I'll check out the branch. I was also running into some issues with the above command not working properly in taskwarrior-tui. It's not surprising that the additional sub-shell caused by the `$()` doesn't work smoothly here. To work around that, I tried a wrapper script like this:

```sh
#!/bin/bash
# openTwUrl.sh TW_ID

URL=$(task _get $1.url)
open $URL
```

This way, I'd just need to run `openTwUrl.sh 1`  (or eventually `openTwUrl {id}`) and not have to deal with a sub-shell in the tui command shell. I'm still actually having some issues running many scripts in the command prompt. I'm getting the generic `failed to execute process` error. Any recommendations on how to help debug these issues? I'm not very familiar with rust.

**Comment by kdheepak** [comment]
The error message is currently awful for the command shell, and in the branch I made a change that should give you a better error message. If you are able to compile from source or use the artifact from here: https://github.com/kdheepak/taskwarrior-tui/suites/1480338946/artifacts/25590280, you'll get the better error message that will tell you what is going on. It always has to do with the shell split command not doing the right thing (or me not using it correctly).

**Comment by nickwynja** [comment]
@kdheepak I've been using this successfully for a while now and it's a great feature!

> I'm having issues with shell escaping `open $(task _get 1.url)` correctly in a way that it works as expected.

I've been thinking about this more and it seems unnecessary to support this level of sub-shell in the command prompt. Other applications like mutt and vim don't support this. I think it would be much more useful to have keyboard shortcuts run the scripts or commands.

Thanks again for building this. It's work great.

**Comment by kdheepak** [comment]
Thanks for sharing your experience! I haven't had too much time to dedicate to this, but hopefully soon! I would love to enable custom keyboard shortcuts in the near future.

**Comment by kdheepak** [comment]
Sorry this took so long to get to! I've finally added custom keyboard shortcuts. Would you be able to try it out, I think this will satisfy your use case. 

I've posted an example of how to set it up in this comment here: https://github.com/kdheepak/taskwarrior-tui/issues/140#issuecomment-801930419.

**Comment by kdheepak** [comment]
The user defined shortcut feature is available in the following release: https://github.com/kdheepak/taskwarrior-tui/releases/tag/v0.12.0

**Comment by nickwynja** [comment]
I just tried this out and it works great! Thanks for adding.

**Comment by kdheepak** [comment]
Great! I’ll close this issue. Feel free to open issues if something else comes up!
