### ISSUE TITLE
Can't go to next pageHeight

### ISSUE THREAD

**Issue by piotryordanov** [kdheepak/taskwarrior-tui#510]
Help menu says that `J: {selected+=pageheight} `

When I press `J`, the cursor goes to the last line, but does not change pages.
So, I end up being unable to view all tasks once the total number fills the viewport.

Is this a bug, or am I missing something?

**Comment by kdheepak** [comment]
`J` is supposed to be the equivalent of pressing `j` `N` times where `N` is the page height (or terminal height). 

Is there something else you'd like `J` to do instead?

**Comment by piotryordanov** [comment]
As you can see in the picture, `task +in` contains 33 tasks
But, when i switch to context inbox (which is for `+in`) then i only get a fixed number of tasks.
How can i get them all?
![image](https://github.com/kdheepak/taskwarrior-tui/assets/48773775/756106aa-901f-4344-9397-81658d23ea4e)

**Comment by kdheepak** [comment]
Hmm, I don't understand why that's happening. What happens if you run `task export rc.json.array=on "+in"`? Do you see all the tasks? 

I need to add better debug statements in the log files so that it'll be easier to report what is going on. I'll make a few changes to the app soon and release a new version. With that it'll be easier to debug stuff like this.

**Comment by piotryordanov** [comment]
Ok here's another way to reproduce the bug:
1. Create a new context called `test` --> `context.test.read=+test` in `taskrc`
2. Run the following:
```bash
task add +test asd
```
3. open taskwarrior-tui -- it will display that task
4. Now add new tasks with the tag test --> `+test 1` etc..
5. Add a total of 24 tasks, they will all be displayed
6. Now, keep on adding, and you will see that any new task will NOT be displayed on tt

**Comment by piotryordanov** [comment]
Actually, i just realized that `g` and `G` behave the same as `J` and `K` !

**Comment by kdheepak** [comment]
`g` and `G` go to the first and last task in your list. `J` and `K` move the cursor down and up the screen size. 

I think in your case the number of tasks is lesser than the screen size. 

Thanks for sharing a reproducible case, I’ll look into it next week.

**Comment by piotryordanov** [comment]
When the number of tasks if greater than the screen size, `J` and `K` do not take me down and up the screen size :(

**Comment by piotryordanov** [comment]
hey @kdheepak  so not only can i not get to the next page, but the screen size seems to be hard coded regardless of the height of my screen.

For example, if i use a 27` monitor in portrait mode, i still get only 24 max tasks

**Comment by kdheepak** [comment]
Thanks for reporting. What terminal emulator / operating system etc are you using? Can you use tput and print out the size of your terminal?

When you say you only get 24 tasks, is anything being drawn below that?

**Comment by kdheepak** [comment]
Like, what happens when you press `/`? Do you see a task filter prompt? If yes, where on the screen does it show?

**Comment by piotryordanov** [comment]
I'm on arch, using alacritty, but i tried with kitty and have the same issue.

![image](https://github.com/kdheepak/taskwarrior-tui/assets/48773775/14fbebbc-2fab-4fdf-b7b7-7dcb2e449402)
That's how it looks like. On the right is the out of task, and on the left the same for taskwarrior TUI (using `task context none`)

If i press `J` or `K`, the 'page' does not change.


If i press `/` it just shows on the bottom of the screen.

How do i use `tput`?

**Comment by piotryordanov** [comment]
Oh wow, i figured it out!
I just had to change reports. 
```
taskwarrior-tui -r next  # fails to show all
```

```
taskwarrior-tui -r all # or any other report really, and bam i have everything i want
```

Even if i override the next report in taskrc, it still shows this limited view

**Comment by piotryordanov** [comment]
![image](https://github.com/kdheepak/taskwarrior-tui/assets/48773775/4d0d1e13-d005-45c0-ace2-b2455b801f8f)

So, the default report has the `limit:page` forced into it.
If i add it to my `uda`, then i also get the page stuck.

**Comment by piotryordanov** [comment]
Also, it's not clear that 
`uda.taskwarrior-tui.task-report.next.filter=status:pending` 
this should not contain the report name, but rather the filter of the report
