### ISSUE TITLE
`uda.taskwarrior-tui.keyconfig.next-tab=ú` not working

### ISSUE THREAD

**Issue by ferdinandyb** [kdheepak/taskwarrior-tui#517]
**Describe the bug**

I tried mapping 

```
uda.taskwarrior-tui.keyconfig.next-tab=ú
uda.taskwarrior-tui.keyconfig.previous-tab=ő
```
since `][` are awkward to access on my Hungarian layout and these letters happen to be physically in the same place. Remapping to say `w` works, so I'm guessing the error is not explicitly in my config, but either how the config file is parsed or how `taskwarrior-tui` interprets the character.

**To Reproduce**

- [ ] Reproducible using the test data located here: <https://github.com/kdheepak/taskwarrior-testdata/>

Switch your keyboard to Hungarian, add the above keyconfigs to your taskrc and then try switching tabs by pressing the key that is physically where ] and [ are on a UK keyboard (possibly verify that you are indeed getting ú and ő. Tabs will _not_ switch. This should be data agnostic.

**Environment (please complete the following information):**

- Operating System: Linux
- Installation: cargo install taskwarrior-tui
- taskwarrior-tui version:

```bash
taskwarrior-tui 0.25.3
```

- task version:

```bash
❯ task --version
2.6.1
```

**Comment by kdheepak** [comment]
Thanks for opening the issue, this was my bad. I was checking the length of the string and expecting it to be just "one character" but what I was really checking for was whether it was one byte; and multi-byte characters (e.g. `ú`) were being silently ignored.

I've made a PR that will fix this. I still need to improve a lot of the error propagation to show the user exactly what `taskwarrior-tui` is doing. For now, I've added a `error!` that will show up the logs. 

Better errors will happen once #349 is complete.

**Comment by kdheepak** [comment]
It's also possible that there are other unicode encoding related issues lurking or assumptions that I've made that are incorrect. Please open issues if you encounter any of them!

**Comment by kdheepak** [comment]
This should be fixed in https://github.com/kdheepak/taskwarrior-tui/releases/tag/v0.25.4.

**Comment by ferdinandyb** [comment]
Thanks, can confirm it now works! Also thanks for the speed :)
