### ISSUE TITLE
How to change month in Calendar?

### ISSUE THREAD

**Issue by kind-ice** [kdheepak/taskwarrior-tui#526]
I'm probably crazy but I think I looked everywhere and tried everything yet I'm not able to change months in calendar (I know keys for changing years, that works). My question is thus:

**What keys to use to move from eg January to September?**

**Comment by kdheepak** [comment]
I believe by default you can scroll up and down using the j and k keys.

**Comment by kind-ice** [comment]
Hmm, **j** and **k** for me change the year and nothing else.

**Comment by kdheepak** [comment]
Sorry for not responding sooner. I'll keep this issue open if that's okay with you. I'm working on an update where I'm planning on fixing this issue.

**Comment by astr0gator** [comment]
I still have the same issue. What am I missing?
