### ISSUE TITLE
Failure to build in WSL2 / Ubuntu

### ISSUE THREAD

**Issue by jepace** [kdheepak/taskwarrior-tui#55]
I'm trying to get it working on Windows 10 WSL2 in a Ubuntu client.  I couldn't choose which release file to try, so I thought I'd just build it.

When 'cargo build --release' gets to:
 Compiling taskwarrior-tui v0.9.3, I get 3 errors of the form:

error[E0658]: use of unstable library feature 'str_strip': newly added
--> src/app.rs:183:53

also src/app.rs:190:67 and app.rs:838:41

(Sorry, I don't have copy/paste working)

**Comment by kdheepak** [comment]
Thanks for opening an issue! This is related to https://github.com/kdheepak/taskwarrior-tui/issues/28, right? I believe you have to use the most recent version of the rust compiler.

**Comment by jepace** [comment]
Looks like it.  Thanks!
