### ISSUE TITLE
missing columns

### ISSUE THREAD

**Issue by adriangalilea** [kdheepak/taskwarrior-tui#550]
My setup
```
task config report.next.columns id,start.age,project,description,tags,depends,scheduled.countdown,due.relative,until.remaining,priority,urgency
```
```
task config report.next.labels 'ID,started,project,description,tags,dep,sch,due,unt,p,urg'
```

task:
<img width="1107" alt="image" src="https://github.com/kdheepak/taskwarrior-tui/assets/90320947/1a1e88c5-7009-426c-af23-8352e1f10d8e">

taskwarrior-tui
<img width="1081" alt="image" src="https://github.com/kdheepak/taskwarrior-tui/assets/90320947/bc357db5-e734-4361-8099-71430e56802a">

Notice the sch column is missing.

**Comment by RedEtherbloom** [comment]
Does any of the tasks have a scheduled value set? If yes, it may actually be a taskwarrior configuration option doing this.

https://manpages.debian.org/testing/taskwarrior/taskrc.5.en.html#print.empty.columns=1

The default value for this is 0, the manpage is written a bit weirdly.

(I'm not too familiar with how the main view is rendered, but would suspect that taskwarrior-tui is not getting the necessary information passed to it)

**Comment by kdheepak** [comment]
It probably is getting the information. Currently the columns parsed from the user configuration are explicitly written out, so if I haven't accounted for `schedule.countdown` it won't show up.

This match block is what needs to be updated with an additional case:

https://github.com/kdheepak/taskwarrior-tui/blob/4902ecdb34c549ed917635cce13148c13ac46106/src/task_report.rs#L255-L266
