### ISSUE TITLE
Specify tag during task add functionality

### ISSUE THREAD

**Issue by muraii** [kdheepak/taskwarrior-tui#551]
**Description**

I would like to be able to specify a tag and/or project while adding a task in the TUI.

**Solution**

Add parsing logic to the input to the add-tag functionality.

**Additional context**

I've looked through the documentation and searched the code in the repo and didn't notice anything indicating this already works.

**Comment by kdheepak** [comment]
I would like to make it easier to do this in the future with a better UI but right now you can hit `a` for add and then type `"get milk" +grocery project:chores` and it should add the tag and project for the task. Hitting <TAB> after `+` or `project:` should also give you context aware autocomplete. Does that not work for you?

**Comment by muraii** [comment]
> I would like to make it easier to do this in the future with a better UI but right now you can hit `a` for add and then type `"get milk" +grocery project:chores` and it should add the tag and project for the task. Hitting after `+` or `project:` should also give you context aware autocomplete. Does that not work for you?

It _does_, in fact, work. Not sure if it's something in my terminal setting, but when I hit `a` I get a matching set of double quotes. I've never tried to move outside the closing double quote to specify anything; I assumed--obviously incorrectly--that all the input to that function in the TUI had to be within the double quotes. That's what I get for assuming!

Maybe just an example in the documentation showing that would help?

**Comment by lyleberman** [comment]
Using the shortcuts is a dirty method of assigning a tag---

In .taskrc add this:

> uda.taskwarrior-tui.shortcuts.1=~/.task/tui/dinner.sh

then create a shell script ~/.task/tui/dinner.sh:
> task rc.bulk=0 rc.confirmation=off rc.dependency.confirmation=off rc.recurrence.confirmation=off "$@" modify tag:dinner

That assigns the task "dinner" by pressing 1.
