### ISSUE TITLE
How to create a context

### ISSUE THREAD

**Issue by Fubukimaru** [kdheepak/taskwarrior-tui#57]
Hello!

Thanks for developing this tool. It's quite interesting :+1: 

It's not clear on the documentation how do we define a context, could you expand it?

Thanks!

**Comment by kdheepak** [comment]
You can type `! task context define personal +PERSONAL`. `!` lets you run a custom shell command.

**Comment by jeeeem** [comment]
> You can type `! task context define personal +PERSONAL`. `!` lets you run a custom shell command.

Is there gonna be an auto-completion?

**Comment by Fubukimaru** [comment]
I thought that this was a taskwarrior-tui feature! Sorry!
