### ISSUE TITLE
Switch current filter with shortcut

### ISSUE THREAD

**Issue by paj0sch** [kdheepak/taskwarrior-tui#577]
**Description**

I want to be able to apply a different filter by pressing a hotkey, e.g. pressing 1 shows all tasks of project X, pressing 2 shows all tasks of project Y etc.

I am fairly sure that this is already possible, but I have not been able to figure it out or find it in the documentation.

**Solution**

If already possible, provide a working example in the documentation.

**Additional context**

Love your project, thank you for your work.

**Comment by kdheepak** [comment]
Thanks for the kind words. A variant of this has already requested in https://github.com/kdheepak/taskwarrior-tui/issues/555. I'll reply there for the sake of consolidating.
