### ISSUE TITLE
possible to filter by project name?

### ISSUE THREAD

**Issue by rhaynes74** [kdheepak/taskwarrior-tui#59]
Hi folks, I have my tasks organized by project, is it possible to quickly search via project name?

**Comment by kdheepak** [comment]
You can hit `/` and type `project:project_name` to filter the current task list. Does that answer your question?

**Comment by rhaynes74** [comment]
Yes - fantastic!  I was trying to use Project:project_name, the upper case P caused a problem!

Sincerely,

Dr. Ronald D. Haynes

Professor, Department of Mathematics and Statistics
Chair, MSc and PhD Scientific Computing Programs
Memorial University of Newfoundland

We acknowledge that the lands on which Memorial University’s campuses are situated are in the traditional territories of diverse Indigenous groups, and we acknowledge with respect the diverse histories and cultures of the Beothuk, Mi’kmaq, Innu, and Inuit of this province.

**Comment by kdheepak** [comment]
Great! Feel free to ask more questions if you run into any issues! Hope you are having a productive time :)
