### ISSUE TITLE
Ansi color doesn't work in Task Detail Pane

### ISSUE THREAD

**Issue by rockydd** [kdheepak/taskwarrior-tui#60]
**Describe the bug**
The ansi color isn't handled correctly. Instead, it show the color code like this:

[4mName         [0m [4mValue                                                     [0m
![iShot2020-12-10 21 26 10](https://user-images.githubusercontent.com/64197/101866693-583f2600-3b2e-11eb-8eb5-9d5b33dfe72c.png)

**To Reproduce**

**Environment (please complete the following information):**

- Operating System: Mac
- Installation: homebrew
- taskwarrior-tui version: taskwarrior-tui 0.9.4

```bash
taskwarrior-tui --version
```
- task version: 2.5.1
```bash
task --version
```

**Additional context and information**

**Comment by kdheepak** [comment]
Oh wow that is so surprising. Which terminal emulator are you using? Can you print out your `TERM` environment variable?

**Comment by rockydd** [comment]
Thanks, kdheepak!

I tried xterm-256color, xterm, and empty. All the same.
BTW, the color works fine in the task list panel (top panel).

**Comment by kdheepak** [comment]
Oh I see what is going on. This line needs to be changed:

https://github.com/kdheepak/taskwarrior-tui/blob/dfcfc0890e438995ae15e107d00400e8402541c6/src/app.rs#L507

to add `rc.color=off`. I'll make a PR, fix and cut a new release.

**Comment by kdheepak** [comment]
This should be resolved in https://github.com/kdheepak/taskwarrior-tui/releases/tag/v0.9.5.

**Comment by rockydd** [comment]
When this new version can be updated to homebrew?

**Comment by kdheepak** [comment]
The brew workflow seems to be broken. I'll manually update the homebrew tap. You can get the latest mac prebuilt binary from over here for now: https://github.com/kdheepak/taskwarrior-tui/releases/download/v0.9.5/taskwarrior-tui-x86_64-apple-darwin.tar.gz

**Comment by rockydd** [comment]
Thanks, kdheepak. However, 0.9.5 still has the same issue. I tried the version in homebrew and the tar file above.

**Comment by kdheepak** [comment]
Would it be possible to share your `.taskrc` file?

**Comment by rockydd** [comment]
Here it is.
`color=on
_forcecolor=on
uda.estimate.label=Estimate
uda.estimate.type=duration
`

**Comment by rockydd** [comment]
It works after commenting out `_forcecolor=on` :)

**Comment by kdheepak** [comment]
Oh neat! I should have thought about that, sorry! It makes sense now.

**Comment by Barbarossa93** [comment]
To clarify @rockydd, are the colors visible for you in the details pane, and/or the escape sequences are now gone? In my case, the colors don't appear but there are no escape sequences. Are there suppose to be colors in the details pane @kdheepak ?

**Comment by kdheepak** [comment]
Related to #10 

Right now I'm using `rc.color=off` so there shouldn't any ANSI sequences and any colors. The way the TUI works is that for anything that I want to show, I have to convert it to `Char`s and the `Style` for that particular character. That gets stored in a `Matrix` / `Grid` and that buffer is drawn to the screen based on the diff that's already on the screen. Meaning, when `task 1 info` outputs text, I can't just take the ansi characters and pass them over to the buffer. If I do that, ANSI characters will show up. I have to figure out what the logic is for applying for those colors and re-implement them. Most of this is already done though, and I'm slowly progressing through applying the colors in more places.
