### ISSUE TITLE
Editing the task using vim instead of nano

### ISSUE THREAD

**Issue by at8i** [kdheepak/taskwarrior-tui#61]
When I press "e" to edit the task, I am in nano env. Is it possible to edit the text in vim Env?
**Additional context**
A little more explanation on how to use TUI settings in taskrc would be helpful for a noob like me. 
For example if I want to add calendar to the main overview and etc.
All in all : A documentation . This is great cml tool . Thanks for the effort.

**Comment by kdheepak** [comment]
> When I press "e" to edit the task, I am in nano env. Is it possible to edit the text in vim Env?

Can you add `export EDITOR=vim` in your bashrc or into your environment and try again?

> A little more explanation on how to use TUI settings in taskrc would be helpful for a noob like me.
> For example if I want to add calendar to the main overview and etc.

Currently it is not possible to add the calendar to the main view (but I can add this as a feature), I usually just have a two terminals open, one with the calendar and a split next to it open with the task report panel. That's the screenshot in the README. I'll make the documentation more clearer about this.

**Comment by at8i** [comment]
Sorry about the delayed answer. I made vim my default editor in my environment (/etc/environment) and in bashrc.
Also I am using ubuntu 20.04 with fish as my default shell , I do not know if it makes a difference or not. 
After adding vim as my default editor, I tried editing in taskwarrior-tui ; both in fish and bash , I went into nano env again on both.
Is it supposed to go to vim ? if it is I guess It might be related to my setup.
Thanks for clarifying it.
Task warrior-tui has made working with taskwarrior much more visual and interactive for terminal junkies like me.

**Comment by kdheepak** [comment]
Can you run `task edit $task_id` from the command line? Which editor opens up then?

This is what I'm doing to open the editor:

https://github.com/kdheepak/taskwarrior-tui/blob/f1ded2713e8b6d1277e92ec525560c5310e177cf/src/app.rs#L1157

which is effectively `task edit $task_id`.

> After adding vim as my default editor, I tried editing in taskwarrior-tui ; both in fish and bash , I went into nano env again on both.

How did you add vim as your default editor? In my bashrc, I have the following:

```
export VISUAL="vim"
export EDITOR="$VISUAL"
```

You'll need to restart the terminal (or maybe even your computer) to have these changes propagate.

>  Task warrior-tui has made working with taskwarrior much more visual and interactive for terminal junkies like me.

Glad you are finding it useful! Feel free to open issues for any feature requests or bugs you come across.

**Comment by at8i** [comment]
Update: There is definitely a problem with fish shell ! IDK what it is . but now in bash after a restart , works like a charm. 
I can use it like this with no problems and I am 100% sure that fish bug is related to my setup. Close the issue  if you see fit. 
Thanks again

**Comment by kdheepak** [comment]
Great! I think fish doesn't read `~/.bashrc`, so you'll have to add the environment variable for the editor in there as well. I'll close this since it is not directly related to `taskwarrior-tui`. Feel free to ask questions by open more issues.

**Comment by wolass** [comment]
I am using zsh, and set up this:

```
export EDITOR="nvim"
export VISUAL="$EDITOR"
```
When I edit a ts kin taskwarrion command line it works as expected


nevertheless pressing `e`  still opens it up in some kind of a minimal vesrion of vim that is installed on my ubuntu somehow from "factory settings" can we explicitly predefine the preffered editor in the tui dotfile?

**Comment by kdheepak** [comment]
taskwarrior-tui runs the subprocess task edit in the default shell. I imagine the environment variables in your default shell are not configured to find nvim?
