### ISSUE TITLE
Quantity of tasks annotations

### ISSUE THREAD

**Issue by suhrobina** [kdheepak/taskwarrior-tui#62]
**Description**

I usually turn off Task Info to see more lines of pending tasks. I don't know which of them has annotations.

**Solution**

Could you please add q-ty of tasks annotations in square brackets?
For example:
    • go to grocery store[5]
    • send birthday card to Bob

**Comment by kdheepak** [comment]
This is a good idea and has been on my list of things to do.

**Comment by kdheepak** [comment]
This is related to #65 and this should be fixed in this release: https://github.com/kdheepak/taskwarrior-tui/releases/tag/v0.9.6.
