### ISSUE TITLE
 Convenient work with projects

### ISSUE THREAD

**Issue by suhrobina** [kdheepak/taskwarrior-tui#63]
**Description**

Often I use a filter to display a list of tasks that relate to a specific project. When adding tasks, I have to enter the name of the project every time.

**Solution**

Could you add auto completion or something like that to easily choose project during adding task. Or you could add one more view - Projects.

**Comment by kdheepak** [comment]
I would have to think about how to implement autocomplete. I think at the very least I'd like to implement a command history.

**Comment by kdheepak** [comment]
Tab autocomplete works for projects, tags, priority and due dates right now. You can try it out in this release: https://github.com/kdheepak/taskwarrior-tui/releases/tag/v0.13.7.

**Comment by kdheepak** [comment]
Here's a gif of it in action:

![](https://user-images.githubusercontent.com/1813121/113711977-cfcb2f00-96a2-11eb-8b06-9fd17903561d.gif)
