### ISSUE TITLE
Could the annotations expand over the whole width instead of the text wrapping up?

### ISSUE THREAD

**Issue by gbstan** [kdheepak/taskwarrior-tui#70]
I really love this programme. I was wondering if it would be possible to have the annotations in the second panel expand to take advantage of the width available instead of the text wrapping up over several lines irrespective of the size of the terminal?

**Comment by kdheepak** [comment]
Probably. The way it is currently is the way taskwarrior presents that information. Can you clarify why you'd want it to be compressed?

**Comment by gbstan** [comment]
I do not want it to be compressed. On the contrary, I would like the annotation text to take advantage of the available terminal window width available.
Currently when using
> task task_number
all the annotation text for the task with task number task_number appear using the whole width available in the terminal window.
In taskwarrior-tui, long annotation text is wrapped up over several lines in the second panel that gives details of the task.

**Comment by kdheepak** [comment]
Just to clarify, are you talking about annotations of a task or the description of the task?

**Comment by kdheepak** [comment]
On the left is the output of `taskwarrior` and on the right is the output of `taskwarrior-tui`:

<img width="1430" alt="Screen Shot 2021-02-16 at 4 40 27 AM" src="https://user-images.githubusercontent.com/1813121/108058317-1a202000-7011-11eb-9f7e-75545607067a.png">

I've added an annotation of random letters that was longer than the terminal width. In `taskwarrior` it wraps around but it `taskwarrior-tui` it is truncated by the terminal width. Is that what you are talking about?

**Comment by gbstan** [comment]
What happens for a full screen window terminal on my side is that taskwarrior expands the annotation to the width of the window and wraps the text if it is longer that the width but taskwarrior-tui wraps the text of the annotations at a fixed width irrespective of the window width.

**Comment by gbstan** [comment]
It would be very good if the text in the annotation wraps when it reaches the full width of the terminal or "box" which contains it. This is wha taskwarrior does in the terminal window.

**Comment by kdheepak** [comment]
I got it, thanks for the clarification. I'll look into that!

**Comment by gbstan** [comment]
Thank you!

**Comment by kdheepak** [comment]
This feature should be available in this release: https://github.com/kdheepak/taskwarrior-tui/releases/tag/v0.10.4

**Comment by gbstan** [comment]
This is great! Thank you so much for being so responsive. I have tested this a bit more. It is almost there. The only thing is that when resizing the window to smaller sizes, I have noticed that some (one or two) characters are cut from the end of a line to the next one when the text wraps. This might be due to the fact that the border within which the annotation text is enclosed makes the space available for the text a bit less than the actual width of the terminal window. If you could have  a look into this to actually not loose some characters at the end of a line when the text wraps (easy to spot when reducing the width of the window) that would be very much appreciated.

**Comment by kdheepak** [comment]
You are right! Nice catch! I'll make a new release with this change shortly :)

**Comment by gbstan** [comment]
I still see the task details missing a couple of characters when the line wraps. Maybe this has already been fixed in a future release?

**Comment by kdheepak** [comment]
I meant to make a new release sooner but didn't get to it. It is fixed in the latest master, but I'll be making a new release this week.

**Comment by kdheepak** [comment]
I've made a new release that should have a fix for this issue: https://github.com/kdheepak/taskwarrior-tui/releases/tag/v0.11.0
