### ISSUE TITLE
[Bug] Crash on date filter with hyphen `end:-`

### ISSUE THREAD

**Issue by Nukesor** [kdheepak/taskwarrior-tui#77]
**Describe the bug**

Hard crash on specific filter input:
```
[taskwarrior-tui error]: Failed to create a Task from JSON. Please report as a github issue on https://github.com/kdheepak/taskwarrior-tui
```

**To Reproduce**

Use this filter: `status:pending end:today-`
As soon as one types the `-` character taskwarrior-tui crashes with the error message above.
It seems as soon as there's a `-` behind the `end:` filter, it crashes.

As soon as I've seen from the taskwarrior example page, this should be valid:
`task end.after:today-1wk completed`

The same error occurs if one filters with `start:-`, so it seems to be related to (date?) filters in general.

**Environment (please complete the following information):**

- Operating System: Arch linux
- Installation: pacman
- taskwarrior-tui version: `taskwarrior-tui 0.9.12`
- task version: `2.5.3`

**Additional context and information**
![Peek 2021-02-09 17-07](https://user-images.githubusercontent.com/3322822/107391764-4f9ca900-6af9-11eb-84e7-a908af11e3c7.gif)

Anyhow, thanks for writing this! It's a excellent and modern alternative to `vit`.
I'll try to contribute, as soon as I find some time :)

**Comment by kdheepak** [comment]
Interesting. I didn't know about `end.after:today-1wk`. I'll look into this.

**Comment by kdheepak** [comment]
![taskwarrior-filter mov](https://user-images.githubusercontent.com/1813121/107405891-092d5700-6ac5-11eb-8520-939c1d15ca3d.gif)

**Comment by kdheepak** [comment]
I patched it such that it doesn't crash on an invalid filter. I'll make a new release with this.

**Comment by kdheepak** [comment]
This is fixed in this release: https://github.com/kdheepak/taskwarrior-tui/releases/tag/v0.9.13

**Comment by Nukesor** [comment]
Awesome! Thanks a lot :)
