### ISSUE TITLE
[Bug] Nothing happens when modifying a completed task

### ISSUE THREAD

**Issue by Nukesor** [kdheepak/taskwarrior-tui#78]
**Describe the bug**

One can modify a completed task, but nothing happens

**To Reproduce**

1. Create any task
2. Complete the task
3. Modify the task via `m` in the interface, change the name and press enter
4. Nothing happens

I would either expect an error message, that editing this task if forbidden or some extra logic, which set's the task to pending and modifies the name.

**Environment (please complete the following information):**

- Operating System: Arch linux
- Installation: pacman
- taskwarrior-tui version: `taskwarrior-tui 0.9.12`
- task version: `2.5.3`

**Comment by kdheepak** [comment]
Can you clarify what do you mean by "2. Complete the task"? As soon as you "complete" it it disappears from the list, no? When I complete a task, I hit the `d` key to perform the equivalent of `task done task_id`.

**Comment by Nukesor** [comment]
Sorry if I've been unclear.

After you set a task to `done`, the task disappears.
If one however removes all filters (`status:pending`), the task shows up again and one can `m` modify the completed tasks.

Doing so, however, doesn't do anything.
This is most likely due `task` not allowing this either, but it would be awesome if there would either be a convenient way to
1. either "undo" a task, i.e. re-schedule it, so one can  be edited
2. Do this automatically
3. Show a warning, that this isn't possible

**Comment by kdheepak** [comment]
Got it, I understand now. I'll look into this.

**Comment by kdheepak** [comment]
This should be resolved in this release: https://github.com/kdheepak/taskwarrior-tui/releases/tag/v0.9.14
