### ISSUE TITLE
[Enhancement] Add task status as extra column

### ISSUE THREAD

**Issue by Nukesor** [kdheepak/taskwarrior-tui#79]
**Description**

Task's CLI interface shows the current status with single capital letters.
This is super convenient, if one looks at the list of all tasks for a specific day.

**Solution**

Add another column (width 2), containing the current status as a character.

**Additional context**

![image](https://user-images.githubusercontent.com/3322822/107399920-94c4d900-6b01-11eb-949f-2f58332d5185.png)

**Comment by kdheepak** [comment]
What does your `~/.taskrc`'s `report.next.columns` look like?

**Comment by kdheepak** [comment]
Thanks for opening the issue! I've fixed it in a PR.

![Screen Shot 2021-02-09 at 12 47 40 PM](https://user-images.githubusercontent.com/1813121/107419414-0175ae80-6ad5-11eb-9ee2-a0b35d8d8575.png)

It'll be part of the next release.

**Comment by kdheepak** [comment]
This feature is now available in this release: https://github.com/kdheepak/taskwarrior-tui/releases/tag/v0.9.13

**Comment by Nukesor** [comment]
Wow, nice response time!
Thanks a lot for adding this :)
