### ISSUE TITLE
Task report does not work with long tasks

### ISSUE THREAD

**Issue by david-perez** [kdheepak/taskwarrior-tui#9]
```
thread 'main' panicked at 'attempt to multiply with overflow', src/app.rs:600:21
```

https://github.com/kdheepak/taskwarrior-tui/blob/master/src/app.rs#L600

Switching to `i32` fixes it, but I'm not sure why the `i16` limitation is in place. Additionally, it just moves the problem to a larger type.

**Comment by kdheepak** [comment]
Can you provide a reproducible example? I created a really long task but I'm not able to get the main thread to panic.

![Screen Shot 2020-08-30 at 11 01 49 PM](https://user-images.githubusercontent.com/1813121/91684452-cda16080-eb14-11ea-9524-3ab8add4ff8a.png)

**Comment by david-perez** [comment]
It only panics in debug builds: https://doc.rust-lang.org/book/ch03-02-data-types.html#integer-overflow

**Comment by kdheepak** [comment]
Are you building from source? All the releases on github are in `release` mode.

The screenshot above is when I tried `cargo run` which defaults to `debug` builds. I just tried it with `cargo run --release` and still no error. This can't be OS specific, can it? I'm on a MacOS.

Can you set `RUST_BACKTRACE=1` and share the full stacktrace? Are you sure it is just a long task that triggers this issue?

**Comment by david-perez** [comment]
I'm building from source on Linux. I've put a `dbg!(&task); dbg!(attr.len())`, the report fails when it encounters the following task:

"Design a scheme by which *necessary* data structures that the kernel will use (gpioCallbacks, ram_vector_table, etc...) are laid out at the beginning of RAM, while the unnecessary ones (mediaBuf, bootloader stuff) are laid out at the end. Calculate size of necessary stuff. Modify linker script of user apps so that .data/.bss sections begin after the necessary kernel ds"

which has 371 characters.

Stack trace:

```
   Compiling taskwarrior-tui v0.6.8 (/home/david/code/taskwarrior-tui)
    Finished dev [unoptimized + debuginfo] target(s) in 2.17s
     Running `target/debug/taskwarrior-tui`
thread 'main' panicked at 'attempt to multiply with overflow', src/app.rs:664:21
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1076
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1537
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:217
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:526
  11: rust_begin_unwind
             at src/libstd/panicking.rs:437
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  13: core::panicking::panic
             at src/libcore/panicking.rs:50
  14: taskwarrior_tui::app::TTApp::task_report
             at src/app.rs:664
  15: taskwarrior_tui::app::TTApp::draw_task_report
             at src/app.rs:490
  16: taskwarrior_tui::app::TTApp::draw_task
             at src/app.rs:230
  17: taskwarrior_tui::app::TTApp::draw
             at src/app.rs:199
  18: taskwarrior_tui::tui_main::{{closure}}
             at src/main.rs:56
  19: tui::terminal::Terminal<B>::draw
             at /home/david/.cargo/registry/src/github.com-1ecc6299db9ec823/tui-0.10.0/src/terminal.rs:210
  20: taskwarrior_tui::tui_main
             at src/main.rs:56
  21: taskwarrior_tui::main
             at src/main.rs:38
  22: std::rt::lang_start::{{closure}}
             at /home/david/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/rt.rs:67
  23: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
  24: std::panicking::try::do_call
             at src/libstd/panicking.rs:348
  25: std::panicking::try
             at src/libstd/panicking.rs:325
  26: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  27: std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  28: std::rt::lang_start
             at /home/david/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/rt.rs:67
  29: main
  30: __libc_start_main
  31: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by david-perez** [comment]
By the way, I had to capture `stderr` to a file to get the stacktrace because any output from this program looks like this in my terminal:

![screenshot-200901-1049-50](https://user-images.githubusercontent.com/6341745/91828843-f292f200-ec40-11ea-9182-541291715297.png)

I've tried `gnome-terminal`, `st` and `alacritty` with the same result.

**Comment by kdheepak** [comment]
Thanks for the detailed report! I'll try this on my machine. 

> By the way, I had to capture stderr to a file to get the stacktrace because any output from this program looks like this in my terminal

This is annoying, isn't it? Ideally it would never panic but when it does I'd like to revert the terminal settings so stacktraces are easier to read. I'll look into this as well.

**Comment by kdheepak** [comment]
Again, thanks for the detailed report, it really helped with the debugging. I fixed it here:

https://github.com/kdheepak/taskwarrior-tui/commit/6f73f472a8b948313618dd90eacd45b79a4e1194

Let me know if you want me to make a new release!

**Comment by david-perez** [comment]
It's ok, no need for a new release, it only breaks debug builds.

I was just wondering why the limitation to i16 exists

**Comment by kdheepak** [comment]
Good question. This is being used for the widths of the [`Table`], which is a array of [`Constraint`]s.

[`Table`]: https://github.com/fdehau/tui-rs/blob/aada695b3f792f1c2d919bd45c1f3e2bc043ed72/src/widgets/table.rs#L93

[`Constraint`]: https://github.com/fdehau/tui-rs/blob/aada695b3f792f1c2d919bd45c1f3e2bc043ed72/src/layout.rs#L24-L31

I am happy to hear feedback on better ways this could be done.
