### ISSUE TITLE
Keybinding

### ISSUE THREAD

**Issue by bepolymathe** [kdheepak/taskwarrior-tui#91]
Is there a way to change the allocation of keyboard keys? In particular to move up and down in the list? I don't use the usual vim shortcuts... 
Thanks!

**Comment by kdheepak** [comment]
I started writing a key configuration setup but haven’t gotten around to completing it yet. It is unfortunately probably lower on my priority list for the list of features I’d like to add. 

I’m curious what keys would you like to use instead?

**Comment by bepolymathe** [comment]
All right. Thank you for this clarification. I use the [bepo](https://en.wikipedia.org/wiki/B%C3%89PO) keyboard configuration optimized for French. But I think other users of variants (dvorak, colemaks, etc) might be interested. I think this is especially true for the keys allowing to go up and down in the list...

**Comment by kdheepak** [comment]
Ah, thanks for the information. Yeah, it does seem quite important for non-qwerty users. Do you use vim? Do you rebind your keys in vim? Just curious again.

**Comment by kdheepak** [comment]
This is a temporary hack, but you can modify the key bindings to your needs if you are willing to build from source. This is the section where all the keys are defined:

https://github.com/kdheepak/taskwarrior-tui/blob/69682227c948bbc5bac3a328a2c2459107324b5b/src/app.rs#L1380-L1673

**Comment by bepolymathe** [comment]
> Ah, thanks for the information. Yeah, it does seem quite important for non-qwerty users. Do you use vim? Do you rebind your keys in vim? Just curious again.

Yes --» [rebind to bépo](http://bepo.fr/wiki/Vim#.7E.2F.vimrc)

**Comment by bepolymathe** [comment]
> This is a temporary hack, but you can modify the key bindings to your needs if you are willing to build from source. This is the section where all the keys are defined:
> 
> https://github.com/kdheepak/taskwarrior-tui/blob/69682227c948bbc5bac3a328a2c2459107324b5b/src/app.rs#L1380-L1673

Ok, thanks you ! I will try this !

**Comment by kdheepak** [comment]
After experimenting a little more, I think it should be straightforward to support customizable key bindings. So I'll work on this sooner than later.

**Comment by bepolymathe** [comment]
Oh that's great. Thank you so much for your efforts and for this great tool.

**Comment by kdheepak** [comment]
I've added a key config support in the latest master. If you can try it out that'd be great! I'll use this for this week and if I don't think any issues, I'll make a new release with this feature.

**Comment by kdheepak** [comment]
I made a new release: https://github.com/kdheepak/taskwarrior-tui/releases/tag/v0.11.0

You can try the key configuration feature now. See this section in the README for more information: https://github.com/kdheepak/taskwarrior-tui#configure-taskwarrior-tui-using-taskrc

**Comment by bepolymathe** [comment]
Hey, thanks for that. It works for me too !
