### ISSUE TITLE
taskwarrior-tui ignores report.xxx.filter from ~/.taskrc

### ISSUE THREAD

**Issue by desbma** [kdheepak/taskwarrior-tui#92]
I have in my `~/.taskrc` the line:
`report.next.filter=status:pending or status:waiting`

However `taskwarrior-tui` always sets default filter to `status:pending`. It would be a great addition to parse that and set it as the default filter.

Thanks

Environment:
* Operating System: Arch Linux
* Installation: https://aur.archlinux.org/packages/taskwarrior-tui-git/
* taskwarrior-tui version: git b8c849e
* terminal : alacritty 0.7.1

EDIT: Sorry, I meant to create this issue as an enhancement request, not a bug, but it seems I can't change it.

**Comment by kdheepak** [comment]
This is available in this release: https://github.com/kdheepak/taskwarrior-tui/releases/tag/v0.10.0

Along with the fix for when it crashes occasionally.
