### ISSUE TITLE
Cannot use custom priorities

### ISSUE THREAD

**Issue by b1two** [kdheepak/taskwarrior-tui#94]
First of all, thanks for this new tool, looks promising.

**Description:**

When custom priorities are defined in `~/.taskrc` and a task uses such priority, taskwarrior-tui stops displaying the tasks.

**Steps to reproduce the behavior:**

In `~/.task/pending.data`:
```
[description:"mytask" entry:"1613257298" modified:"1613257298" priority:"U" status:"pending" uuid:"f2a1dba3-9576-4850-b68c-f962fff29cdd"]
[description:"my other task" entry:"1613257359" modified:"1613257359" status:"pending" uuid:"5c006712-9a6f-458b-8133-500e1c9b8508"]
```
In `~/.taskrc`:
```
data.location=~/.task
uda.priority.values=U,H,M,L
color.uda.priority.U=color1
urgency.uda.priority.U.coefficient=15.0
```

In that configuration, no task is displayed, however, removing the first line of `~/.task/pending.data` or change `priority:"U"` to `priority:"H"`, allows to preview the tasks in taskwarrior-tui.

**Environment:**

- Operating System: Debian 
- Installation: Github releases
- taskwarrior-tui version:
```bash
% taskwarrior-tui --version
taskwarrior-tui 0.9.15
```
- task version:

```bash
% task --version
2.5.3
```

**Comment by kdheepak** [comment]
This should be straight forward to fix. Thanks for opening a bug report!

**Comment by b1two** [comment]
Nice, thanks for the quick fix. Just tested it, works like a charm.

**Comment by kdheepak** [comment]
Thanks for opening the issue! I'm learning about new taskwarrior features because of this :)
